DELETE FROM hr_infoset_item WHERE pk_infoset_item in ('1001ZZ10000000005JUI', '1001ZZ10000000005JUJ');
INSERT INTO hr_infoset_item (accessor_classname, calculation, class_id, creationtime, creator, custom_attr, data_type, data_type_id, data_type_style, default_value, description, dr, dynamic_flag, enum_id, fixed_length, help, hided, id, is_active, is_authen, item_code, item_formula, item_formula_sql, item_name, max_length, max_value, meta_data, min_value, modifiedtime, modifier, not_serialize, nullable, pk_group, pk_infoset, pk_infoset_item, pk_main_item, pk_org, precise, read_only, ref_leaf_flag, ref_model_name, resid, respath, showorder, sub_formula, sub_formula_sql, ts, unique_flag, visibility, item_name2, item_name3, item_name4, item_name5, item_name6) VALUES (null, null, null, '2017-09-14 11:14:43', null, 'Y', 101, null, null, null, null, 0, null, null, null, null, 'N', null, null, null, 'glbdef14', null, null, '劳退开始日期', 19, null, null, null, null, null, null, 'Y', '~', (select pk_infoset from hr_infoset where infoset_name = '勞保勞退信息'), '1001ZZ10000000005JUI', '~', 'GLOBLE00000000000000', null, 'N', 'N', null, 'hi_psndoc_glbdef1_4019', '6007psn', 113, null, null, '2017-09-14 11:14:44', 'N', null, '勞退開始日期', null, null, null, null);
INSERT INTO hr_infoset_item (accessor_classname, calculation, class_id, creationtime, creator, custom_attr, data_type, data_type_id, data_type_style, default_value, description, dr, dynamic_flag, enum_id, fixed_length, help, hided, id, is_active, is_authen, item_code, item_formula, item_formula_sql, item_name, max_length, max_value, meta_data, min_value, modifiedtime, modifier, not_serialize, nullable, pk_group, pk_infoset, pk_infoset_item, pk_main_item, pk_org, precise, read_only, ref_leaf_flag, ref_model_name, resid, respath, showorder, sub_formula, sub_formula_sql, ts, unique_flag, visibility, item_name2, item_name3, item_name4, item_name5, item_name6) VALUES (null, null, null, '2017-09-14 11:14:43', null, 'Y', 102, null, null, null, null, 0, null, null, null, null, 'N', null, null, null, 'glbdef15', null, null, '劳退结束日期', 19, null, null, null, null, null, null, 'Y', '~', (select pk_infoset from hr_infoset where infoset_name = '勞保勞退信息'), '1001ZZ10000000005JUJ', '~', 'GLOBLE00000000000000', null, 'N', 'N', null, 'hi_psndoc_glbdef1_4034', '6007psn', 114, null, null, '2017-09-14 11:14:44', 'N', null, '勞退結束日期', null, null, null, null);
GO

update hr_infoset_item set showorder = 115 where pk_infoset = (select pk_infoset from hr_infoset where infoset_name = '勞保勞退信息') and item_code='glbdef7';
update hr_infoset_item set showorder = 116 where pk_infoset = (select pk_infoset from hr_infoset where infoset_name = '勞保勞退信息') and item_code='glbdef8';
update hr_infoset_item set showorder = 117 where pk_infoset = (select pk_infoset from hr_infoset where infoset_name = '勞保勞退信息') and item_code='glbdef13';
update hr_infoset_item set showorder = 118 where pk_infoset = (select pk_infoset from hr_infoset where infoset_name = '勞保勞退信息') and item_code='glbdef9';
GO

