ALTER DATABASE AECOMDB
SET RECOVERY SIMPLE;
GO
-- Shrink the truncated log file to 1 MB.
DBCC SHRINKFILE (AECOMDB_log, 1);
GO
-- Reset the database recovery model.
ALTER DATABASE AECOMDB
SET RECOVERY FULL;
GO