/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ta.timeitem;

import nc.md.model.IEnumValue;
import nc.md.model.impl.MDEnum;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
public class SettlementPeriodEnum extends MDEnum {
	public SettlementPeriodEnum(IEnumValue enumvalue) {
		super(enumvalue);
	}

	public static final SettlementPeriodEnum MONTH = MDEnum.valueOf(
			SettlementPeriodEnum.class, 0);
	public static final SettlementPeriodEnum YEAR = MDEnum.valueOf(
			SettlementPeriodEnum.class, 1);

	// ssx append on 2018-03-16
	// for start date of company age
	public static final SettlementPeriodEnum DATE = MDEnum.valueOf(
			SettlementPeriodEnum.class, 2);
	// 年資起算日
	public static final SettlementPeriodEnum STARTDATE = MDEnum.valueOf(
			SettlementPeriodEnum.class, 3);
	//

}
