/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.bd.team.team01.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 班组定义维护表头vo </b>
 * <p>
 * 班组定义维护表头vo
 * </p>
 * 创建日期:
 * 
 * @author huanglw
 * @version
 */
@SuppressWarnings("serial")
public class TeamHeadVO extends SuperVO {

    public static final String BSHIFTFLAG = "bshiftflag";
    //2019年1月8日11:42:13 Ares.Tank 使用年度补休
    public static final String ANNUALRESTFLAG = "annualrestflag";

    public static final String CTEAMID = "cteamid";

    public static final String PK_GROUP = "pk_group";

    public static final String PK_ORG = "pk_org";

    public static final String PK_ORG_V = "pk_org_v";

    public static final String VTEAMCODE = "vteamcode";

    public static final String VTEAMNAME = "vteamname";

    public static final String VTEAMNAME2 = "vteamname2";

    public static final String VTEAMNAME3 = "vteamname3";

    public static final String CWKID = "cwkid";

    public static final String CDEPTID = "cdeptid";

    public static final String CDEPTVID = "cdeptvid";

    public static final String CRESPONSIBLER = "cresponsibler";

    public static final String ENABLESTATE = "enablestate";

    public static final String CREATOR = "creator";

    public static final String CREATIONTIME = "creationtime";

    public static final String MODIFIER = "modifier";

    public static final String MODIFIEDTIME = "modifiedtime";

    public static final String VBNOTE = "vbnote";

    public static final String VDEF1 = "vdef1";

    public static final String VDEF2 = "vdef2";

    public static final String VDEF3 = "vdef3";

    public static final String VDEF4 = "vdef4";

    public static final String VDEF5 = "vdef5";

    public static final String VDEF6 = "vdef6";

    public static final String VDEF7 = "vdef7";

    public static final String VDEF8 = "vdef8";

    public static final String VDEF9 = "vdef9";

    public static final String VDEF10 = "vdef10";

    public static final String VDEF11 = "vdef11";

    public static final String VDEF12 = "vdef12";

    public static final String VDEF13 = "vdef13";

    public static final String VDEF14 = "vdef14";

    public static final String VDEF15 = "vdef15";

    public static final String VDEF16 = "vdef16";

    public static final String VDEF17 = "vdef17";

    public static final String VDEF18 = "vdef18";

    public static final String VDEF19 = "vdef19";

    public static final String VDEF20 = "vdef20";

    /**
     * 属性bshiftflag的Getter方法.属性名：轮班 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getBshiftflag() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("bshiftflag");
    }

    /**
     * 属性bshiftflag的Setter方法.属性名：轮班 创建日期:
     * 
     * @param newBshiftflag
     *            nc.vo.pub.lang.UFBoolean
     */
    public void setBshiftflag(nc.vo.pub.lang.UFBoolean newBshiftflag) {
        this.setAttributeValue("bshiftflag", newBshiftflag);
    }
    
    /**
     * 属性annualrestflag的Getter方法.属性名：轮班 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getAnnualrestflag() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("annualrestflag");
    }

    /**
     * 属性annualrestflag的Setter方法.属性名：轮班 创建日期:
     * 
     * @param newBshiftflag
     *            nc.vo.pub.lang.UFBoolean
     */
    public void setAnnualrestflag(nc.vo.pub.lang.UFBoolean annualrestflag) {
        this.setAttributeValue("annualrestflag", annualrestflag);
    }

    /**
     * 属性cteamid的Getter方法.属性名：班组 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCteamid() {
        return (java.lang.String) this.getAttributeValue("cteamid");
    }

    /**
     * 属性cteamid的Setter方法.属性名：班组 创建日期:
     * 
     * @param newCteamid
     *            java.lang.String
     */
    public void setCteamid(java.lang.String newCteamid) {
        this.setAttributeValue("cteamid", newCteamid);
    }

    /**
     * 属性pk_group的Getter方法.属性名：集团 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_group() {
        return (java.lang.String) this.getAttributeValue("pk_group");
    }

    /**
     * 属性pk_group的Setter方法.属性名：集团 创建日期:
     * 
     * @param newPk_group
     *            java.lang.String
     */
    public void setPk_group(java.lang.String newPk_group) {
        this.setAttributeValue("pk_group", newPk_group);
    }

    /**
     * 属性pk_org的Getter方法.属性名：业务单元 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org() {
        return (java.lang.String) this.getAttributeValue("pk_org");
    }

    /**
     * 属性pk_org的Setter方法.属性名：业务单元 创建日期:
     * 
     * @param newPk_org
     *            java.lang.String
     */
    public void setPk_org(java.lang.String newPk_org) {
        this.setAttributeValue("pk_org", newPk_org);
    }

    /**
     * 属性pk_org_v的Getter方法.属性名：业务单元版本 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org_v() {
        return (java.lang.String) this.getAttributeValue("pk_org_v");
    }

    /**
     * 属性pk_org_v的Setter方法.属性名：业务单元版本 创建日期:
     * 
     * @param newPk_org_v
     *            java.lang.String
     */
    public void setPk_org_v(java.lang.String newPk_org_v) {
        this.setAttributeValue("pk_org_v", newPk_org_v);
    }

    /**
     * 属性vteamcode的Getter方法.属性名：班组编码 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVteamcode() {
        return (java.lang.String) this.getAttributeValue("vteamcode");
    }

    /**
     * 属性vteamcode的Setter方法.属性名：班组编码 创建日期:
     * 
     * @param newVteamcode
     *            java.lang.String
     */
    public void setVteamcode(java.lang.String newVteamcode) {
        this.setAttributeValue("vteamcode", newVteamcode);
    }

    /**
     * 属性vteamname的Getter方法.属性名：班组名称 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVteamname() {
        return (java.lang.String) this.getAttributeValue("vteamname");
    }

    /**
     * 属性vteamname的Setter方法.属性名：班组名称 创建日期:
     * 
     * @param newVteamname
     *            java.lang.String
     */
    public void setVteamname(java.lang.String newVteamname) {
        this.setAttributeValue("vteamname", newVteamname);
    }

    /**
     * 属性vteamname的Getter方法.属性名：班组名称 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVteamname2() {
        return (java.lang.String) this.getAttributeValue("vteamname2");
    }

    /**
     * 属性vteamname的Setter方法.属性名：班组名称 创建日期:
     * 
     * @param newVteamname
     *            java.lang.String
     */
    public void setVteamname2(java.lang.String newVteamname2) {
        this.setAttributeValue("vteamname2", newVteamname2);
    }

    /**
     * 属性vteamname的Getter方法.属性名：班组名称 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVteamname3() {
        return (java.lang.String) this.getAttributeValue("vteamname3");
    }

    /**
     * 属性vteamname的Setter方法.属性名：班组名称 创建日期:
     * 
     * @param newVteamname
     *            java.lang.String
     */
    public void setVteamname3(java.lang.String newVteamname3) {
        this.setAttributeValue("vteamname3", newVteamname3);
    }

    /**
     * 属性vteamname的Getter方法.属性名：班组名称 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVteamname4() {
        return (java.lang.String) this.getAttributeValue("vteamname4");
    }

    /**
     * 属性vteamname的Setter方法.属性名：班组名称 创建日期:
     * 
     * @param newVteamname
     *            java.lang.String
     */
    public void setVteamname4(java.lang.String newVteamname4) {
        this.setAttributeValue("vteamname4", newVteamname4);
    }

    /**
     * 属性vteamname的Getter方法.属性名：班组名称 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVteamname5() {
        return (java.lang.String) this.getAttributeValue("vteamname5");
    }

    /**
     * 属性vteamname的Setter方法.属性名：班组名称 创建日期:
     * 
     * @param newVteamname
     *            java.lang.String
     */
    public void setVteamname5(java.lang.String newVteamname5) {
        this.setAttributeValue("vteamname5", newVteamname5);
    }

    /**
     * 属性vteamname的Getter方法.属性名：班组名称 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVteamname6() {
        return (java.lang.String) this.getAttributeValue("vteamname6");
    }

    /**
     * 属性vteamname的Setter方法.属性名：班组名称 创建日期:
     * 
     * @param newVteamname
     *            java.lang.String
     */
    public void setVteamname6(java.lang.String newVteamname6) {
        this.setAttributeValue("vteamname6", newVteamname6);
    }

    /**
     * 属性cwkid的Getter方法.属性名：工作中心 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCwkid() {
        return (java.lang.String) this.getAttributeValue("cwkid");
    }

    /**
     * 属性cwkid的Setter方法.属性名：工作中心 创建日期:
     * 
     * @param newCwkid
     *            java.lang.String
     */
    public void setCwkid(java.lang.String newCwkid) {
        this.setAttributeValue("cwkid", newCwkid);
    }

    /**
     * 属性cdeptid的Getter方法.属性名：部门编码 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCdeptid() {
        return (java.lang.String) this.getAttributeValue("cdeptid");
    }

    /**
     * 属性cdeptid的Setter方法.属性名：部门编码 创建日期:
     * 
     * @param newCdeptid
     *            java.lang.String
     */
    public void setCdeptid(java.lang.String newCdeptid) {
        this.setAttributeValue("cdeptid", newCdeptid);
    }

    /**
     * 属性cdeptvid的Getter方法.属性名：部门版本 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCdeptvid() {
        return (java.lang.String) this.getAttributeValue("cdeptvid");
    }

    /**
     * 属性cdeptvid的Setter方法.属性名：部门版本 创建日期:
     * 
     * @param newCdeptvid
     *            java.lang.String
     */
    public void setCdeptvid(java.lang.String newCdeptvid) {
        this.setAttributeValue("cdeptvid", newCdeptvid);
    }

    /**
     * 属性cresponsibler的Getter方法.属性名：负责人 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCresponsibler() {
        return (java.lang.String) this.getAttributeValue("cresponsibler");
    }

    /**
     * 属性cresponsibler的Setter方法.属性名：负责人 创建日期:
     * 
     * @param newCresponsibler
     *            java.lang.String
     */
    public void setCresponsibler(java.lang.String newCresponsibler) {
        this.setAttributeValue("cresponsibler", newCresponsibler);
    }

    /**
     * 属性enablestate的Getter方法.属性名：启用状态 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getEnablestate() {
        return (java.lang.Integer) this.getAttributeValue("enablestate");
    }

    /**
     * 属性enablestate的Setter方法.属性名：启用状态 创建日期:
     * 
     * @param newEnablestate
     *            java.lang.Integer
     */
    public void setEnablestate(java.lang.Integer newEnablestate) {
        this.setAttributeValue("enablestate", newEnablestate);
    }

    /**
     * 属性creator的Getter方法.属性名：创建人 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCreator() {
        return (java.lang.String) this.getAttributeValue("creator");
    }

    /**
     * 属性creator的Setter方法.属性名：创建人 创建日期:
     * 
     * @param newCreator
     *            java.lang.String
     */
    public void setCreator(java.lang.String newCreator) {
        this.setAttributeValue("creator", newCreator);
    }

    /**
     * 属性creationtime的Getter方法.属性名：创建时间 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getCreationtime() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("creationtime");
    }

    /**
     * 属性creationtime的Setter方法.属性名：创建时间 创建日期:
     * 
     * @param newCreationtime
     *            nc.vo.pub.lang.UFDateTime
     */
    public void setCreationtime(nc.vo.pub.lang.UFDateTime newCreationtime) {
        this.setAttributeValue("creationtime", newCreationtime);
    }

    /**
     * 属性modifier的Getter方法.属性名：最后修改人 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getModifier() {
        return (java.lang.String) this.getAttributeValue("modifier");
    }

    /**
     * 属性modifier的Setter方法.属性名：最后修改人 创建日期:
     * 
     * @param newModifier
     *            java.lang.String
     */
    public void setModifier(java.lang.String newModifier) {
        this.setAttributeValue("modifier", newModifier);
    }

    /**
     * 属性modifiedtime的Getter方法.属性名：最后修改时间 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getModifiedtime() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("modifiedtime");
    }

    /**
     * 属性modifiedtime的Setter方法.属性名：最后修改时间 创建日期:
     * 
     * @param newModifiedtime
     *            nc.vo.pub.lang.UFDateTime
     */
    public void setModifiedtime(nc.vo.pub.lang.UFDateTime newModifiedtime) {
        this.setAttributeValue("modifiedtime", newModifiedtime);
    }

    /**
     * 属性vbnote的Getter方法.属性名：备注 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVbnote() {
        return (java.lang.String) this.getAttributeValue("vbnote");
    }

    /**
     * 属性vbnote的Setter方法.属性名：备注 创建日期:
     * 
     * @param newVbnote
     *            java.lang.String
     */
    public void setVbnote(java.lang.String newVbnote) {
        this.setAttributeValue("vbnote", newVbnote);
    }

    /**
     * 属性vdef1的Getter方法.属性名：自定义项1 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef1() {
        return (java.lang.String) this.getAttributeValue("vdef1");
    }

    /**
     * 属性vdef1的Setter方法.属性名：自定义项1 创建日期:
     * 
     * @param newVdef1
     *            java.lang.String
     */
    public void setVdef1(java.lang.String newVdef1) {
        this.setAttributeValue("vdef1", newVdef1);
    }

    /**
     * 属性vdef2的Getter方法.属性名：自定义项2 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef2() {
        return (java.lang.String) this.getAttributeValue("vdef2");
    }

    /**
     * 属性vdef2的Setter方法.属性名：自定义项2 创建日期:
     * 
     * @param newVdef2
     *            java.lang.String
     */
    public void setVdef2(java.lang.String newVdef2) {
        this.setAttributeValue("vdef2", newVdef2);
    }

    /**
     * 属性vdef3的Getter方法.属性名：自定义项3 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef3() {
        return (java.lang.String) this.getAttributeValue("vdef3");
    }

    /**
     * 属性vdef3的Setter方法.属性名：自定义项3 创建日期:
     * 
     * @param newVdef3
     *            java.lang.String
     */
    public void setVdef3(java.lang.String newVdef3) {
        this.setAttributeValue("vdef3", newVdef3);
    }

    /**
     * 属性vdef4的Getter方法.属性名：自定义项4 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef4() {
        return (java.lang.String) this.getAttributeValue("vdef4");
    }

    /**
     * 属性vdef4的Setter方法.属性名：自定义项4 创建日期:
     * 
     * @param newVdef4
     *            java.lang.String
     */
    public void setVdef4(java.lang.String newVdef4) {
        this.setAttributeValue("vdef4", newVdef4);
    }

    /**
     * 属性vdef5的Getter方法.属性名：自定义项5 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef5() {
        return (java.lang.String) this.getAttributeValue("vdef5");
    }

    /**
     * 属性vdef5的Setter方法.属性名：自定义项5 创建日期:
     * 
     * @param newVdef5
     *            java.lang.String
     */
    public void setVdef5(java.lang.String newVdef5) {
        this.setAttributeValue("vdef5", newVdef5);
    }

    /**
     * 属性vdef6的Getter方法.属性名：自定义项6 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef6() {
        return (java.lang.String) this.getAttributeValue("vdef6");
    }

    /**
     * 属性vdef6的Setter方法.属性名：自定义项6 创建日期:
     * 
     * @param newVdef6
     *            java.lang.String
     */
    public void setVdef6(java.lang.String newVdef6) {
        this.setAttributeValue("vdef6", newVdef6);
    }

    /**
     * 属性vdef7的Getter方法.属性名：自定义项7 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef7() {
        return (java.lang.String) this.getAttributeValue("vdef7");
    }

    /**
     * 属性vdef7的Setter方法.属性名：自定义项7 创建日期:
     * 
     * @param newVdef7
     *            java.lang.String
     */
    public void setVdef7(java.lang.String newVdef7) {
        this.setAttributeValue("vdef7", newVdef7);
    }

    /**
     * 属性vdef8的Getter方法.属性名：自定义项8 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef8() {
        return (java.lang.String) this.getAttributeValue("vdef8");
    }

    /**
     * 属性vdef8的Setter方法.属性名：自定义项8 创建日期:
     * 
     * @param newVdef8
     *            java.lang.String
     */
    public void setVdef8(java.lang.String newVdef8) {
        this.setAttributeValue("vdef8", newVdef8);
    }

    /**
     * 属性vdef9的Getter方法.属性名：自定义项9 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef9() {
        return (java.lang.String) this.getAttributeValue("vdef9");
    }

    /**
     * 属性vdef9的Setter方法.属性名：自定义项9 创建日期:
     * 
     * @param newVdef9
     *            java.lang.String
     */
    public void setVdef9(java.lang.String newVdef9) {
        this.setAttributeValue("vdef9", newVdef9);
    }

    /**
     * 属性vdef10的Getter方法.属性名：自定义项10 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef10() {
        return (java.lang.String) this.getAttributeValue("vdef10");
    }

    /**
     * 属性vdef10的Setter方法.属性名：自定义项10 创建日期:
     * 
     * @param newVdef10
     *            java.lang.String
     */
    public void setVdef10(java.lang.String newVdef10) {
        this.setAttributeValue("vdef10", newVdef10);
    }

    /**
     * 属性vdef11的Getter方法.属性名：自定义项11 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef11() {
        return (java.lang.String) this.getAttributeValue("vdef11");
    }

    /**
     * 属性vdef11的Setter方法.属性名：自定义项11 创建日期:
     * 
     * @param newVdef11
     *            java.lang.String
     */
    public void setVdef11(java.lang.String newVdef11) {
        this.setAttributeValue("vdef11", newVdef11);
    }

    /**
     * 属性vdef12的Getter方法.属性名：自定义项12 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef12() {
        return (java.lang.String) this.getAttributeValue("vdef12");
    }

    /**
     * 属性vdef12的Setter方法.属性名：自定义项12 创建日期:
     * 
     * @param newVdef12
     *            java.lang.String
     */
    public void setVdef12(java.lang.String newVdef12) {
        this.setAttributeValue("vdef12", newVdef12);
    }

    /**
     * 属性vdef13的Getter方法.属性名：自定义项13 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef13() {
        return (java.lang.String) this.getAttributeValue("vdef13");
    }

    /**
     * 属性vdef13的Setter方法.属性名：自定义项13 创建日期:
     * 
     * @param newVdef13
     *            java.lang.String
     */
    public void setVdef13(java.lang.String newVdef13) {
        this.setAttributeValue("vdef13", newVdef13);
    }

    /**
     * 属性vdef14的Getter方法.属性名：自定义项14 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef14() {
        return (java.lang.String) this.getAttributeValue("vdef14");
    }

    /**
     * 属性vdef14的Setter方法.属性名：自定义项14 创建日期:
     * 
     * @param newVdef14
     *            java.lang.String
     */
    public void setVdef14(java.lang.String newVdef14) {
        this.setAttributeValue("vdef14", newVdef14);
    }

    /**
     * 属性vdef15的Getter方法.属性名：自定义项15 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef15() {
        return (java.lang.String) this.getAttributeValue("vdef15");
    }

    /**
     * 属性vdef15的Setter方法.属性名：自定义项15 创建日期:
     * 
     * @param newVdef15
     *            java.lang.String
     */
    public void setVdef15(java.lang.String newVdef15) {
        this.setAttributeValue("vdef15", newVdef15);
    }

    /**
     * 属性vdef16的Getter方法.属性名：自定义项16 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef16() {
        return (java.lang.String) this.getAttributeValue("vdef16");
    }

    /**
     * 属性vdef16的Setter方法.属性名：自定义项16 创建日期:
     * 
     * @param newVdef16
     *            java.lang.String
     */
    public void setVdef16(java.lang.String newVdef16) {
        this.setAttributeValue("vdef16", newVdef16);
    }

    /**
     * 属性vdef17的Getter方法.属性名：自定义项17 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef17() {
        return (java.lang.String) this.getAttributeValue("vdef17");
    }

    /**
     * 属性vdef17的Setter方法.属性名：自定义项17 创建日期:
     * 
     * @param newVdef17
     *            java.lang.String
     */
    public void setVdef17(java.lang.String newVdef17) {
        this.setAttributeValue("vdef17", newVdef17);
    }

    /**
     * 属性vdef18的Getter方法.属性名：自定义项18 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef18() {
        return (java.lang.String) this.getAttributeValue("vdef18");
    }

    /**
     * 属性vdef18的Setter方法.属性名：自定义项18 创建日期:
     * 
     * @param newVdef18
     *            java.lang.String
     */
    public void setVdef18(java.lang.String newVdef18) {
        this.setAttributeValue("vdef18", newVdef18);
    }

    /**
     * 属性vdef19的Getter方法.属性名：自定义项19 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef19() {
        return (java.lang.String) this.getAttributeValue("vdef19");
    }

    /**
     * 属性vdef19的Setter方法.属性名：自定义项19 创建日期:
     * 
     * @param newVdef19
     *            java.lang.String
     */
    public void setVdef19(java.lang.String newVdef19) {
        this.setAttributeValue("vdef19", newVdef19);
    }

    /**
     * 属性vdef20的Getter方法.属性名：自定义项20 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVdef20() {
        return (java.lang.String) this.getAttributeValue("vdef20");
    }

    /**
     * 属性vdef20的Setter方法.属性名：自定义项20 创建日期:
     * 
     * @param newVdef20
     *            java.lang.String
     */
    public void setVdef20(java.lang.String newVdef20) {
        this.setAttributeValue("vdef20", newVdef20);
    }

    /**
     * 属性dr的Getter方法.属性名：dr 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getDr() {
        return (java.lang.Integer) this.getAttributeValue("dr");
    }

    /**
     * 属性dr的Setter方法.属性名：dr 创建日期:
     * 
     * @param newDr
     *            java.lang.Integer
     */
    public void setDr(java.lang.Integer newDr) {
        this.setAttributeValue("dr", newDr);
    }

    /**
     * 属性ts的Getter方法.属性名：ts 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getTs() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("ts");
    }

    /**
     * 属性ts的Setter方法.属性名：ts 创建日期:
     * 
     * @param newTs
     *            nc.vo.pub.lang.UFDateTime
     */
    public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
        this.setAttributeValue("ts", newTs);
    }

    /**
     * <p>
     * 取得父VO主键字段.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getParentPKFieldName() {
        return null;
    }

    /**
     * <p>
     * 取得表主键.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getPKFieldName() {
        return "cteamid";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getTableName() {
        return "bd_team";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public static java.lang.String getDefaultTableName() {
        return "bd_team";
    }

    /**
     * 按照默认方式创建构造子.
     * 创建日期:
     */
    public TeamHeadVO() {
        super();
    }

    @Override
    public IVOMeta getMetaData() {
        return VOMetaFactory.getInstance().getVOMeta("mmbd.bd_team");
    }
}
