 ALTER TABLE om_deptadj
ADD shortname2 VARCHAR2(50);
 ALTER TABLE om_deptadj
ADD shortname3 VARCHAR2(50);
 ALTER TABLE om_deptadj
ADD shortname4 VARCHAR2(50);
 ALTER TABLE om_deptadj
ADD shortname5 VARCHAR2(50);
 ALTER TABLE om_deptadj
ADD shortname6 VARCHAR2(50);

 ALTER TABLE om_deptadj
ADD name2 VARCHAR2(50);
 ALTER TABLE om_deptadj
ADD name3 VARCHAR2(50);
 ALTER TABLE om_deptadj
ADD name4 VARCHAR2(50);
 ALTER TABLE om_deptadj
ADD name5 VARCHAR2(50);
 ALTER TABLE om_deptadj
ADD name6 VARCHAR2(50);