/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ta.overtime;

import nc.vo.ta.annotation.IDColumn;
import nc.vo.ta.timebill.annotation.BeginTimeFieldName;
import nc.vo.ta.timebill.annotation.BillBeginDateFieldName;
import nc.vo.ta.timebill.annotation.BillEndDateFieldName;
import nc.vo.ta.timebill.annotation.EndTimeFieldName;
import nc.vo.ta.timebill.annotation.PkJobOrgFieldName;
import nc.vo.ta.timebill.annotation.PkPsndocFieldName;
import nc.vo.ta.timebill.annotation.PkPsnjobFieldName;

/**
 * <b> ??????????????????? </b>
 * <p>
 *     ??????????????????
 * </p>
 * ????????:${vmObject.createdDate}
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
@IDColumn(idColumn="pk_overtimereg")
@BeginTimeFieldName(fieldName="overtimebegintime")
@EndTimeFieldName(fieldName="overtimeendtime")
@PkPsndocFieldName(fieldName="pk_psndoc")
@PkPsnjobFieldName(fieldName="pk_psnjob")
@PkJobOrgFieldName(fieldName="pk_joborg")
@BillBeginDateFieldName(fieldName="overtimebegindate")
@BillEndDateFieldName(fieldName="overtimeenddate")
public class OvertimeRegVO extends OvertimeCommonVO {
	private java.lang.String pk_overtimereg;
	private nc.vo.pub.lang.UFBoolean istorest;
	private nc.vo.pub.lang.UFDouble toresthour;
	private java.lang.String torestyear;
	private java.lang.String torestmonth;
	private nc.vo.pub.lang.UFBoolean ischeck;
	private nc.vo.pub.lang.UFDouble diffhour;
	private java.lang.Integer billsource;
	private nc.vo.pub.lang.UFDateTime begintimebeforecheck;
	private nc.vo.pub.lang.UFDateTime endtimebeforecheck;
	private java.lang.String pk_billsourceh;
	private java.lang.String pk_billsourceb;
	private java.lang.String pk_overtimegen;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime ts;
	private nc.vo.pub.lang.UFDateTime approve_time;
	private java.lang.String projectcode;
	private java.lang.String waperiod;
	public java.lang.String getWaperiod() {
		return waperiod;
	}
	public void setWaperiod(java.lang.String waperiod) {
		this.waperiod = waperiod;
	}
	public java.lang.String getProjectcode() {
		return projectcode;
	}
	public void setProjectcode(java.lang.String projectcode) {
		this.projectcode = projectcode;
	}
	public nc.vo.pub.lang.UFDateTime getApprove_time() {
		return approve_time;
	}
	public void setApprove_time(nc.vo.pub.lang.UFDateTime approve_time) {
		this.approve_time = approve_time;
	}
	public static final String PK_OVERTIMEREG = "pk_overtimereg";
	public static final String ISTOREST = "istorest";
	public static final String TORESTHOUR = "toresthour";
	public static final String TORESTYEAR = "torestyear";
	public static final String TORESTMONTH = "torestmonth";
	public static final String ISCHECK = "ischeck";
	public static final String DIFFHOUR = "diffhour";
	public static final String BILLSOURCE = "billsource";
	public static final String BEGINTIMEBEFORECHECK = "begintimebeforecheck";
	public static final String ENDTIMEBEFORECHECK = "endtimebeforecheck";
	public static final String PK_BILLSOURCEH = "pk_billsourceh";
	public static final String PK_BILLSOURCEB = "pk_billsourceb";
	public static final String PK_OVERTIMEGEN = "pk_overtimegen";
	public static final String CREATIONTIME = "creationtime";
	public static final String CREATOR = "creator";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String MODIFIER = "modifier";
	public static final String APPROVE_TIME = "approve_time";
	
			
	/**
	 * ????pk_overtimereg??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getPk_overtimereg () {
		return pk_overtimereg;
	}   
	/**
	 * ????pk_overtimereg??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newPk_overtimereg java.lang.String
	 */
	public void setPk_overtimereg (java.lang.String newPk_overtimereg ) {
	 	this.pk_overtimereg = newPk_overtimereg;
	} 	  
	/**
	 * ????istorest??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIstorest () {
		return istorest;
	}   
	/**
	 * ????istorest??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newIstorest nc.vo.pub.lang.UFBoolean
	 */
	public void setIstorest (nc.vo.pub.lang.UFBoolean newIstorest ) {
	 	this.istorest = newIstorest;
	} 	  
	/**
	 * ????toresthour??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getToresthour () {
		return toresthour;
	}   
	/**
	 * ????toresthour??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newToresthour nc.vo.pub.lang.UFDouble
	 */
	public void setToresthour (nc.vo.pub.lang.UFDouble newToresthour ) {
	 	this.toresthour = newToresthour;
	} 	  
	/**
	 * ????torestyear??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getTorestyear () {
		return torestyear;
	}   
	/**
	 * ????torestyear??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newTorestyear java.lang.String
	 */
	public void setTorestyear (java.lang.String newTorestyear ) {
	 	this.torestyear = newTorestyear;
	} 	  
	/**
	 * ????torestmonth??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getTorestmonth () {
		return torestmonth;
	}   
	/**
	 * ????torestmonth??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newTorestmonth java.lang.String
	 */
	public void setTorestmonth (java.lang.String newTorestmonth ) {
	 	this.torestmonth = newTorestmonth;
	} 	  
	/**
	 * ????ischeck??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIscheck () {
		return ischeck;
	}   
	/**
	 * ????ischeck??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newIscheck nc.vo.pub.lang.UFBoolean
	 */
	public void setIscheck (nc.vo.pub.lang.UFBoolean newIscheck ) {
	 	this.ischeck = newIscheck;
	} 	  
	/**
	 * ????billsource??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getBillsource () {
		return billsource;
	}   
	/**
	 * ????billsource??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newBillsource java.lang.Integer
	 */
	public void setBillsource (java.lang.Integer newBillsource ) {
	 	this.billsource = newBillsource;
	} 	  
	public nc.vo.pub.lang.UFDouble getDiffhour() {
		return diffhour;
	}
	public void setDiffhour(nc.vo.pub.lang.UFDouble diffhour) {
		this.diffhour = diffhour;
	}
	/**
	 * ????pk_billsourceh??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getPk_billsourceh () {
		return pk_billsourceh;
	}   
	/**
	 * ????pk_billsourceh??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newPk_billsourceh java.lang.String
	 */
	public void setPk_billsourceh (java.lang.String newPk_billsourceh ) {
	 	this.pk_billsourceh = newPk_billsourceh;
	} 	  
	public nc.vo.pub.lang.UFDateTime getBegintimebeforecheck() {
		return begintimebeforecheck;
	}
	public void setBegintimebeforecheck(
			nc.vo.pub.lang.UFDateTime begintimebeforecheck) {
		this.begintimebeforecheck = begintimebeforecheck;
	}
	public nc.vo.pub.lang.UFDateTime getEndtimebeforecheck() {
		return endtimebeforecheck;
	}
	public void setEndtimebeforecheck(nc.vo.pub.lang.UFDateTime endtimebeforecheck) {
		this.endtimebeforecheck = endtimebeforecheck;
	}
	/**
	 * ????pk_billsourceb??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getPk_billsourceb () {
		return pk_billsourceb;
	}   
	/**
	 * ????pk_billsourceb??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newPk_billsourceb java.lang.String
	 */
	public void setPk_billsourceb (java.lang.String newPk_billsourceb ) {
	 	this.pk_billsourceb = newPk_billsourceb;
	} 	  
	/**
	 * ????pk_overtimegen??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getPk_overtimegen () {
		return pk_overtimegen;
	}   
	/**
	 * ????pk_overtimegen??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newPk_overtimegen java.lang.String
	 */
	public void setPk_overtimegen (java.lang.String newPk_overtimegen ) {
	 	this.pk_overtimegen = newPk_overtimegen;
	} 	  
	/**
	 * ????creationtime??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * ????creationtime??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * ????creator??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * ????creator??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * ????modifiedtime??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * ????modifiedtime??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * ????modifier??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * ????modifier??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * ????ts??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * ????ts??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>????VO???????.
	  * <p>
	  * ????????:${vmObject.createdDate}
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>????????.
	  * <p>
	  * ????????:${vmObject.createdDate}
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_overtimereg";
	}
    
	/**
	 * <p>?????????.
	 * <p>
	 * ????????:${vmObject.createdDate}
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "tbm_overtimereg";
	}    
	
	/**
	 * <p>?????????.
	 * <p>
	 * ????????:${vmObject.createdDate}
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "tbm_overtimereg";
	}    
    
    /**
	  * ???????????????????.
	  *
	  * ????????:${vmObject.createdDate}
	  */
     public OvertimeRegVO() {
		super();	
	}
	@Override
	public boolean isAppBill() {
		return false;
	}
	@Override
	public void setAppBill(boolean isAppBill) {
		// TODO Auto-generated method stub
		
	}    
} 


