
delete pub_billtemplet_t where ( pk_billtemplet in ('0001ZZ1000000003IBUC') and (dr=0 or dr is null) );


delete pub_billtemplet_b where ( pk_billtemplet in ('0001ZZ1000000003IBUC') and (dr=0 or dr is null) );


delete pub_billtemplet where ( pk_billtemplet='0001ZZ1000000003IBUC' and (bill_templetname='SYSTEM') and (dr=0 or dr is null) );



insert into pub_billtemplet(bill_templetcaption,bill_templetname,devorg,dividerproportion,dr,funccode,layer,metadataclass,model_type,modulecode,nodecode,options,pk_billtemplet,pk_billtypecode,pk_corp,pk_org,resid,shareflag,ts,validateformula) values( '参数设定','SYSTEM',null,null,0,null,0,'twhr.basedoc',null,'TWHR','68J61006',null,'0001ZZ1000000003IBUC','68J61006','@@@@',null,null,null,'2018-07-27 19:51:33',null);



insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def19',0,'N',1,'N','N',19,null,0,'def19','twhr.basedoc.def19',null,'N',0,null,'0001ZZ1000000003IBUC','0001ZZ1000000003IBUV','@@@@',1,null,null,null,'N',0,1,'basedoc','参数设定',0,'2018-07-27 19:51:33','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def20',0,'N',1,'N','N',20,null,0,'def20','twhr.basedoc.def20',null,'N',0,null,'0001ZZ1000000003IBUC','0001ZZ1000000003IBUW','@@@@',1,null,null,null,'N',0,2,'basedoc','参数设定',0,'2018-07-27 19:51:33','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'id',0,'N',1,'N','N',28,null,0,'id','twhr.basedoc.id',null,'N',0,null,'0001ZZ1000000003IBUC','0001ZZ1000000003IBV4','@@@@',1,null,null,null,'N',0,3,'basedoc','参数设定',0,'2018-07-27 19:51:33','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'doccategory',0,'N',1,'N','Y',29,null,0,'doccategory','twhr.basedoc.doccategory',null,'N',0,null,'0001ZZ1000000003IBUC','0001ZZ1000000003IBV5','@@@@',1,null,null,null,'N',1,4,'basedoc','参数设定',0,'2018-07-27 19:51:33','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'code',0,'N',1,'N','Y',30,null,0,'code','twhr.basedoc.code',null,'N',0,null,'0001ZZ1000000003IBUC','0001ZZ1000000003IBV6','@@@@',1,null,null,null,'N',1,5,'basedoc','参数设定',0,'2018-07-27 19:51:33','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'name',0,'N',1,'N','Y',31,null,0,'name','twhr.basedoc.name',null,'N',0,null,'0001ZZ1000000003IBUC','0001ZZ1000000003IBV7','@@@@',1,null,null,null,'N',1,6,'basedoc','参数设定',0,'2018-07-27 19:51:33','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'doctype',0,'N',1,'N','Y',32,null,0,'doctype','twhr.basedoc.doctype',null,'N',0,null,'0001ZZ1000000003IBUC','0001ZZ1000000003IBV8','@@@@',1,null,null,null,'N',1,7,'basedoc','参数设定',0,'2018-07-27 19:51:33','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'numbervalue',0,'N',1,'N','Y',33,null,0,'numbervalue','twhr.basedoc.numbervalue',null,'N',0,null,'0001ZZ1000000003IBUC','0001ZZ1000000003IBV9','@@@@',1,null,null,null,'N',1,8,'basedoc','参数设定',0,'2018-07-27 19:51:33','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'waitemvalue',0,'N',1,'N','Y',34,null,0,'waitemvalue','twhr.basedoc.waitemvalue',null,'N',0,null,'0001ZZ1000000003IBUC','0001ZZ1000000003IBVA','@@@@',1,null,null,null,'N',1,9,'basedoc','参数设定',0,'2018-07-27 19:51:33','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',35,null,0,'ts','twhr.basedoc.ts',null,'N',0,null,'0001ZZ1000000003IBUC','0001ZZ1000000003IBVB','@@@@',1,null,null,null,'N',0,10,'basedoc','参数设定',0,'2018-07-27 19:51:33','N',null,null,null,1,1,'N',1,null,100);



insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'twhr.basedoc','basedoc',null,'0001ZZ1000000003IBUC','1001ZZ1000000000K7ZC',null,1,null,null,'basedoc',0,'参数设定','2018-07-27 19:51:40',null,null,null);

