INSERT  INTO dbo.wa_expformat_head
        ( pk_formathead ,
          code ,
          name ,
          linecount ,
          dr
        )
VALUES  ( '6886TW100000IITX2015' , -- pk_formathead - char(20)
          N'IITX_FMT_TW_2015' , -- code - nvarchar(50)
          N'綜合所得稅申報格式2015' , -- name - nvarchar(50)
          3 , -- linecount - int
          0  -- dr - smallint
        );

INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0001',	1,	1,	N'CITY_NO',	N'縣市別',	0,	1,	1,	N' ',	N'',	N'',	N'',	'N',	2,	N'%LEFT%org_hrorg AS reportOrg',	N'hrorg.glbdef27=reportOrg.pk_hrorg',	N'LEFT(def1.code, 1)',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0002',	1,	2,	N'DEPT_NO',	N'機關別',	0,	2,	1,	N' ',	N'',	N'',	N'',	'N',	2,	N'%LEFT%bd_defdoc AS def2',	N'reportOrg.glbdef13=def2.pk_defdoc',	N'RIGHT(def2.code, 2)',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0003',	1,	3,	N'FIX_BLANK',	N'固定空白',	0,	8,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0004',	1,	4,	N'VAT_CODE',	N'統一編號',	0,	8,	0,	N'',	N'',	N'',	N'',	'N',	2,	N'%INNER%org_orgs AS org',	N'org.pk_org = hrorg.pk_hrorg',	N'reportOrg.glbdef7',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0005',	1,	5,	N'DATA_SPLT',	N'資料區隔',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'1',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0006',	1,	6,	N'CMP_NAME',	N'申報單位名稱',	0,	36,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'%LEFT%bd_defdoc AS def1',	N'reportOrg.glbdef12=def1.pk_defdoc',	N'reportOrg.glbdef26',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0007',	1,	7,	N'CMP_ADDR',	N'申報單位地點',	0,	52,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'%LEFT%bd_address AS addr',	N'org.address=addr.pk_address',	N'addr.detailinfo',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0008',	1,	8,	N'LEGAL_PERSON',	N'扣繳義務人名稱',	0,	40,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'',	N'',	N'reportOrg.glbdef8',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0009',	1,	9,	N'LINK_MAN',	N'聯絡人姓名',	0,	40,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'org_hrorg AS hrorg',	N'',	N'reportOrg.glbdef14',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0010',	1,	10,	N'TELE_NO',	N'聯絡人電話',	0,	15,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'',	N'',	N'reportOrg.glbdef15',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0011',	1,	11,	N'EMAIL_ADDR',	N'申報單據電子郵箱',	0,	30,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'',	N'',	N'reportOrg.glbdef16',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0012',	1,	12,	N'TAX_NO',	N'扣繳單位稅籍編號',	0,	9,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'',	N'',	N'reportOrg.glbdef9',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0013',	1,	13,	N'IS_HQ',	N'總分支機構註記',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'',	N'',	N'reportOrg.glbdef17',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0014',	1,	14,	N'REPT_TIMES',	N'申報次數',	0,	2,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0015',	1,	15,	N'REPT_RESN',	N'重複申報原因',	0,	2,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0016',	1,	16,	N'IS_STOCK',	N'上市公司註記',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'',	N'',	N'reportOrg.glbdef18',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0017',	1,	17,	N'IS_BANK',	N'金融機構註記',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'',	N'',	N'case when isnull(reportOrg.glbdef19,''N'')=''N'' then '' '' else ''1'' end',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0018',	1,	18,	N'IS_AGENT',	N'事務所代理註記',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'',	N'org.pk_org IN (%PKORGS%)',	N'reportOrg.glbdef20',	0)	;
																																					
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0019',	2,	1,	N'CITY_NO',	N'縣市別',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%VALUE:LINE:1:CITY_NO%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0020',	2,	2,	N'DEPT_NO',	N'機關別',	0,	2,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%VALUE:LINE:1:DEPT_NO%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0021',	2,	3,	N'SERL_PRE',	N'流水號前兩碼',	0,	2,	0,	N'',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'01',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0022',	2,	4,	N'SERL_NO',	N'流水號',	1,	6,	1,	N'0',	N'',	N'',	N'',	'N',	2,	N'wa_data AS wa',	N'',	N'%ROWNO%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0023',	2,	5,	N'VAT_CODE',	N'統一編號',	0,	8,	0,	N'',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%VALUE:LINE:1:VAT_CODE%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0024',	2,	6,	N'MEMO_MARK',	N'註記',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0025',	2,	7,	N'TAX_FRMT',	N'所得稅格式代號',	0,	2,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'50',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0026',	2,	8,	N'PSN_ID',	N'納稅人統一編號',	0,	10,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'%INNER%bd_psndoc AS psn',	N'wa.pk_psndoc = psn.pk_psndoc',	N'psn.id',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0027',	2,	9,	N'ID_TYPE',	N'證號別',	0,	1,	2,	N'  ',	N'',	N'',	N'',	'N',	2,	N'',	N'',	N'CASE WHEN ( psn.country = ''0001Z010000000079UJK'' AND psn.glbdef9 != ''Y'') THEN ( CASE WHEN psn.glbdef10 = ''Y'' THEN 0 ELSE 9 END ) ELSE ( CASE WHEN psn.country != ''0001Z010000000079UJK'' AND psn.glbdef9 = ''Y'' AND psn.glbdef10 = ''Y'' THEN 3 ELSE ( CASE WHEN psn.country = ''0001Z010000000079UJJ'' AND psn.glbdef9 = ''Y'' AND psn.glbdef10 != ''Y'' THEN 5 ELSE ( CASE WHEN psn.country NOT IN (''0001Z010000000079UJK'',''0001Z010000000079UJJ'' ) AND psn.glbdef9 = ''Y'' AND psn.glbdef10 != ''Y'' THEN 7 ELSE '' '' END)END)END)END',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0028',	2,	10,	N'TOTAL_PAY',	N'給付總額',	1,	10,	1,	N'0',	N'',	N'',	N'',	'Y',	2,	N'%INNER%wa_periodstate AS stat',	N'wa.pk_wa_class = stat.pk_wa_class',	N'cast(wa.f_4 as int)',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0029',	2,	11,	N'TOTAL_DEC',	N'扣繳總額',	1,	10,	1,	N'0',	N'',	N'',	N'',	'Y',	2,	N'',	N' stat.isapproved = ''Y''  and stat.enableflag = ''Y'' and stat.payoffflag = ''Y''',	N'cast(wa.f_5+wa.f_158 as int)',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0030',	2,	12,	N'NET_PAY',	N'給付凈額',	1,	10,	1,	N'0',	N'',	N'',	N'',	'Y',	2,	N'%INNER%wa_period AS pd',	N'stat.pk_wa_period = pd.pk_wa_period',	N'cast(wa.f_4-wa.f_5-wa.f_158 as int)',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0031',	2,	13,	N'SHARE_COL1',	N'共用欄位1',	0,	12,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'',	N'wa.cyear = pd.caccyear and wa.cperiod = pd.caccperiod',	N'psn.code',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0032',	2,	14,	N'SOFT_MARK',	N'軟體註記',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'B',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0033',	2,	15,	N'ERROR_MARK',	N'錯誤註記',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N' ',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0034',	2,	16,	N'INC_YEAR',	N'所得年度',	1,	3,	1,	N'0',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%REFTWYEAR%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0035',	2,	17,	N'PSN_NAME',	N'納稅人姓名',	0,	40,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'',	N'(CASE WHEN (SELECT value FROM pub_sysinit WHERE initcode = ''TWHR07'' and pk_org = wa.pk_org)=''發放日期'' THEN ((LEFT(stat.cpaydate,4)+RIGHT(LEFT(stat.cpaydate,7), 2))) ELSE ((wa.cyear+wa.cperiod)) END) BETWEEN ''%STARTPERIOD%'' AND ''%ENDPERIOD%''',	N'psn.name',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0036',	2,	18,	N'PSN_ADDR',	N'納稅人中文地址',	0,	60,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'',	N'',	N'psn.censusaddr',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0037',	2,	19,	N'INC_PERIOD_MIN',	N'所得所屬期間（起）',	0,	5,	2,	N' ',	N'',	N'',	N'',	'N',	1,	N'',	N'',	N'CASE WHEN (SELECT value FROM pub_sysinit WHERE initcode = ''TWHR07'' and pk_org = wa.pk_org)=''發放日期'' THEN MIN(CAST(CAST(LEFT(stat.cpaydate,4) AS INT)-1911 AS NVARCHAR(3))+RIGHT(LEFT(stat.cpaydate,7), 2)) ELSE MIN(CAST(CAST(wa.cyear AS INT)-1911 AS NVARCHAR(3))+wa.cperiod) END',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0038',	2,	20,	N'INC_PERIOD_MAX',	N'所得所屬期間（迄）',	0,	5,	2,	N' ',	N'',	N'',	N'',	'N',	1,	N'',	N'',	N'CASE WHEN (SELECT value FROM pub_sysinit WHERE initcode = ''TWHR07'' and pk_org = wa.pk_org)=''發放日期'' THEN MAX(CAST(CAST(LEFT(stat.cpaydate,4) AS INT)-1911 AS NVARCHAR(3))+RIGHT(LEFT(stat.cpaydate,7), 2)) ELSE MAX(CAST(CAST(wa.cyear AS INT)-1911 AS NVARCHAR(3))+wa.cperiod) END',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0039',	2,	21,	N'SHARE_COL2_1',	N'共用欄位2-1',	1,	10,	1,	N'0',	N'',	N'',	N'',	'Y',	2,	N'',	N'wa.pk_wa_class IN (%REFCLASSES%)  OR wa.pk_wa_class IN (SELECT pk_childclass FROM dbo.wa_inludeclass WHERE pk_parentclass IN ( %REFCLASSES% ) )', N'cast(f_34 as int)+cast(f_44 as int)',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0040',	2,	22,	N'SHARE_COL2_2',	N'共用欄位2-2',	0,	37,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0041',	2,	23,	N'TAXDEC_NOTE',	N'扣抵稅額註記',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N' ',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0042',	2,	24,	N'VOUCHER_TYPE',	N'憑單填發方式',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%REF:VOUCHERTYPE%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0043',	2,	25,	N'IS_183',	N'是否滿183天',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0044',	2,	26,	N'NATION_CODE',	N'國家代碼',	0,	2,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0045',	2,	27,	N'PROC_CODE',	N'租稅協定代碼',	0,	2,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0046',	2,	28,	N'BLACK',	N'空白',	0,	2,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0047',	2,	29,	N'MONTHDATE',	N'月日',	0,	4,	0,	N'',	N'',	N'',	N'',	'N',	1,	N'',	N'',	N'FORMAT(GETDATE(), ''MMdd'')',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0048',	2,	30,	N'ADDEDGROUP',	N'ADDEDGROUP',	0,	0,	0,	N'',	N'',	N'',	N'',	'N',	2,	N'',	N'wa.f_4 != 0',	N'wa.pk_org',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0049',	2,	31,	N'ADDEDGROUP1',	N'ADDEDGROUP1',	0,	0,	0,	N'',	N'',	N'',	N'',	'N',	2,	N'',	N'',	N'psn.glbdef9',	0)	;
																																					
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0050',	3,	1,	N'CITY_NO',	N'縣市別',	0,	1,	1,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%VALUE:LINE:1:CITY_NO%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0051',	3,	2,	N'DEPT_NO',	N'機關別',	0,	2,	1,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%VALUE:LINE:1:DEPT_NO%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0052',	3,	3,	N'SERL_PRE',	N'流水號第一碼',	0,	8,	0,	N'',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'ZZ000001',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0053',	3,	4,	N'VAT_CODE',	N'申報單位統一編號',	0,	8,	0,	N'',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%VALUE:LINE:1:VAT_CODE%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0054',	3,	5,	N'DATA_SPLT',	N'資料區分',	0,	1,	0,	N'',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'9',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0055',	3,	6,	N'DMSTC_OVS',	N'國內國外',	0,	1,	0,	N'',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'1',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0056',	3,	7,	N'IS_INDV',	N'個人非個人',	0,	1,	0,	N'',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'1',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0057',	3,	8,	N'INCOME_TYPE',	N'所得類別',	0,	1,	0,	N'',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'3',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0058',	3,	9,	N'TYPE_CLASS',	N'類別區分',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0059',	3,	10,	N'INCOME_COUNT',	N'該類所得資料筆數',	1,	9,	1,	N'0',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%COUNT:LINE:2:*%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0060',	3,	11,	N'TOTAL_PAY',	N'扣繳憑單給付總額',	1,	14,	1,	N'0',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%SUM:LINE:2:TOTAL_PAY%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0061',	3,	12,	N'TOTAL_DEC',	N'扣繳稅額',	1,	14,	1,	N'0',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%SUM:LINE:2:TOTAL_DEC%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0062',	3,	13,	N'TAX_NO',	N'扣繳單位稅籍編號',	0,	9,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%VALUE:LINE:1:TAX_NO%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0063',	3,	14,	N'PRINT_BLANK',	N'列印位置或空白',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'%INNER%org_hrorg AS hrorg',	N'org.pk_org = hrorg.pk_org',	N'''''',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0064',	3,	15,	N'HOUSE_TAXCODE',	N'申報單位房屋稅籍編號',	0,	12,	2,	N' ',	N'',	N'',	N'',	'N',	2,	N'%LEFT%org_hrorg AS reportOrg',	N'hrorg.glbdef26=reportOrg.pk_hrorg',	N'hrorg.glbdef10',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0065',	3,	16,	N'ERROR_MARK',	N'錯誤註記',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0066',	3,	17,	N'DATA_YEAR',	N'資料年度',	0,	3,	0,	N'',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%REFTWYEAR%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0067',	3,	18,	N'DATA_DATE',	N'檔案製作日期',	0,	7,	0,	N'',	N'',	N'',	N'',	'N',	2,	N'org_orgs AS org',	N'',	N'%TWDATE%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0068',	3,	19,	N'START_SERL',	N'起始流水號',	0,	8,	0,	N'',	N'',	N'',	N'',	'N',	1,	N'',	N'',	N'CONCAT(''%VALUE:LINE:2:SERL_PRE%'',FORMAT(%MIN:LINE:2:SERL_NO%, ''00000#''))',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0069',	3,	20,	N'END_SERL',	N'結束流水號',	0,	8,	0,	N'',	N'',	N'',	N'',	'N',	1,	N'',	N'',	N'CONCAT(''%VALUE:LINE:2:SERL_PRE%'',FORMAT(%MAX:LINE:2:SERL_NO%, ''00000#''))',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0070',	3,	21,	N'DEC_RATE',	N'稅額扣抵比率',	1,	4,	1,	N'0',	N'',	N'',	N'',	'N',	2,	N'',	N'hrorg.pk_hrorg IN (%PKORGS%)',	N'ROUND(%SUM:LINE:2:TOTAL_DEC%/%SUM:LINE:2:TOTAL_PAY%*100, 2)',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0071',	3,	22,	N'ALLOC_TIMES',	N'分配次數',	1,	2,	0,	N'',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'00',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0072',	3,	23,	N'EX_DATE',	N'除權（息）日期',	0,	7,	0,	N'',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'0000000',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0073',	3,	24,	N'VOLU_PAY',	N'自願提（撥）繳之金額',	1,	14,	1,	N'0',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'%SUM:LINE:2:SHARE_COL2%',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0074',	3,	25,	N'DIVDENT_AMOUNT',	N'股利或盈餘抵繳稅額',	1,	14,	1,	N'0',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0075',	3,	26,	N'BLANK',	N'空白',	0,	98,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
INSERT INTO dbo.wa_expformat_item (pk_formathead,	pk_formatitem,	linenumber,	posnumber,	itemcode,	itemname,	datatype,	byteLength,	fillmode,	fillstr,	prefix,	suffix,	splitter,	issum,	datasource,	datatable,	joinkey,	datacontext,	dr) VALUES('6886TW100000IITX2015',	'6886TW100000IITX0076',	3,	27,	N'MEDIA_CODE',	N'來源標識',	0,	1,	2,	N' ',	N'',	N'',	N'',	'N',	0,	N'',	N'',	N'',	0)	;
