/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.org;

import java.util.HashMap;

import nc.vo.org.orgmodel.OrgTypeVO;
import nc.vo.pub.BusinessException;
import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2008-02-26 16:44:24
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class DeptVO extends SuperVO {
	private java.lang.String pk_dept;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.String name2;
	private java.lang.String name3;
	private java.lang.String name4;
	private java.lang.String name5;
	private java.lang.String name6;
	private java.lang.String innercode;
	private java.lang.String pk_fatherorg;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.Integer depttype = 0;
	private java.lang.String deptlevel;
	private nc.vo.pub.lang.UFLiteralDate createdate;
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.String resposition;
	private java.lang.String shortname;
	private java.lang.String shortname2;
	private java.lang.String shortname3;
	private java.lang.String shortname4;
	private java.lang.String shortname5;
	private java.lang.String shortname6;
	private java.lang.String mnecode;
	private nc.vo.pub.lang.UFBoolean hrcanceled;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.Integer enablestate = 1;
	private java.lang.Integer displayorder;
	private java.lang.Integer dataoriginflag = 0;
	private java.lang.String pk_vid;
	private java.lang.String vname;
	private java.lang.String vno;
	private nc.vo.pub.lang.UFDate vstartdate;
	private nc.vo.pub.lang.UFDate venddate;
	private nc.vo.pub.lang.UFBoolean orgtype13;
	private nc.vo.pub.lang.UFBoolean orgtype17;
	private java.lang.String principal;
	private java.lang.String tel;
	private java.lang.String address;
	private java.lang.String memo;
	private java.lang.String def6;
	private java.lang.String def7;
	private java.lang.String def8;
	private java.lang.String def9;
	private java.lang.String def10;
	private java.lang.String def11;
	private java.lang.String def12;
	private java.lang.String def13;
	private java.lang.String def14;
	private java.lang.String def15;
	private java.lang.String def16;
	private java.lang.String def17;
	private java.lang.String def18;
	private java.lang.String def19;
	private java.lang.String def20;
	private nc.vo.pub.lang.UFLiteralDate deptcanceldate;
	private nc.vo.pub.lang.UFBoolean islastversion;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private java.lang.String vname2;
	private java.lang.String vname3;
	private java.lang.String vname4;
	private java.lang.String vname5;
	private java.lang.String vname6;
	private nc.vo.pub.lang.UFBoolean isretail;
	private java.lang.String chargeleader;
	private java.lang.Integer weekform;
	private java.lang.Integer overtimecontrol;
	public static final String PK_DEPT = "pk_dept";
	public static final String CODE = "code";
	public static final String NAME = "name";
	public static final String NAME2 = "name2";
	public static final String NAME3 = "name3";
	public static final String NAME4 = "name4";
	public static final String NAME5 = "name5";
	public static final String NAME6 = "name6";
	public static final String INNERCODE = "innercode";
	public static final String PK_FATHERORG = "pk_fatherorg";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String DEPTTYPE = "depttype";
	public static final String DEPTLEVEL = "deptlevel";
	public static final String CREATEDATE = "createdate";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String RESPOSITION = "resposition";
	public static final String SHORTNAME = "shortname";
	public static final String SHORTNAME2 = "shortname2";
	public static final String SHORTNAME3 = "shortname3";
	public static final String SHORTNAME4 = "shortname4";
	public static final String SHORTNAME5 = "shortname5";
	public static final String SHORTNAME6 = "shortname6";
	public static final String MNECODE = "mnecode";
	public static final String HRCANCELED = "hrcanceled";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String ENABLESTATE = "enablestate";
	public static final String DISPLAYORDER = "displayorder";
	public static final String DATAORIGINFLAG = "dataoriginflag";
	public static final String PK_VID = "pk_vid";
	public static final String VNAME = "vname";
	public static final String VNO = "vno";
	public static final String VSTARTDATE = "vstartdate";
	public static final String VENDDATE = "venddate";
	public static final String ORGTYPE13 = "orgtype13";
	public static final String ORGTYPE17 = "orgtype17";
	public static final String PRINCIPAL = "principal";
	public static final String TEL = "tel";
	public static final String ADDRESS = "address";
	public static final String MEMO = "memo";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
	public static final String DEF11 = "def11";
	public static final String DEF12 = "def12";
	public static final String DEF13 = "def13";
	public static final String DEF14 = "def14";
	public static final String DEF15 = "def15";
	public static final String DEF16 = "def16";
	public static final String DEF17 = "def17";
	public static final String DEF18 = "def18";
	public static final String DEF19 = "def19";
	public static final String DEF20 = "def20";
	public static final String DEPTCANCELDATE = "deptcanceldate";
	public static final String ISLASTVERSION = "islastversion";
	public static final String VNAME2 = "vname2";
	public static final String VNAME3 = "vname3";
	public static final String VNAME4 = "vname4";
	public static final String VNAME5 = "vname5";
	public static final String VNAME6 = "vname6";
	public static final String ISRETAIL = "isretail";
	public static final String CHARGELEADER="chargeleader";
	public static final String WEEKFORM="weekform";
	public static final String OVERTIMECONTROL="overtimecontrol";

	/**
	 * 属性pk_dept的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_dept() {
		return pk_dept;
	}

	/**
	 * 属性pk_dept的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newPk_dept
	 *            java.lang.String
	 */
	public void setPk_dept(java.lang.String newPk_dept) {
		this.pk_dept = newPk_dept;
	}

	/**
	 * 属性code的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCode() {
		return code;
	}

	/**
	 * 属性code的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newCode
	 *            java.lang.String
	 */
	public void setCode(java.lang.String newCode) {
		this.code = newCode;
	}

	/**
	 * 属性name的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getName() {
		return name;
	}

	/**
	 * 属性name的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newName
	 *            java.lang.String
	 */
	public void setName(java.lang.String newName) {
		this.name = newName;
	}

	/**
	 * 属性name的Getter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getName2() {
		return name2;
	}

	/**
	 * 属性name的Setter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @param newName2
	 *            java.lang.String
	 */
	public void setName2(java.lang.String newName2) {
		this.name2 = newName2;
	}

	/**
	 * 属性name的Getter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getName3() {
		return name3;
	}

	/**
	 * 属性name的Setter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @param newName3
	 *            java.lang.String
	 */
	public void setName3(java.lang.String newName3) {
		this.name3 = newName3;
	}

	/**
	 * 属性name的Getter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getName4() {
		return name4;
	}

	/**
	 * 属性name的Setter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @param newName4
	 *            java.lang.String
	 */
	public void setName4(java.lang.String newName4) {
		this.name4 = newName4;
	}

	/**
	 * 属性name的Getter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getName5() {
		return name5;
	}

	/**
	 * 属性name的Setter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @param newName5
	 *            java.lang.String
	 */
	public void setName5(java.lang.String newName5) {
		this.name5 = newName5;
	}

	/**
	 * 属性name的Getter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getName6() {
		return name6;
	}

	/**
	 * 属性name的Setter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @param newName6
	 *            java.lang.String
	 */
	public void setName6(java.lang.String newName6) {
		this.name6 = newName6;
	}

	/**
	 * 属性shortname的Getter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getShortname2() {
		return shortname2;
	}

	/**
	 * 属性shortname的Setter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @param newShortname2
	 *            java.lang.String
	 */
	public void setShortname2(java.lang.String newShortname2) {
		this.shortname2 = newShortname2;
	}

	/**
	 * 属性shortname的Getter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getShortname3() {
		return shortname3;
	}

	/**
	 * 属性shortname的Setter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @param newShortname3
	 *            java.lang.String
	 */
	public void setShortname3(java.lang.String newShortname3) {
		this.shortname3 = newShortname3;
	}

	/**
	 * 属性shortname的Getter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getShortname4() {
		return shortname4;
	}

	/**
	 * 属性shortname的Setter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @param newShortname4
	 *            java.lang.String
	 */
	public void setShortname4(java.lang.String newShortname4) {
		this.shortname4 = newShortname4;
	}

	/**
	 * 属性shortname的Getter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getShortname5() {
		return shortname5;
	}

	/**
	 * 属性shortname的Setter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @param newShortname5
	 *            java.lang.String
	 */
	public void setShortname5(java.lang.String newShortname5) {
		this.shortname5 = newShortname5;
	}

	/**
	 * 属性shortname的Getter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getShortname6() {
		return shortname6;
	}

	/**
	 * 属性shortname的Setter方法. 创建日期:$vmObject.createdDate
	 * 
	 * @param newShortname6
	 *            java.lang.String
	 */
	public void setShortname6(java.lang.String newShortname6) {
		this.shortname6 = newShortname6;
	}

	/**
	 * 属性innercode的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getInnercode() {
		return innercode;
	}

	/**
	 * 属性innercode的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newInnercode
	 *            java.lang.String
	 */
	public void setInnercode(java.lang.String newInnercode) {
		this.innercode = newInnercode;
	}

	/**
	 * 属性pk_fatherorg的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_fatherorg() {
		return pk_fatherorg;
	}

	/**
	 * 属性pk_fatherorg的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newPk_fatherorg
	 *            java.lang.String
	 */
	public void setPk_fatherorg(java.lang.String newPk_fatherorg) {
		this.pk_fatherorg = newPk_fatherorg;
	}

	/**
	 * 属性pk_group的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group() {
		return pk_group;
	}

	/**
	 * 属性pk_group的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newPk_group
	 *            java.lang.String
	 */
	public void setPk_group(java.lang.String newPk_group) {
		this.pk_group = newPk_group;
	}

	/**
	 * 属性pk_org的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org() {
		return pk_org;
	}

	/**
	 * 属性pk_org的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newPk_org
	 *            java.lang.String
	 */
	public void setPk_org(java.lang.String newPk_org) {
		this.pk_org = newPk_org;
	}

	/**
	 * 属性depttype的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDepttype() {
		return depttype;
	}

	/**
	 * 属性depttype的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDepttype
	 *            java.lang.Integer
	 */
	public void setDepttype(java.lang.Integer newDepttype) {
		this.depttype = newDepttype;
	}

	/**
	 * 属性deptlevel的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDeptlevel() {
		return deptlevel;
	}

	/**
	 * 属性deptlevel的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDeptlevel
	 *            java.lang.String
	 */
	public void setDeptlevel(java.lang.String newDeptlevel) {
		this.deptlevel = newDeptlevel;
	}

	/**
	 * 属性createdate的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return nc.vo.pub.lang.UFLiteralDate
	 */
	public nc.vo.pub.lang.UFLiteralDate getCreatedate() {
		return createdate;
	}

	/**
	 * 属性createdate的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newCreatedate
	 *            nc.vo.pub.lang.UFLiteralDate
	 */
	public void setCreatedate(nc.vo.pub.lang.UFLiteralDate newCreatedate) {
		this.createdate = newCreatedate;
	}

	/**
	 * 属性def1的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef1
	 *            java.lang.String
	 */
	public void setDef1(java.lang.String newDef1) {
		this.def1 = newDef1;
	}

	/**
	 * 属性def2的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef2
	 *            java.lang.String
	 */
	public void setDef2(java.lang.String newDef2) {
		this.def2 = newDef2;
	}

	/**
	 * 属性def3的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef3
	 *            java.lang.String
	 */
	public void setDef3(java.lang.String newDef3) {
		this.def3 = newDef3;
	}

	/**
	 * 属性def4的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef4
	 *            java.lang.String
	 */
	public void setDef4(java.lang.String newDef4) {
		this.def4 = newDef4;
	}

	/**
	 * 属性def5的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef5
	 *            java.lang.String
	 */
	public void setDef5(java.lang.String newDef5) {
		this.def5 = newDef5;
	}

	/**
	 * 属性resposition的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getResposition() {
		return resposition;
	}

	/**
	 * 属性resposition的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newResposition
	 *            java.lang.String
	 */
	public void setResposition(java.lang.String newResposition) {
		this.resposition = newResposition;
	}

	/**
	 * 属性shortname的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getShortname() {
		return shortname;
	}

	/**
	 * 属性shortname的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newShortname
	 *            java.lang.String
	 */
	public void setShortname(java.lang.String newShortname) {
		this.shortname = newShortname;
	}

	/**
	 * 属性mnecode的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getMnecode() {
		return mnecode;
	}

	/**
	 * 属性mnecode的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newMnecode
	 *            java.lang.String
	 */
	public void setMnecode(java.lang.String newMnecode) {
		this.mnecode = newMnecode;
	}

	/**
	 * 属性hrcanceled的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getHrcanceled() {
		return hrcanceled;
	}

	/**
	 * 属性hrcanceled的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newHrcanceled
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setHrcanceled(nc.vo.pub.lang.UFBoolean newHrcanceled) {
		this.hrcanceled = newHrcanceled;
	}

	/**
	 * 属性creator的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCreator() {
		return creator;
	}

	/**
	 * 属性creator的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newCreator
	 *            java.lang.String
	 */
	public void setCreator(java.lang.String newCreator) {
		this.creator = newCreator;
	}

	/**
	 * 属性creationtime的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime() {
		return creationtime;
	}

	/**
	 * 属性creationtime的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newCreationtime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime(nc.vo.pub.lang.UFDateTime newCreationtime) {
		this.creationtime = newCreationtime;
	}

	/**
	 * 属性modifier的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getModifier() {
		return modifier;
	}

	/**
	 * 属性modifier的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newModifier
	 *            java.lang.String
	 */
	public void setModifier(java.lang.String newModifier) {
		this.modifier = newModifier;
	}

	/**
	 * 属性modifiedtime的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime() {
		return modifiedtime;
	}

	/**
	 * 属性modifiedtime的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newModifiedtime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime(nc.vo.pub.lang.UFDateTime newModifiedtime) {
		this.modifiedtime = newModifiedtime;
	}

	/**
	 * 属性enablestate的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getEnablestate() {
		return enablestate;
	}

	/**
	 * 属性enablestate的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newEnablestate
	 *            java.lang.Integer
	 */
	public void setEnablestate(java.lang.Integer newEnablestate) {
		this.enablestate = newEnablestate;
	}

	/**
	 * 属性displayorder的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDisplayorder() {
		return displayorder;
	}

	/**
	 * 属性displayorder的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDisplayorder
	 *            java.lang.Integer
	 */
	public void setDisplayorder(java.lang.Integer newDisplayorder) {
		this.displayorder = newDisplayorder;
	}

	/**
	 * 属性dataoriginflag的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDataoriginflag() {
		return dataoriginflag;
	}

	/**
	 * 属性dataoriginflag的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDataoriginflag
	 *            java.lang.Integer
	 */
	public void setDataoriginflag(java.lang.Integer newDataoriginflag) {
		this.dataoriginflag = newDataoriginflag;
	}

	/**
	 * 属性pk_vid的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_vid() {
		return pk_vid;
	}

	/**
	 * 属性pk_vid的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newPk_vid
	 *            java.lang.String
	 */
	public void setPk_vid(java.lang.String newPk_vid) {
		this.pk_vid = newPk_vid;
	}

	/**
	 * 属性vname的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getVname() {
		return vname;
	}

	/**
	 * 属性vname的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newVname
	 *            java.lang.String
	 */
	public void setVname(java.lang.String newVname) {
		this.vname = newVname;
	}

	/**
	 * 属性vno的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getVno() {
		return vno;
	}

	/**
	 * 属性vno的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newVno
	 *            java.lang.String
	 */
	public void setVno(java.lang.String newVno) {
		this.vno = newVno;
	}

	/**
	 * 属性vstartdate的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getVstartdate() {
		return vstartdate;
	}

	/**
	 * 属性vstartdate的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newVstartdate
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setVstartdate(nc.vo.pub.lang.UFDate newVstartdate) {
		this.vstartdate = newVstartdate;
	}

	/**
	 * 属性venddate的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getVenddate() {
		return venddate;
	}

	/**
	 * 属性venddate的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newVenddate
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setVenddate(nc.vo.pub.lang.UFDate newVenddate) {
		this.venddate = newVenddate;
	}

	/**
	 * 属性orgtype13的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getOrgtype13() {
		return orgtype13;
	}

	/**
	 * 属性orgtype13的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newOrgtype13
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setOrgtype13(nc.vo.pub.lang.UFBoolean newOrgtype13) {
		this.orgtype13 = newOrgtype13;
	}

	/**
	 * 属性orgtype17的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getOrgtype17() {
		return orgtype17;
	}

	/**
	 * 属性orgtype17的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newOrgtype17
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setOrgtype17(nc.vo.pub.lang.UFBoolean newOrgtype17) {
		this.orgtype17 = newOrgtype17;
	}

	/**
	 * 属性principal的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPrincipal() {
		return principal;
	}

	/**
	 * 属性principal的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newPrincipal
	 *            java.lang.String
	 */
	public void setPrincipal(java.lang.String newPrincipal) {
		this.principal = newPrincipal;
	}

	/**
	 * 属性tel的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTel() {
		return tel;
	}

	/**
	 * 属性tel的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newTel
	 *            java.lang.String
	 */
	public void setTel(java.lang.String newTel) {
		this.tel = newTel;
	}

	/**
	 * 属性address的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getAddress() {
		return address;
	}

	/**
	 * 属性address的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newAddress
	 *            java.lang.String
	 */
	public void setAddress(java.lang.String newAddress) {
		this.address = newAddress;
	}

	/**
	 * 属性memo的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getMemo() {
		return memo;
	}

	/**
	 * 属性memo的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newMemo
	 *            java.lang.String
	 */
	public void setMemo(java.lang.String newMemo) {
		this.memo = newMemo;
	}

	/**
	 * 属性def6的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef6() {
		return def6;
	}

	/**
	 * 属性def6的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef6
	 *            java.lang.String
	 */
	public void setDef6(java.lang.String newDef6) {
		this.def6 = newDef6;
	}

	/**
	 * 属性def7的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef7() {
		return def7;
	}

	/**
	 * 属性def7的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef7
	 *            java.lang.String
	 */
	public void setDef7(java.lang.String newDef7) {
		this.def7 = newDef7;
	}

	/**
	 * 属性def8的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef8() {
		return def8;
	}

	/**
	 * 属性def8的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef8
	 *            java.lang.String
	 */
	public void setDef8(java.lang.String newDef8) {
		this.def8 = newDef8;
	}

	/**
	 * 属性def9的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef9() {
		return def9;
	}

	/**
	 * 属性def9的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef9
	 *            java.lang.String
	 */
	public void setDef9(java.lang.String newDef9) {
		this.def9 = newDef9;
	}

	/**
	 * 属性def10的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef10() {
		return def10;
	}

	/**
	 * 属性def10的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef10
	 *            java.lang.String
	 */
	public void setDef10(java.lang.String newDef10) {
		this.def10 = newDef10;
	}

	/**
	 * 属性def11的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef11() {
		return def11;
	}

	/**
	 * 属性def11的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef11
	 *            java.lang.String
	 */
	public void setDef11(java.lang.String newDef11) {
		this.def11 = newDef11;
	}

	/**
	 * 属性def12的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef12() {
		return def12;
	}

	/**
	 * 属性def12的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef12
	 *            java.lang.String
	 */
	public void setDef12(java.lang.String newDef12) {
		this.def12 = newDef12;
	}

	/**
	 * 属性def13的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef13() {
		return def13;
	}

	/**
	 * 属性def13的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef13
	 *            java.lang.String
	 */
	public void setDef13(java.lang.String newDef13) {
		this.def13 = newDef13;
	}

	/**
	 * 属性def14的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef14() {
		return def14;
	}

	/**
	 * 属性def14的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef14
	 *            java.lang.String
	 */
	public void setDef14(java.lang.String newDef14) {
		this.def14 = newDef14;
	}

	/**
	 * 属性def15的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef15() {
		return def15;
	}

	/**
	 * 属性def15的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef15
	 *            java.lang.String
	 */
	public void setDef15(java.lang.String newDef15) {
		this.def15 = newDef15;
	}

	/**
	 * 属性def16的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef16() {
		return def16;
	}

	/**
	 * 属性def16的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef16
	 *            java.lang.String
	 */
	public void setDef16(java.lang.String newDef16) {
		this.def16 = newDef16;
	}

	/**
	 * 属性def17的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef17() {
		return def17;
	}

	/**
	 * 属性def17的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef17
	 *            java.lang.String
	 */
	public void setDef17(java.lang.String newDef17) {
		this.def17 = newDef17;
	}

	/**
	 * 属性def18的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef18() {
		return def18;
	}

	/**
	 * 属性def18的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef18
	 *            java.lang.String
	 */
	public void setDef18(java.lang.String newDef18) {
		this.def18 = newDef18;
	}

	/**
	 * 属性def19的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef19() {
		return def19;
	}

	/**
	 * 属性def19的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef19
	 *            java.lang.String
	 */
	public void setDef19(java.lang.String newDef19) {
		this.def19 = newDef19;
	}

	/**
	 * 属性def20的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef20() {
		return def20;
	}

	/**
	 * 属性def20的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDef20
	 *            java.lang.String
	 */
	public void setDef20(java.lang.String newDef20) {
		this.def20 = newDef20;
	}

	/**
	 * 属性deptcanceldate的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return nc.vo.pub.lang.UFLiteralDate
	 */
	public nc.vo.pub.lang.UFLiteralDate getDeptcanceldate() {
		return deptcanceldate;
	}

	/**
	 * 属性deptcanceldate的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDeptcanceldate
	 *            nc.vo.pub.lang.UFLiteralDate
	 */
	public void setDeptcanceldate(nc.vo.pub.lang.UFLiteralDate newDeptcanceldate) {
		this.deptcanceldate = newDeptcanceldate;
	}

	/**
	 * 属性islastversion的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIslastversion() {
		return islastversion;
	}

	/**
	 * 属性islastversion的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newIslastversion
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setIslastversion(nc.vo.pub.lang.UFBoolean newIslastversion) {
		this.islastversion = newIslastversion;
	}

	/**
	 * 属性dr的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newDr
	 *            java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * 属性ts的Getter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法. 创建日期:2008-02-26 16:44:24
	 * 
	 * @param newTs
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.ts = newTs;
	}

	public java.lang.String getVname2() {
		return vname2;
	}

	public void setVname2(java.lang.String vname2) {
		this.vname2 = vname2;
	}

	public java.lang.String getVname3() {
		return vname3;
	}

	public void setVname3(java.lang.String vname3) {
		this.vname3 = vname3;
	}

	public java.lang.String getVname4() {
		return vname4;
	}

	public void setVname4(java.lang.String vname4) {
		this.vname4 = vname4;
	}

	public java.lang.String getVname5() {
		return vname5;
	}

	public void setVname5(java.lang.String vname5) {
		this.vname5 = vname5;
	}

	public java.lang.String getVname6() {
		return vname6;
	}

	public void setVname6(java.lang.String vname6) {
		this.vname6 = vname6;
	}

	public nc.vo.pub.lang.UFBoolean getIsretail() {
		return isretail;
	}

	public void setIsretail(nc.vo.pub.lang.UFBoolean isretail) {
		this.isretail = isretail;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_dept";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "org_dept";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2008-02-26 16:44:24
	 * 
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "org_dept";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2008-02-26 16:44:24
	 */
	public DeptVO() {
		super();
	}

	/******************************************************/

	private HashMap<String, Object> businessOrgMap = null; // 用于存储orgvo选中的组织类型对应的orgtypevo数据

	public HashMap<String, Object> getBusinessOrgMap() {
		if (businessOrgMap == null || businessOrgMap.size() == 0
				|| businessOrgMap.get(OrgVOQueryUtil.REPORTORGTYPE/*TODO 临时修改，待以后构造方式调整后，再修改为IOrgConst*/) == null) {
			businessOrgMap = OrgVOQueryUtil.getInstance()
					.getDeptTypeVOMap(this);
		}
		return businessOrgMap;
	}

	/**
	 * 更新OrgVO中的组织类型数据Map中的对应组织类型数据
	 * 
	 * @param obj
	 */
	public void syncOrgTypeData(Object obj) {
		OrgTypeVO orgtypevo = OrgVOQueryUtil.getInstance()
				.getOrgTypeByFullclassname(obj.getClass().getName());
		if (orgtypevo != null) {
			if (getBusinessOrgMap().get(orgtypevo.getPrimaryKey()) != null) {
				getBusinessOrgMap().remove(orgtypevo.getPrimaryKey());
			}
			getBusinessOrgMap().put(orgtypevo.getPrimaryKey(), obj);
		}
	}

	/**
	 * 根据组织类型主键得到具体组织VO数据
	 * 
	 * @param orgtypeID
	 * @return
	 */
	public Object getBusinessOrgVOByTypeID(String pk_orgtype)
			throws BusinessException {
		return getBusinessOrgMap().get(pk_orgtype);
	}

	public java.lang.String getChargeleader() {
		return chargeleader;
	}

	public void setChargeleader(java.lang.String chargeleader) {
		this.chargeleader = chargeleader;
	}
	
	public Integer getWeekform(){
		return weekform;
	}
	public void setWeekform(Integer weekform){
		this.weekform=weekform;
	}
	public Integer getOvertimecontrol(){
		return overtimecontrol;
	}
	public void setOvertimecontrol(Integer overtimecontrol){
		this.overtimecontrol=overtimecontrol;
	}
	/******************************************************/

}
