/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.wa.classitem;

import nc.hr.utils.ResHelper;
import nc.vo.bd.defdoc.DefdocVO;
import nc.vo.pub.VOStatus;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.wa.item.WaItemVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2009-12-03 09:38:36
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WaClassItemVO extends WaItemVO {
	private String pk_wa_classitem;
	private String pk_wa_class;
	private String cyear;
	private String cperiod;

	private Integer icomputeseq = 0;
	private Integer idisplayseq;
	private Integer round_type = null;

	private String destitempk;
	private String destitemcol;

	private Integer bankaccount;
	
    private java.lang.String trano;
    private java.lang.String debitentry;
    private java.lang.String debitentry_b;
    private java.lang.String creditsubject;
    private java.lang.String credisubject_b;

	private UFBoolean showflag = UFBoolean.TRUE;
	private UFBoolean issysformula = UFBoolean.FALSE;
	private UFBoolean editflag = UFBoolean.TRUE;
	private UFBoolean inapproveditem = UFBoolean.FALSE;

	@Deprecated
	// private String othersys;
	private DefdocVO categoryVO;

	private UFBoolean istransfer = UFBoolean.FALSE;

	public static final String PK_WA_CLASSITEM = "pk_wa_classitem";
	public static final String PK_WA_CLASS = "pk_wa_class";
	public static final String CYEAR = "cyear";
	public static final String CPERIOD = "cperiod";

	public static final String ICOMPUTESEQ = "icomputeseq";
	public static final String IDISPLAYSEQ = "idisplayseq";
	public static final String ROUND_TYPE = "round_type";

	public static final String DESTITEMPK = "destitempk";
	public static final String DESTITEMCOL = "destitemcol";

	public static final String SHOWFLAG = "showflag";
	public static final String ISSYSFORMULA = "issysformula";
	public static final String EDITFLAG = "editflag";

	public static final String OTHERSYS = "othersys";
	public static final String ISTRANSFER = "istransfer";
	public static final String BANKACCOUNT = "bankaccount";

	public static final String INAPPROVEDITEM = "inapproveditem";

	public static final String TABLE_NAME = "wa_classitem";
	
	
	/**
	 * 添加trano
		借方科目
		借方子科目
		贷方科目
		贷方子科目
		五个字段 
		2018年6月4日16:11:18
	 */
    public static final String TRANO = "trano";
    public static final String DEBITENTRY = "debitentry";
    public static final String DEBITENTRY_B = "debitentry_b";
    public static final String CREDITSUBJECT = "creditsubject";
    public static final String CREDISUBJECT_B = "credisubject_b";

	@Override
	public String toString() {
		return getMultilangName();
	}

	public java.lang.String getTrano() {
		return trano;
	}

	public void setTrano(java.lang.String trano) {
		this.trano = trano;
	}

	public java.lang.String getDebitentry() {
		return debitentry;
	}

	public void setDebitentry(java.lang.String debitentry) {
		this.debitentry = debitentry;
	}

	public java.lang.String getDebitentry_b() {
		return debitentry_b;
	}

	public void setDebitentry_b(java.lang.String debitentry_b) {
		this.debitentry_b = debitentry_b;
	}

	public java.lang.String getCreditsubject() {
		return creditsubject;
	}

	public void setCreditsubject(java.lang.String creditsubject) {
		this.creditsubject = creditsubject;
	}

	public java.lang.String getCredisubject_b() {
		return credisubject_b;
	}

	public void setCredisubject_b(java.lang.String credisubject_b) {
		this.credisubject_b = credisubject_b;
	}

	/**
	 * 属性pk_wa_classitem的Getter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_wa_classitem() {
		return pk_wa_classitem;
	}

	public Integer getRound_type() {
		return round_type == null ? RoundTypeEnum.ROUND.value() : round_type;
	}

	public void setRound_type(Integer round_type) {
		this.round_type = round_type;
	}

	public UFBoolean getInapproveditem() {
		return inapproveditem;
	}

	public void setInapproveditem(UFBoolean inapproveditem) {
		this.inapproveditem = inapproveditem;
	}

	public Integer getBankaccount() {
		return bankaccount;
	}

	public void setBankaccount(Integer bankaccount) {
		this.bankaccount = bankaccount;
	}

	/**
	 * 属性pk_wa_classitem的Setter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @param newPk_wa_classitem
	 *            java.lang.String
	 */
	public void setPk_wa_classitem(java.lang.String newPk_wa_classitem) {
		this.pk_wa_classitem = newPk_wa_classitem;
	}

	/**
	 * 属性pk_wa_class的Getter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_wa_class() {
		return pk_wa_class;
	}

	public UFBoolean getIstransfer() {
		return istransfer;
	}

	public void setIstransfer(UFBoolean istransfer) {
		this.istransfer = istransfer;
	}

	/**
	 * 属性pk_wa_class的Setter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @param newPk_wa_class
	 *            java.lang.String
	 */
	public void setPk_wa_class(java.lang.String newPk_wa_class) {
		this.pk_wa_class = newPk_wa_class;
	}

	/**
	 * 属性cyear的Getter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCyear() {
		return cyear;
	}

	/**
	 * 属性cyear的Setter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @param newCyear
	 *            java.lang.String
	 */
	public void setCyear(java.lang.String newCyear) {
		this.cyear = newCyear;
	}

	/**
	 * 属性cperiod的Getter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCperiod() {
		return cperiod;
	}

	/**
	 * 属性cperiod的Setter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @param newCperiod
	 *            java.lang.String
	 */
	public void setCperiod(java.lang.String newCperiod) {
		this.cperiod = newCperiod;
	}

	/**
	 * 属性pk_wa_item的Getter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @return java.lang.String
	 */

	/**
	 * 属性icomputeseq的Getter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getIcomputeseq() {
		return icomputeseq;
	}

	/**
	 * 属性icomputeseq的Setter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @param newIcomputeseq
	 *            java.lang.Integer
	 */
	public void setIcomputeseq(java.lang.Integer newIcomputeseq) {
		this.icomputeseq = newIcomputeseq;
	}

	/**
	 * 属性idisplayseq的Getter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getIdisplayseq() {
		return idisplayseq;
	}

	/**
	 * 属性idisplayseq的Setter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @param newIdisplayseq
	 *            java.lang.Integer
	 */
	public void setIdisplayseq(java.lang.Integer newIdisplayseq) {
		this.idisplayseq = newIdisplayseq;
	}

	/**
	 * 属性showflag的Getter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getShowflag() {
		return showflag;
	}

	/**
	 * 属性showflag的Setter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @param newShowflag
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setShowflag(nc.vo.pub.lang.UFBoolean newShowflag) {
		this.showflag = newShowflag;
	}

	/**
	 * 属性issysformula的Getter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIssysformula() {
		return issysformula;
	}

	/**
	 * 属性issysformula的Setter方法. 创建日期:2009-12-03 09:38:36
	 * 
	 * @param newIssysformula
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setIssysformula(nc.vo.pub.lang.UFBoolean newIssysformula) {
		this.issysformula = newIssysformula;
	}

	/**
	 * 属性destitempk的Getter方法. 创建日期:2009-08-26 16:52:43
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDestitempk() {
		return destitempk;
	}

	/**
	 * 属性destitempk的Setter方法. 创建日期:2009-08-26 16:52:43
	 * 
	 * @param newDestitempk
	 *            java.lang.String
	 */
	public void setDestitempk(java.lang.String newDestitempk) {
		this.destitempk = newDestitempk;
	}

	/**
	 * 属性destitemcol的Getter方法. 创建日期:2009-08-26 16:52:43
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDestitemcol() {
		return destitemcol;
	}

	/**
	 * 属性destitemcol的Setter方法. 创建日期:2009-08-26 16:52:43
	 * 
	 * @param newDestitemcol
	 *            java.lang.String
	 */
	public void setDestitemcol(java.lang.String newDestitemcol) {
		this.destitemcol = newDestitemcol;
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2009-12-03 09:38:36
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getPKFieldName() {
		return "pk_wa_classitem";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2009-12-03 09:38:36
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getTableName() {
		return "wa_classitem";
	}

	/**
	 * 按照默认方式创建构造子. 创建日期:2009-12-03 09:38:36
	 */
	public WaClassItemVO() {
		super();
	}

	public nc.vo.pub.lang.UFBoolean getEditflag() {
		return editflag;
	}

	public void setEditflag(nc.vo.pub.lang.UFBoolean editflag) {
		this.editflag = editflag;
	}

	public DefdocVO getCategoryVO() {
		return categoryVO;
	}

	public void setCategoryVO(DefdocVO categoryVO) {
		this.categoryVO = categoryVO;
	}

	/**
	 * 将公共项目中的通用属性设置到　发放项目中。 注意：发放项目中的　pk_org pk_group Pk_wa_class Cyear cperiod
	 * displayseq 需要自己设置 必要时可能需要设置 Issysformula 于 status
	 * 
	 */
	public void merge(WaItemVO item) {

		for (String attr : item.getAttributeNames()) {
			if (WaItemVO.PK_ORG.equals(attr) || WaItemVO.PK_GROUP.equals(attr)) {
				continue;
			}
			if (WaItemVO.VFORMULASTR.equals(attr)) {
				// 将公式中的 "公共薪资项目"取代为 "薪资发放项目"
				Object vformularStr = item.getAttributeValue(attr);
				if (vformularStr != null) {
					vformularStr = vformularStr.toString().replaceAll(
							ResHelper.getString("60130payitem", "160130glbitem0008")/*
																					 * @
																					 * res
																					 * "公共薪资项目"
																					 */,
							ResHelper.getString("60130payitem", "160130payitem0006")/*
																					 * @
																					 * res
																					 * "薪资发放项目"
																					 */);
				}
				setAttributeValue(attr, vformularStr);
			} else {
				setAttributeValue(attr, item.getAttributeValue(attr));
			}

		}
	}

	public WaItemVO abstracts() {

		WaItemVO itemvo = new WaItemVO();
		for (String attr : this.getAttributeNames()) {

			if (WaItemVO.VFORMULASTR.equals(attr)) {
				// 将公式中的 "公共薪资项目"取代为 "薪资发放项目"
				Object vformularStr = this.getAttributeValue(attr);
				if (vformularStr != null) {
					vformularStr = vformularStr.toString().replaceAll(
							ResHelper.getString("60130payitem", "160130payitem0006")/*
																					 * @
																					 * res
																					 * "薪资发放项目"
																					 */,
							ResHelper.getString("60130payitem", "160130glbitem0008")/*
																					 * @
																					 * res
																					 * "公共薪资项目"
																					 */);
				}
				itemvo.setAttributeValue(attr, vformularStr);
			} else {
				itemvo.setAttributeValue(attr, this.getAttributeValue(attr));
			}

			itemvo.setStatus(VOStatus.NEW);
			// 如何为itemvo生成一个code？ 必输入项包括 编码 、 名称、数据类型、增减属性、数据长度、小数位数
			// 利用一个主键来定
			itemvo.setCode("unknown");

		}
		return itemvo;
	}

	// MOD {薪资发放项目增加20个自定义项，用于分摊方案，借方科目，借方供应商编码，贷方科目，贷方供应商编码字段扩展} kevin.nie
	// 2017-09-08 start
	private String def1;
	private String def2;
	private String def3;
	private String def4;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private String def9;
	private String def10;
	private String def11;
	private String def12;
	private String def13;
	private String def14;
	private String def15;
	private String def16;
	private String def17;
	private String def18;
	private String def19;
	private String def20;

	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
	public static final String DEF11 = "def11";
	public static final String DEF12 = "def12";
	public static final String DEF13 = "def13";
	public static final String DEF14 = "def14";
	public static final String DEF15 = "def15";
	public static final String DEF16 = "def16";
	public static final String DEF17 = "def17";
	public static final String DEF18 = "def18";
	public static final String DEF19 = "def19";
	public static final String DEF20 = "def20";

	public String getDef1() {
		return def1;
	}

	public void setDef1(String def1) {
		this.def1 = def1;
	}

	public String getDef2() {
		return def2;
	}

	public void setDef2(String def2) {
		this.def2 = def2;
	}

	public String getDef3() {
		return def3;
	}

	public void setDef3(String def3) {
		this.def3 = def3;
	}

	public String getDef4() {
		return def4;
	}

	public void setDef4(String def4) {
		this.def4 = def4;
	}

	public String getDef5() {
		return def5;
	}

	public void setDef5(String def5) {
		this.def5 = def5;
	}

	public String getDef6() {
		return def6;
	}

	public void setDef6(String def6) {
		this.def6 = def6;
	}

	public String getDef7() {
		return def7;
	}

	public void setDef7(String def7) {
		this.def7 = def7;
	}

	public String getDef8() {
		return def8;
	}

	public void setDef8(String def8) {
		this.def8 = def8;
	}

	public String getDef9() {
		return def9;
	}

	public void setDef9(String def9) {
		this.def9 = def9;
	}

	public String getDef10() {
		return def10;
	}

	public void setDef10(String def10) {
		this.def10 = def10;
	}

	public String getDef11() {
		return def11;
	}

	public void setDef11(String def11) {
		this.def11 = def11;
	}

	public String getDef12() {
		return def12;
	}

	public void setDef12(String def12) {
		this.def12 = def12;
	}

	public String getDef13() {
		return def13;
	}

	public void setDef13(String def13) {
		this.def13 = def13;
	}

	public String getDef14() {
		return def14;
	}

	public void setDef14(String def14) {
		this.def14 = def14;
	}

	public String getDef15() {
		return def15;
	}

	public void setDef15(String def15) {
		this.def15 = def15;
	}

	public String getDef16() {
		return def16;
	}

	public void setDef16(String def16) {
		this.def16 = def16;
	}

	public String getDef17() {
		return def17;
	}

	public void setDef17(String def17) {
		this.def17 = def17;
	}

	public String getDef18() {
		return def18;
	}

	public void setDef18(String def18) {
		this.def18 = def18;
	}

	public String getDef19() {
		return def19;
	}

	public void setDef19(String def19) {
		this.def19 = def19;
	}

	public String getDef20() {
		return def20;
	}

	public void setDef20(String def20) {
		this.def20 = def20;
	}
	// {薪资发放项目增加20个自定义项，用于分摊方案，借方科目，借方供应商编码，贷方科目，贷方供应商编码字段扩展} kevin.nie
	// 2017-09-08 end
}