
delete pub_billtemplet_t where ( pk_billtemplet in ('0001ZZ10000000057EX0') and (dr=0 or dr is null) )
/

delete pub_billtemplet_b where ( pk_billtemplet in ('0001ZZ10000000057EX0') and (dr=0 or dr is null) )
/

delete pub_billtemplet where ( PK_BILLTEMPLET='0001ZZ10000000057EX0' and (bill_templetname='SYSTEM') and (dr=0 or dr is null) )
/


insert into pub_billtemplet(bill_templetcaption,bill_templetname,devorg,dividerproportion,dr,funccode,layer,metadataclass,model_type,modulecode,nodecode,options,pk_billtemplet,pk_billtypecode,pk_corp,pk_org,resid,shareflag,ts,validateformula) values( '部门调整申请','SYSTEM',null,'0.8149779735682819',0,null,0,'hrjf.deptadj',null,'HRJF','60050deptadj',null,'0001ZZ10000000057EX0','60050depta','@@@@',null,null,null,'2018-11-09 11:05:36',null)
/


insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_deptadj',0,'N',1,'N','N',2,null,0,'pk_deptadj','hrjf.deptadj.pk_deptadj',null,'N',0,null,'0001ZZ10000000057EX0','0001ZZ10000000057EX1','@@@@',0,null,null,null,'N',0,1,'deptadj','部门调整申请',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_dept_v',0,'N',1,'N','N',6,null,0,'pk_dept_v','hrjf.deptadj.pk_dept_v',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004DA1H','@@@@',0,null,null,null,'N',0,6,'deptadj','deptadj',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'effectivedate',0,'N',1,'N','Y',17,null,0,'effectivedate','hrjf.deptadj.effectivedate',null,'N',0,null,'0001ZZ10000000057EX0','0001ZZ10000000057EXB','@@@@',0,null,null,null,'N',1,2,'deptadj','部门调整申请',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_dept',0,'N',1,'N','Y',18,null,0,'pk_dept','hrjf.deptadj.pk_dept',null,'N',0,null,'0001ZZ10000000057EX0','0001ZZ10000000057EXD','@@@@',0,null,null,null,'N',1,3,'deptadj','部门调整申请',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.code',null,'N',1,'N','Y',3,null,0,'pk_vid.code','uap.dept_v.code',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004CI9L',null,0,null,null,null,'N',1,2,'001','001',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.name',null,'N',1,'N','Y',5,null,0,'pk_vid.name','uap.dept_v.name',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004CI9N',null,0,null,null,null,'N',1,3,'001','001',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,0,'调整前信息主键',null,0,1,null,-1,'N',null,20,'调整前信息主键',null,'N',1,'N','N',0,null,0,null,null,null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004CI9O',null,0,null,null,null,'N',0,1,'001','调整前信息',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.pk_fatherorg',0,'N',1,'N','Y',5,null,0,'pk_vid.pk_fatherorg','uap.dept_v.pk_fatherorg',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004DA1T','@@@@',0,null,null,null,'N',1,4,'001','001',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,0,'调整后信息主键',null,0,1,null,-1,'N',null,20,'调整后信息主键',null,'N',1,'N','N',1,null,0,null,null,null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004CI9W',null,0,null,null,null,'N',0,1,'002','调整后信息',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.mnecode',0,'N',1,'N','Y',7,null,0,'pk_vid.mnecode','uap.dept_v.mnecode',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004DA1V','@@@@',0,null,null,null,'N',1,6,'001','001',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.displayorder',0,'N',1,'N','Y',8,null,0,'pk_vid.displayorder','uap.dept_v.displayorder',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004DA1W','@@@@',0,null,null,null,'N',1,7,'001','001',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.principal',0,'N',1,'N','Y',9,null,0,'pk_vid.principal','uap.dept_v.principal',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004DA1X','@@@@',0,null,null,null,'N',1,8,'001','001',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',24,null,0,'ts','hrjf.deptadj.ts',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D99W',null,0,null,null,null,'N',0,25,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.shortname',0,'N',1,'N','Y',6,null,0,'pk_vid.shortname','uap.dept_v.shortname',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004DA1Y','@@@@',0,null,null,null,'N',1,5,'001','001',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'上级部门编码',null,0,0,null,-1,'N','pk_fatherorg',-1,'pk_fatherorg.code',0,'N',1,'N','Y',6,null,0,'code','hrjf.hrdept.code',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004DEOY','@@@@',0,null,null,null,'N',1,6,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'code',null,'N',1,'N','Y',4,null,0,'code','hrjf.deptadj.code',null,'N',1,null,'0001ZZ10000000057EX0','1001ZZ1000000004CIA0',null,0,null,null,null,'N',1,2,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'name',null,'N',1,'N','Y',6,null,0,'name','hrjf.deptadj.name',null,'N',1,null,'0001ZZ10000000057EX0','1001ZZ1000000004CIA2',null,0,null,null,null,'N',1,3,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'上级部门编码',null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_fatherorg.code',null,'N',1,'N','Y',9,null,0,'pk_fatherorg.code','hrjf.hrdept.code',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004DGZH',null,0,null,null,null,'N',1,9,'001',null,0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,0,null,-1,'N',null,-1,'iseffective',0,'N',1,'N','Y',7,null,0,'iseffective','hrjf.deptadj.iseffective',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004CWXO','@@@@',0,null,null,null,'N',1,4,'deptadj','deptadj',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'innercode',null,'N',1,'N','N',4,null,0,'innercode','hrjf.deptadj.innercode',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8I5',null,0,null,null,null,'N',0,4,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'enablestate',null,'N',1,'N','N',14,null,0,'enablestate','hrjf.deptadj.enablestate',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8I6',null,0,null,null,null,'N',0,15,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'tel',null,'N',1,'N','Y',20,null,0,'tel','hrjf.deptadj.tel',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8I7',null,0,null,null,null,'N',1,21,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,1,null,-1,'N',null,-1,'orgtype13',null,'N',1,'N','N',17,null,0,'orgtype13','hrjf.deptadj.orgtype13',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8I8',null,0,null,null,null,'N',0,18,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'dataoriginflag',null,'N',1,'N','N',16,null,0,'dataoriginflag','hrjf.deptadj.dataoriginflag',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8I9',null,0,null,null,null,'N',0,17,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'displayorder',null,'N',1,'N','Y',15,null,0,'displayorder','hrjf.deptadj.displayorder',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8IA',null,0,null,null,null,'N',1,16,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'是否撤销(用於取消撤銷)','false',0,0,null,-1,'N',null,-1,'hrcanceled',null,'N',1,'N','Y',12,null,0,'hrcanceled','hrjf.deptadj.hrcanceled',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8IB',null,0,null,null,null,'N',1,13,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'depttype',null,'N',1,'N','Y',6,null,0,'depttype','hrjf.deptadj.depttype',null,'N',1,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8IC',null,0,null,null,null,'N',1,7,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'mnecode',null,'N',1,'N','Y',11,null,0,'mnecode','hrjf.deptadj.mnecode',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8ID',null,0,null,null,null,'N',1,12,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,1,null,-1,'N',null,-1,'islastversion',null,'N',1,'N','N',23,null,0,'islastversion','hrjf.deptadj.islastversion',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8IE',null,0,null,null,null,'N',0,24,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,1,null,-1,'N',null,-1,'orgtype17',null,'N',1,'N','N',18,null,0,'orgtype17','hrjf.deptadj.orgtype17',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8IF',null,0,null,null,null,'N',0,19,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'deptcanceldate',null,'N',1,'N','Y',13,null,0,'deptcanceldate','hrjf.deptadj.deptcanceldate',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8IG',null,0,null,null,null,'N',1,14,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'address',null,'N',1,'N','Y',21,null,0,'address','hrjf.deptadj.address',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8IH',null,0,null,null,null,'N',1,22,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'deptlevel',null,'N',1,'N','Y',7,null,0,'deptlevel','hrjf.deptadj.deptlevel',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8II',null,0,null,null,null,'N',1,8,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_fatherorg',null,'N',1,'N','Y',5,null,0,'pk_fatherorg','hrjf.deptadj.pk_fatherorg',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8HZ',null,0,null,null,null,'N',1,5,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'principal',null,'N',1,'N','Y',19,null,0,'principal','hrjf.deptadj.principal',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8I0',null,0,null,null,null,'N',1,20,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'createdate',null,'N',1,'N','Y',9,null,0,'createdate','hrjf.deptadj.createdate',null,'N',1,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8I1',null,0,null,null,null,'N',1,10,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'shortname',null,'N',1,'N','Y',10,null,0,'shortname','hrjf.deptadj.shortname',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8I2',null,0,null,null,null,'N',1,11,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'deptduty',null,'N',1,'N','Y',8,null,0,'deptduty','hrjf.deptadj.deptduty',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8I3',null,0,null,null,null,'N',1,9,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'memo',null,'N',1,'N','Y',22,null,0,'memo','hrjf.deptadj.memo',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004D8I4',null,0,null,null,null,'N',1,23,'002','002',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'billdate',0,'N',1,'N','N',20,null,0,'billdate','hrjf.deptadj.billdate',null,'N',0,null,'0001ZZ10000000057EX0','1001ZZ1000000004CWY1','@@@@',0,null,null,null,'N',0,5,'deptadj','deptadj',0,'2018-11-09 11:05:36','N',null,null,null,1,1,'N',1,null,1)
/


insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrjf.deptadj','deptadj',null,'0001ZZ10000000057EX0','1001ZZ1000000004DVNH',null,0,0,null,'deptadj',0,'部门调整申请','2018-11-09 11:05:44',null,null,null)
/
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( 'deptadj',0,'hrjf.deptadj','deptadj',null,'0001ZZ10000000057EX0','1001ZZ1000000004DVNI',null,0,0,null,'001',1,'调整前信息','2018-11-09 11:05:44',null,null,null)
/
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( 'deptadj',0,'hrjf.deptadj','deptadj',null,'0001ZZ10000000057EX0','1001ZZ1000000004DVNJ',null,0,0,null,'002',2,'调整后信息','2018-11-09 11:05:44',null,null,null)
/
