
delete pub_billtemplet_t where ( pk_billtemplet in ('1001Z710000000022P1M') and (dr=0 or dr is null) )
go

delete pub_billtemplet_b where ( pk_billtemplet in ('1001Z710000000022P1M') and (dr=0 or dr is null) )
go

delete pub_billtemplet where ( pk_billtemplet='1001Z710000000022P1M' and (bill_templetname='SYSTEM') and (dr=0 or dr is null) )
go


insert into pub_billtemplet(bill_templetcaption,bill_templetname,devorg,dividerproportion,dr,funccode,layer,metadataclass,model_type,modulecode,nodecode,options,pk_billtemplet,pk_billtypecode,pk_corp,pk_org,resid,shareflag,ts,validateformula) values( '社保档案','SYSTEM',null,null,0,null,0,'hrbm.bmdata',null,'HRBM','60150bmfile',null,'1001Z710000000022P1M','bmfile','@@@@',null,'160150bmfile0011',null,'2017-11-13 18:25:04',null)
go


insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_liabilitydept',0,'N',1,'N','N',32,null,0,'pk_liabilitydept','hrbm.bmdata.pk_liabilitydept',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033U9B','@@@@',0,null,null,null,'N',0,32,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'任职部门oid',null,0,0,null,-1,'N',null,-1,'workdept',0,'N',1,'N','N',28,null,0,'workdept','hrbm.bmdata.workdept',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033U9C','@@@@',0,null,'160150bmfile0009',null,'N',0,28,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'任职组织oid',null,0,0,null,-1,'N',null,-1,'workorg',0,'N',1,'N','N',29,null,0,'workorg','hrbm.bmdata.workorg',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033U9D','@@@@',0,'业务单元','160150bmfile0010',null,'N',0,29,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_financedept',0,'N',1,'N','N',31,null,0,'pk_financedept','hrbm.bmdata.pk_financedept',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033U9A','@@@@',0,null,null,null,'N',0,31,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_liabilityorg',0,'N',1,'N','N',20,null,0,'pk_liabilityorg','hrbm.bmdata.pk_liabilityorg',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033U99','@@@@',0,null,null,null,'N',1,20,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_financeorg',0,'N',1,'N','N',30,null,0,'pk_financeorg','hrbm.bmdata.pk_financeorg',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033U98','@@@@',0,null,null,null,'N',0,30,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'assgid',null,'N',1,'N','N',25,null,0,'assgid','hrbm.bmdata.assgid',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033U8U',null,0,null,null,null,'N',0,25,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_bm_data',null,'N',1,'N','N',22,null,0,'pk_bm_data','hrbm.bmdata.pk_bm_data',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033U8T',null,0,null,null,null,'N',0,22,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'人员编码',null,0,0,null,-1,'N',null,-1,'pk_psndoc',null,'N',1,'N','Y',0,null,0,'pk_psndoc','hrbm.bmdata.pk_psndoc',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033U8S',null,0,'HR人员,code=Y','160150bmfile0021',null,'N',1,0,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',26,null,0,'pk_group','hrbm.bmdata.pk_group',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033U8R',null,0,null,null,null,'N',0,26,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_psnorg',null,'N',1,'N','N',24,null,0,'pk_psnorg','hrbm.bmdata.pk_psnorg',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033U8Q',null,0,null,null,null,'N',0,24,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',27,null,0,'pk_org','hrbm.bmdata.pk_org',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033U8P',null,0,null,null,null,'N',0,27,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'险种编码',null,0,0,null,-1,'N',null,-1,'pk_bm_class',0,'N',1,'N','Y',11,null,0,'pk_bm_class','hrbm.bmdata.pk_bm_class',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033PMH','@@@@',0,'<nc.ui.bm.ref.BmClassRefModel>,code=Y','160150bmfile0008',null,'N',0,11,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'accounttype',0,'N',1,'N','Y',15,null,0,'accounttype','hrbm.bmdata.accounttype',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033PME','@@@@',0,null,null,null,'N',0,15,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',33,null,0,'ts','hrbm.bmdata.ts',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000001NF0','@@@@',0,null,null,null,'N',0,33,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.clerkcode',0,'N',1,'N','Y',1,null,0,'clerkcode','hrhi.hi_psnjob.clerkcode',null,'N',0,null,'1001Z710000000022P1M','1001Z71000000000111G','@@@@',0,null,null,null,'N',1,1,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'社保供应商代码(个人)',null,0,0,null,-1,'N',null,-1,'def3',0,'N',1,'N','Y',17,null,0,'def3','hrbm.bmdata.def3',null,'N',0,null,'1001Z710000000022P1M','1001AA10000000001453','@@@@',0,'1001AA1000000000GGLF:社保供應商代碼(自定义档案)','160150bmfile0033',null,'N',0,17,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def13',0,'N',1,'N','N',43,null,0,'def13','hrbm.bmdata.def13',null,'N',0,null,'1001Z710000000022P1M','1001AA10000000001452','@@@@',0,null,null,null,'N',0,50,'bmdata',null,0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'社保供应商代码(公司)',null,0,0,null,-1,'N',null,-1,'def2',0,'N',1,'N','Y',16,null,0,'def2','hrbm.bmdata.def2',null,'N',0,null,'1001Z710000000022P1M','1001AA10000000001451','@@@@',0,'1001AA1000000000GGLF:社保供應商代碼(自定义档案)','160150bmfile0032',null,'N',0,16,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def12',0,'N',1,'N','N',42,null,0,'def12','hrbm.bmdata.def12',null,'N',0,null,'1001Z710000000022P1M','1001AA10000000001450','@@@@',0,null,null,null,'N',0,42,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def8',0,'N',1,'N','N',38,null,0,'def8','hrbm.bmdata.def8',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144Z','@@@@',0,null,null,null,'N',0,38,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def15',0,'N',1,'N','N',45,null,0,'def15','hrbm.bmdata.def15',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144Y','@@@@',0,null,null,null,'N',0,44,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def14',0,'N',1,'N','N',44,null,0,'def14','hrbm.bmdata.def14',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144X','@@@@',0,null,null,null,'N',0,43,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def6',0,'N',1,'N','N',36,null,0,'def6','hrbm.bmdata.def6',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144W','@@@@',0,null,null,null,'N',0,36,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def18',0,'N',1,'N','N',48,null,0,'def18','hrbm.bmdata.def18',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144V','@@@@',0,null,null,null,'N',0,47,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def19',0,'N',1,'N','N',49,null,0,'def19','hrbm.bmdata.def19',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144U','@@@@',0,null,null,null,'N',0,48,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def11',0,'N',1,'N','N',41,null,0,'def11','hrbm.bmdata.def11',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144T','@@@@',0,null,null,null,'N',0,41,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def5',0,'N',1,'N','N',35,null,0,'def5','hrbm.bmdata.def5',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144S','@@@@',0,null,null,null,'N',0,35,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def10',0,'N',1,'N','N',40,null,0,'def10','hrbm.bmdata.def10',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144R','@@@@',0,null,null,null,'N',0,40,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def20',0,'N',1,'N','N',50,null,0,'def20','hrbm.bmdata.def20',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144Q','@@@@',0,null,null,null,'N',0,49,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def9',0,'N',1,'N','N',39,null,0,'def9','hrbm.bmdata.def9',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144P','@@@@',0,null,null,null,'N',0,39,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def17',0,'N',1,'N','N',47,null,0,'def17','hrbm.bmdata.def17',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144O','@@@@',0,null,null,null,'N',0,46,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def16',0,'N',1,'N','N',46,null,0,'def16','hrbm.bmdata.def16',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144N','@@@@',0,null,null,null,'N',0,45,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def7',0,'N',1,'N','N',37,null,0,'def7','hrbm.bmdata.def7',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144M','@@@@',0,null,null,null,'N',0,37,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'社保代理公司',null,0,1,null,-1,'N',null,-1,'def1',0,'N',1,'N','Y',9,null,0,'def1','hrbm.bmdata.def1',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144L','@@@@',0,'1001A110000000007QJW:社保代理公司(自定义档案),code=N','160150bmfile0031',null,'N',1,9,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def4',0,'N',1,'N','N',34,null,0,'def4','hrbm.bmdata.def4',null,'N',0,null,'1001Z710000000022P1M','1001AA1000000000144K','@@@@',0,null,null,null,'N',0,34,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'paylocation',0,'N',1,'N','Y',13,null,0,'paylocation','hrbm.bmdata.paylocation',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033PMD','@@@@',0,null,null,null,'N',0,13,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'bmaccountno',0,'N',1,'N','Y',10,null,0,'bmaccountno','hrbm.bmdata.bmaccountno',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033PMC','@@@@',0,null,null,null,'N',0,10,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'accountstate',0,'N',1,'N','Y',14,null,0,'accountstate','hrbm.bmdata.accountstate',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033PMA','@@@@',0,null,null,null,'N',0,14,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_bm_class',-1,'pk_bm_class.name',0,'N',1,'N','Y',12,null,0,'name','hrbm.bmclass.name',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033PM9','@@@@',0,null,null,null,'N',0,12,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'1',0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.assgid',0,'N',1,'N','N',5,null,0,'assgid','hrhi.hi_psnjob.assgid',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000033PM4','@@@@',0,null,null,null,'N',0,6,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_psndoc.id',0,'N',1,'N','Y',4,null,0,'pk_psndoc.id','hrhi.bd_psndoc.id',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000023M8L','@@@@',0,null,null,null,'N',1,4,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_psndoc.idtype',0,'N',1,'N','Y',3,null,0,'pk_psndoc.idtype','hrhi.bd_psndoc.idtype',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000023M8K','@@@@',0,null,null,null,'N',1,3,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_psndoc.name',0,'N',1,'N','Y',2,null,0,'pk_psndoc.name','hrhi.bd_psndoc.name',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000023M8F','@@@@',0,null,null,null,'N',1,2,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'人员编码',null,0,0,null,-1,'N',null,-1,'pk_psnjob',0,'N',1,'N','N',21,null,0,'pk_psnjob','hrbm.bmdata.pk_psnjob',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000023M8A','@@@@',0,'人员工作记录,code=Y','UC000-0000147',null,'N',0,21,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_psncl',0,'N',1,'N','Y',8,null,0,'pk_psncl','hrhi.hi_psnjob.pk_psncl',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000023M85','@@@@',0,null,null,null,'N',1,8,'bmdata','bmdata',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'成本部门',null,0,1,null,-1,'N',null,-1,'libdeptvid',0,'N',1,'N','N',23,null,0,'libdeptvid','hrbm.bmdata.libdeptvid',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000022P2L','@@@@',0,'<nc.ui.wabm.file.refmodel.CostDeptVersionRefModel>','160150bmfile0006',null,'N',1,23,'bmdata','社保数据',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'财务部门',null,0,1,null,-1,'N',null,-1,'fipdeptvid',0,'N',1,'N','N',19,null,0,'fipdeptvid','hrbm.bmdata.fipdeptvid',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000022P2H','@@@@',0,null,'160150bmfile0005',null,'N',1,19,'bmdata','社保数据',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'财务组织',null,0,1,null,-1,'N',null,-1,'fiporgvid',0,'N',1,'N','N',18,null,0,'fiporgvid','hrbm.bmdata.fiporgvid',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000022P2F','@@@@',0,null,'160150bmfile0004',null,'N',1,18,'bmdata','社保数据',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'任职部门',null,0,0,null,-1,'N',null,-1,'workdeptvid',0,'N',1,'N','Y',7,null,0,'workdeptvid','hrbm.bmdata.workdeptvid',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000022P2D','@@@@',0,null,'160150bmfile0003',null,'N',1,7,'bmdata','社保数据',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'任职组织',null,0,0,null,-1,'N',null,-1,'workorgvid',0,'N',1,'N','Y',6,null,0,'workorgvid','hrbm.bmdata.workorgvid',null,'N',0,null,'1001Z710000000022P1M','1001Z710000000022P2B','@@@@',0,null,'160150bmfile0002',null,'N',1,5,'bmdata','社保数据',0,'2017-11-13 18:25:04','N',null,null,null,1,1,'N',1,null,1)
go


insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrbm.bmdata','bmdata',null,'1001Z710000000022P1M','1001AA1000000000GKGI',null,0,0,'160150bmfile0012','bmdata',0,'社保数据','2017-11-13 18:25:05',null,null,null)
go
