
delete pub_query_condition where ( pk_templet in ('0001AA10000000HY6RVL') and (dr=0 or dr is null) )
/

delete pub_query_templet where ( id='0001AA10000000HY6RVL' and (pk_corp='@@@@') and (dr=0 or dr is null) )
/


insert into pub_query_templet(description,devorg,dr,fixcondition,fixquerytree,id,layer,metaclass,model_code,model_name,node_code,parentid,pk_corp,pk_org,resid,ts) values( null,null,0,null,null,'0001AA10000000HY6RVL',0,'2647561e-c913-4684-a64a-60564842d702','60050deptadj','部门调整申请','60050deptadj',null,'@@@@',null,null,'2018-11-03 16:46:40')
/


insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,0,1,null,0,null,null,null,null,null,'pk_deptadj',null,null,'0001AA10000000HY6SND','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '集团',5,1,1,null,0,null,null,null,null,null,'pk_group',null,null,'0001AA10000000HY6TF5','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '组织（包含全局）(所有)',5,2,1,null,0,null,null,null,null,null,'pk_org',null,null,'0001AA10000000HY6U6X','N','Y','N','Y',null,'N','N','N','Y',null,'N','N','N','Y','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,'#mainorg#')
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '业务单元版本',5,3,1,null,0,null,null,null,null,null,'pk_org_v',null,null,'0001AA10000000HY6UYP','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '用户',5,4,1,null,0,null,null,null,null,null,'creator',null,null,'0001AA10000000HY6VQH','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',8,5,1,null,0,null,null,null,null,null,'creationtime',null,null,'0001AA10000000HY6WI9','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '用户',5,6,1,null,0,null,null,null,null,null,'modifier',null,null,'0001AA10000000HY6XA1','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',8,7,1,null,0,null,null,null,null,null,'modifiedtime',null,null,'0001AA10000000HY6Y1T','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,8,1,null,0,null,null,null,null,null,'adj_code',null,null,'0001AA10000000HY6YTL','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( 'HR部门版本',5,9,1,null,0,null,null,null,null,null,'pk_dept_v',null,null,'0001AA10000000HY6ZLD','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',10,10,1,null,0,null,null,null,null,null,'effectivedate',null,null,'0001AA10000000HY70D5','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',4,11,1,null,0,null,null,null,null,null,'iseffective',null,null,'0001AA10000000HY714X','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,12,1,null,0,null,null,null,null,null,'pk_dept',null,null,'0001AA10000000HY71WP','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,13,1,null,0,null,null,null,null,null,'code',null,null,'0001AA10000000HY72OH','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,14,1,null,0,null,null,null,null,null,'name',null,null,'0001AA10000000HY73G9','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,15,1,null,0,null,null,null,null,null,'innercode',null,null,'0001AA10000000HY7481','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '部门HR',5,16,1,null,0,null,null,null,null,null,'pk_fatherorg',null,null,'0001AA10000000HY74ZT','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( 'IM,32d8fdf6-9428-40a2-8201-d10dc0efb3f9',6,17,1,null,0,null,null,null,null,null,'depttype',null,null,'0001AA10000000HY75RL','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@<>@','等于@不等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '部门级别(自定义档案)',5,18,1,null,0,null,null,null,null,null,'deptlevel',null,null,'0001AA10000000HY76JD','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,19,1,null,0,null,null,null,null,null,'deptduty',null,null,'0001AA10000000HY77B5','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',10,20,1,null,0,null,null,null,null,null,'createdate',null,null,'0001AA10000000HY782X','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,21,1,null,0,null,null,null,null,null,'shortname',null,null,'0001AA10000000HY78UP','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,22,1,null,0,null,null,null,null,null,'mnecode',null,null,'0001AA10000000HY79MH','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',4,23,1,null,0,null,null,null,null,null,'hrcanceled',null,null,'0001AA10000000HY7AE9','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',10,24,1,null,0,null,null,null,null,null,'deptcanceldate',null,null,'0001AA10000000HY7B61','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( 'IM,6b533ffa-3e43-4147-8670-ba0f5471fd40',6,25,1,null,0,null,null,null,null,null,'enablestate',null,null,'0001AA10000000HY7BXT','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@<>@','等于@不等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',1,26,1,null,0,null,null,null,null,null,'displayorder',null,null,'0001AA10000000HY7CPL','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( 'IM,28b94d24-6d65-4cc5-b6ac-ca1b638b0da3',6,27,1,null,0,null,null,null,null,null,'dataoriginflag',null,null,'0001AA10000000HY7DHD','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@<>@','等于@不等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',4,28,1,null,0,null,null,null,null,null,'orgtype13',null,null,'0001AA10000000HY7E95','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',4,29,1,null,0,null,null,null,null,null,'orgtype17',null,null,'0001AA10000000HY7F0X','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( 'HR人员',5,30,1,null,0,null,null,null,null,null,'principal',null,null,'0001AA10000000HY7FSP','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,31,1,null,0,null,null,null,null,null,'tel',null,null,'0001AA10000000HY7GKH','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '地址簿',5,32,1,null,0,null,null,null,null,null,'address',null,null,'0001AA10000000HY7HC9','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,33,1,null,0,null,null,null,null,null,'memo',null,null,'0001AA10000000HY7I41','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',4,34,1,null,0,null,null,null,null,null,'islastversion',null,null,'0001AA10000000HY7IVT','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,35,1,null,0,null,null,null,null,null,'def1',null,null,'0001AA10000000HY7JNL','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,36,1,null,0,null,null,null,null,null,'def2',null,null,'0001AA10000000HY7KFD','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,37,1,null,0,null,null,null,null,null,'def3',null,null,'0001AA10000000HY7L75','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,38,1,null,0,null,null,null,null,null,'def4',null,null,'0001AA10000000HY7LYX','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,39,1,null,0,null,null,null,null,null,'def5',null,null,'0001AA10000000HY7MQP','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,40,1,null,0,null,null,null,null,null,'def6',null,null,'0001AA10000000HY7NIH','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,41,1,null,0,null,null,null,null,null,'def7',null,null,'0001AA10000000HY7OA9','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,42,1,null,0,null,null,null,null,null,'def8',null,null,'0001AA10000000HY7P21','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,43,1,null,0,null,null,null,null,null,'def9',null,null,'0001AA10000000HY7PTT','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,44,1,null,0,null,null,null,null,null,'def10',null,null,'0001AA10000000HY7QLL','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,45,1,null,0,null,null,null,null,null,'def11',null,null,'0001AA10000000HY7RDD','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,46,1,null,0,null,null,null,null,null,'def12',null,null,'0001AA10000000HY7S55','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,47,1,null,0,null,null,null,null,null,'def13',null,null,'0001AA10000000HY7SWX','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,48,1,null,0,null,null,null,null,null,'def14',null,null,'0001AA10000000HY7TOP','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,49,1,null,0,null,null,null,null,null,'def15',null,null,'0001AA10000000HY7UGH','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,50,1,null,0,null,null,null,null,null,'def16',null,null,'0001AA10000000HY7V89','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,51,1,null,0,null,null,null,null,null,'def17',null,null,'0001AA10000000HY7W01','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,52,1,null,0,null,null,null,null,null,'def18',null,null,'0001AA10000000HY7WRT','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,53,1,null,0,null,null,null,null,null,'def19',null,null,'0001AA10000000HY7XJL','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,54,1,null,0,null,null,null,null,null,'def20',null,null,'0001AA10000000HY7YBD','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',3,55,0,null,0,null,null,null,null,null,'billdate',null,null,'0001AA10000000HY7Z35','N','Y','N','Y',null,'N','N','N','Y',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001AA10000000HY6RVL',null,null,2,null,null,'2018-11-03 16:46:40',null,'#day(0)#,#day(0)#')
/
