
delete pub_billtemplet_t where ( pk_billtemplet in ('0001ZZ10000000058LCS') and (dr=0 or dr is null) );


delete pub_billtemplet_b where ( pk_billtemplet in ('0001ZZ10000000058LCS') and (dr=0 or dr is null) );


delete pub_billtemplet where ( pk_billtemplet='0001ZZ10000000058LCS' and (bill_templetname='SYSTEM') and (dr=0 or dr is null) );



insert into pub_billtemplet(bill_templetcaption,bill_templetname,devorg,dividerproportion,dr,funccode,layer,metadataclass,model_type,modulecode,nodecode,options,pk_billtemplet,pk_billtypecode,pk_corp,pk_org,resid,shareflag,ts,validateformula) values( '劳健保计算','SYSTEM',null,'0.5369127516778524',0,null,0,'twhr.nhicalc',null,'TWHR','68J61707',null,'0001ZZ10000000058LCS','68J61707','@@@@',null,null,null,'2018-09-13 09:54:47',null);



insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',0,'N',1,'N','Y',2,null,0,'creator','twhr.nhicalc.creator',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LCT','@@@@',2,null,null,null,'N',1,0,'auditInfo','审计信息',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','Y',4,null,0,'creationtime','twhr.nhicalc.creationtime',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LCU','@@@@',2,null,null,null,'N',1,1,'auditInfo','审计信息',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','Y',6,null,0,'modifier','twhr.nhicalc.modifier',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LCV','@@@@',2,null,null,null,'N',1,2,'auditInfo','审计信息',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','Y',8,null,0,'modifiedtime','twhr.nhicalc.modifiedtime',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LCW','@@@@',2,null,null,null,'N',1,3,'auditInfo','审计信息',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_nhicalc',0,'N',1,'N','N',1,null,0,'pk_nhicalc','twhr.nhicalc.pk_nhicalc',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LCX','@@@@',0,null,null,null,'N',0,1,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'rowno',0,'N',1,'N','N',3,null,0,'rowno','twhr.nhicalc.rowno',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LCY','@@@@',0,null,null,null,'N',0,2,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',5,null,0,'pk_group','twhr.nhicalc.pk_group',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LCZ','@@@@',0,null,null,null,'N',0,3,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',7,null,0,'pk_org','twhr.nhicalc.pk_org',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LD0','@@@@',0,'法人组织,code=N',null,null,'N',0,4,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',9,null,0,'pk_org_v','twhr.nhicalc.pk_org_v',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LD1','@@@@',0,null,null,null,'N',0,5,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_psndoc',0,'N',1,'N','Y',10,null,0,'pk_psndoc','twhr.nhicalc.pk_psndoc',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LD2','@@@@',0,null,null,null,'N',1,6,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,1,null,-1,'N',null,-1,'iscalculated',0,'N',1,'N','Y',11,null,0,'iscalculated','twhr.nhicalc.iscalculated',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LD3','@@@@',0,null,null,null,'N',1,11,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,1,null,-1,'N',null,-1,'isaudit',0,'N',1,'N','Y',12,null,0,'isaudit','twhr.nhicalc.isaudit',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LD4','@@@@',0,null,null,null,'N',1,12,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'cyear',0,'N',1,'N','Y',13,null,0,'cyear','twhr.nhicalc.cyear',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LD5','@@@@',0,null,null,null,'N',1,13,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'cperiod',0,'N',1,'N','Y',14,null,0,'cperiod','twhr.nhicalc.cperiod',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LD6','@@@@',0,null,null,null,'N',1,14,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'begindate',0,'N',1,'N','Y',15,null,0,'begindate','twhr.nhicalc.begindate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LD7','@@@@',0,null,null,null,'N',1,15,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'enddate',0,'N',1,'N','Y',16,null,0,'enddate','twhr.nhicalc.enddate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LD8','@@@@',0,null,null,null,'N',1,16,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'oldlaborsalary',0,'N',1,'N','N',17,null,0,'oldlaborsalary','twhr.nhicalc.oldlaborsalary',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LD9','@@@@',0,null,null,null,'N',0,17,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'laborsalary',0,'N',1,'N','N',18,null,0,'laborsalary','twhr.nhicalc.laborsalary',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDA','@@@@',0,null,null,null,'N',0,18,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'oldlaborrange',0,'N',1,'N','Y',19,null,0,'oldlaborrange','twhr.nhicalc.oldlaborrange',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDB','@@@@',0,null,null,null,'N',1,19,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'laborrange',0,'N',1,'N','N',20,null,0,'laborrange','twhr.nhicalc.laborrange',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDC','@@@@',0,null,null,null,'N',0,20,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'oldretirerange',0,'N',1,'N','Y',21,null,0,'oldretirerange','twhr.nhicalc.oldretirerange',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDD','@@@@',0,null,null,null,'N',1,21,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'retirerange',0,'N',1,'N','N',22,null,0,'retirerange','twhr.nhicalc.retirerange',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDE','@@@@',0,null,null,null,'N',0,22,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'oldhealthsalary',0,'N',1,'N','Y',23,null,0,'oldhealthsalary','twhr.nhicalc.oldhealthsalary',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDF','@@@@',0,null,null,null,'N',1,23,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'healthsalary',0,'N',1,'N','N',24,null,0,'healthsalary','twhr.nhicalc.healthsalary',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDG','@@@@',0,null,null,null,'N',0,24,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'oldhealthrange',0,'N',1,'N','Y',25,null,0,'oldhealthrange','twhr.nhicalc.oldhealthrange',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDH','@@@@',0,null,null,null,'N',1,25,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'healthrange',0,'N',1,'N','N',26,null,0,'healthrange','twhr.nhicalc.healthrange',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDI','@@@@',0,null,null,null,'N',0,26,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'labortsmd5',0,'N',1,'N','N',27,null,0,'labortsmd5','twhr.nhicalc.labortsmd5',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDJ','@@@@',0,null,null,null,'N',0,27,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'healthtsmd5',0,'N',1,'N','N',28,null,0,'healthtsmd5','twhr.nhicalc.healthtsmd5',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDK','@@@@',0,null,null,null,'N',0,28,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,1,null,-1,'N',null,-1,'includelastmonth',0,'N',1,'N','Y',29,null,0,'includelastmonth','twhr.nhicalc.includelastmonth',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDL','@@@@',0,null,null,null,'N',1,29,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthlabordays',0,'N',1,'N','Y',30,null,0,'lastmonthlabordays','twhr.nhicalc.lastmonthlabordays',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDM','@@@@',0,null,null,null,'N',1,30,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthretirehirer',0,'N',1,'N','Y',31,null,0,'lastmonthretirehirer','twhr.nhicalc.lastmonthretirehirer',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDN','@@@@',0,null,null,null,'N',1,31,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthretirestuff',0,'N',1,'N','Y',32,null,0,'lastmonthretirestuff','twhr.nhicalc.lastmonthretirestuff',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDO','@@@@',0,null,null,null,'N',1,32,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthlaborhirer',0,'N',1,'N','Y',33,null,0,'lastmonthlaborhirer','twhr.nhicalc.lastmonthlaborhirer',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDP','@@@@',0,null,null,null,'N',1,33,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthllaborstuff',0,'N',1,'N','Y',34,null,0,'lastmonthllaborstuff','twhr.nhicalc.lastmonthllaborstuff',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDQ','@@@@',0,null,null,null,'N',1,34,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthemphirer',0,'N',1,'N','Y',35,null,0,'lastmonthemphirer','twhr.nhicalc.lastmonthemphirer',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDR','@@@@',0,null,null,null,'N',1,35,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthempstuff',0,'N',1,'N','Y',36,null,0,'lastmonthempstuff','twhr.nhicalc.lastmonthempstuff',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDS','@@@@',0,null,null,null,'N',1,36,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthdishirer',0,'N',1,'N','Y',37,null,0,'lastmonthdishirer','twhr.nhicalc.lastmonthdishirer',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDT','@@@@',0,null,null,null,'N',1,37,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthdisstuff',0,'N',1,'N','Y',38,null,0,'lastmonthdisstuff','twhr.nhicalc.lastmonthdisstuff',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDU','@@@@',0,null,null,null,'N',1,38,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthcomhirer',0,'N',1,'N','Y',39,null,0,'lastmonthcomhirer','twhr.nhicalc.lastmonthcomhirer',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDV','@@@@',0,null,null,null,'N',1,39,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthcomstuff',0,'N',1,'N','Y',40,null,0,'lastmonthcomstuff','twhr.nhicalc.lastmonthcomstuff',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDW','@@@@',0,null,null,null,'N',1,40,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'labordays',0,'N',1,'N','Y',41,null,0,'labordays','twhr.nhicalc.labordays',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDX','@@@@',0,null,null,null,'N',1,41,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'retirehirer',0,'N',1,'N','Y',42,null,0,'retirehirer','twhr.nhicalc.retirehirer',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDY','@@@@',0,null,null,null,'N',1,42,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'retirestuff',0,'N',1,'N','Y',43,null,0,'retirestuff','twhr.nhicalc.retirestuff',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LDZ','@@@@',0,null,null,null,'N',1,43,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'laborhirer',0,'N',1,'N','Y',44,null,0,'laborhirer','twhr.nhicalc.laborhirer',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LE0','@@@@',0,null,null,null,'N',1,44,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'laborstuff',0,'N',1,'N','Y',45,null,0,'laborstuff','twhr.nhicalc.laborstuff',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LE1','@@@@',0,null,null,null,'N',1,45,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'emphirer',0,'N',1,'N','Y',46,null,0,'emphirer','twhr.nhicalc.emphirer',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LE2','@@@@',0,null,null,null,'N',1,46,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'empstuff',0,'N',1,'N','Y',47,null,0,'empstuff','twhr.nhicalc.empstuff',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LE3','@@@@',0,null,null,null,'N',1,47,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'dishirer',0,'N',1,'N','Y',48,null,0,'dishirer','twhr.nhicalc.dishirer',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LE4','@@@@',0,null,null,null,'N',1,48,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'disstuff',0,'N',1,'N','Y',49,null,0,'disstuff','twhr.nhicalc.disstuff',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LE5','@@@@',0,null,null,null,'N',1,49,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'comhirer',0,'N',1,'N','Y',50,null,0,'comhirer','twhr.nhicalc.comhirer',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LE6','@@@@',0,null,null,null,'N',1,50,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'comstuff',0,'N',1,'N','Y',51,null,0,'comstuff','twhr.nhicalc.comstuff',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LE7','@@@@',0,null,null,null,'N',1,51,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'disablegrade',0,'N',1,'N','Y',52,null,0,'disablegrade','twhr.nhicalc.disablegrade',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LE8','@@@@',0,null,null,null,'N',1,52,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'labortype',0,'N',1,'N','Y',53,null,0,'labortype','twhr.nhicalc.labortype',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LE9','@@@@',0,null,null,null,'N',1,53,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'comrate',0,'N',1,'N','Y',54,null,0,'comrate','twhr.nhicalc.comrate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEA','@@@@',0,null,null,null,'N',1,54,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'comstuffrate',0,'N',1,'N','Y',55,null,0,'comstuffrate','twhr.nhicalc.comstuffrate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEB','@@@@',0,null,null,null,'N',1,55,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'comhirerrate',0,'N',1,'N','Y',56,null,0,'comhirerrate','twhr.nhicalc.comhirerrate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEC','@@@@',0,null,null,null,'N',1,56,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'disrate',0,'N',1,'N','Y',57,null,0,'disrate','twhr.nhicalc.disrate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LED','@@@@',0,null,null,null,'N',1,57,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'disstuffrate',0,'N',1,'N','Y',58,null,0,'disstuffrate','twhr.nhicalc.disstuffrate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEE','@@@@',0,null,null,null,'N',1,58,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'dishirerrate',0,'N',1,'N','Y',59,null,0,'dishirerrate','twhr.nhicalc.dishirerrate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEF','@@@@',0,null,null,null,'N',1,59,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'emprate',0,'N',1,'N','Y',60,null,0,'emprate','twhr.nhicalc.emprate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEG','@@@@',0,null,null,null,'N',1,60,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'empstuffrate',0,'N',1,'N','Y',61,null,0,'empstuffrate','twhr.nhicalc.empstuffrate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEH','@@@@',0,null,null,null,'N',1,61,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'emphirerrate',0,'N',1,'N','Y',62,null,0,'emphirerrate','twhr.nhicalc.emphirerrate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEI','@@@@',0,null,null,null,'N',1,62,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'retirestuffrate',0,'N',1,'N','Y',63,null,0,'retirestuffrate','twhr.nhicalc.retirestuffrate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEJ','@@@@',0,null,null,null,'N',1,63,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'retirehirerrate',0,'N',1,'N','Y',64,null,0,'retirehirerrate','twhr.nhicalc.retirehirerrate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEK','@@@@',0,null,null,null,'N',1,64,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'laborsalaryextend',0,'N',1,'N','Y',65,null,0,'laborsalaryextend','twhr.nhicalc.laborsalaryextend',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEL','@@@@',0,null,null,null,'N',1,65,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'healthsalaryextend',0,'N',1,'N','Y',66,null,0,'healthsalaryextend','twhr.nhicalc.healthsalaryextend',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEM','@@@@',0,null,null,null,'N',1,66,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'dependentcount',0,'N',1,'N','Y',67,null,0,'dependentcount','twhr.nhicalc.dependentcount',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEN','@@@@',0,null,null,null,'N',1,67,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'healthstuff',0,'N',1,'N','Y',68,null,0,'healthstuff','twhr.nhicalc.healthstuff',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEO','@@@@',0,null,null,null,'N',1,68,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'healthhirer',0,'N',1,'N','Y',69,null,0,'healthhirer','twhr.nhicalc.healthhirer',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEP','@@@@',0,null,null,null,'N',1,69,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'healthgov',0,'N',1,'N','Y',70,null,0,'healthgov','twhr.nhicalc.healthgov',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEQ','@@@@',0,null,null,null,'N',1,70,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'healthstuffact',0,'N',1,'N','Y',71,null,0,'healthstuffact','twhr.nhicalc.healthstuffact',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LER','@@@@',0,null,null,null,'N',1,71,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'repayfund',0,'N',1,'N','Y',72,null,0,'repayfund','twhr.nhicalc.repayfund',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LES','@@@@',0,null,null,null,'N',1,72,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthrepayfund',0,'N',1,'N','Y',73,null,0,'lastmonthrepayfund','twhr.nhicalc.lastmonthrepayfund',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LET','@@@@',0,null,null,null,'N',1,73,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthhealthstuff',0,'N',1,'N','Y',74,null,0,'lastmonthhealthstuff','twhr.nhicalc.lastmonthhealthstuff',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEU','@@@@',0,null,null,null,'N',1,74,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthhealthhirer',0,'N',1,'N','Y',75,null,0,'lastmonthhealthhirer','twhr.nhicalc.lastmonthhealthhirer',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEV','@@@@',0,null,null,null,'N',1,75,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthhealthgov',0,'N',1,'N','Y',76,null,0,'lastmonthhealthgov','twhr.nhicalc.lastmonthhealthgov',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEW','@@@@',0,null,null,null,'N',1,76,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthhealthstuffact',0,'N',1,'N','Y',77,null,0,'lastmonthhealthstuffact','twhr.nhicalc.lastmonthhealthstuffact',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEX','@@@@',0,null,null,null,'N',1,77,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'retiredays',0,'N',1,'N','Y',78,null,0,'retiredays','twhr.nhicalc.retiredays',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEY','@@@@',0,null,null,null,'N',1,78,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lastmonthretiredays',0,'N',1,'N','Y',79,null,0,'lastmonthretiredays','twhr.nhicalc.lastmonthretiredays',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LEZ','@@@@',0,null,null,null,'N',1,79,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_corp',0,'N',1,'N','Y',0,null,0,'pk_corp','twhr.nhicalc.pk_corp',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LF0','@@@@',0,null,null,null,'N',1,0,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'healthpersamount',0,'N',1,'N','Y',80,null,0,'healthpersamount','twhr.nhicalc.healthpersamount',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LF1','@@@@',0,null,null,null,'N',1,80,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'healthcommitamount',0,'N',1,'N','Y',81,null,0,'healthcommitamount','twhr.nhicalc.healthcommitamount',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LF2','@@@@',0,null,null,null,'N',1,81,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'billdate',0,'N',1,'N','N',82,null,0,'billdate','twhr.nhicalc.billdate',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LF3','@@@@',0,null,null,null,'N',0,82,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'biiltype',0,'N',1,'N','N',83,null,0,'biiltype','twhr.nhicalc.biiltype',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LF4','@@@@',0,null,null,null,'N',0,83,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',84,null,0,'ts','twhr.nhicalc.ts',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LF5','@@@@',0,null,null,null,'N',0,84,'nhicalc','劳健保计算',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_epyfamily',0,'N',1,'N','N',0,null,0,'pk_epyfamily','twhr.epyfamily.pk_epyfamily',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LF6','@@@@',1,null,null,null,'N',0,0,'pk_epyfamily','员工眷属',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'rowno',0,'N',1,'N','Y',1,null,0,'rowno','twhr.epyfamily.rowno',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LF7','@@@@',1,null,null,null,'N',1,1,'pk_epyfamily','员工眷属',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_psndoc',0,'N',1,'N','Y',2,null,0,'pk_psndoc','twhr.epyfamily.pk_psndoc',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LF8','@@@@',1,null,null,null,'N',1,2,'pk_epyfamily','员工眷属',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_psndoc_sub',0,'N',1,'N','Y',3,null,0,'pk_psndoc_sub','twhr.epyfamily.pk_psndoc_sub',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LF9','@@@@',1,null,null,null,'N',1,3,'pk_epyfamily','员工眷属',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'code',0,'N',1,'N','Y',4,null,0,'code','twhr.epyfamily.code',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LFA','@@@@',1,null,null,null,'N',1,4,'pk_epyfamily','员工眷属',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'healthamount',0,'N',1,'N','Y',5,null,0,'healthamount','twhr.epyfamily.healthamount',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LFB','@@@@',1,null,null,null,'N',1,5,'pk_epyfamily','员工眷属',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',6,null,0,'ts','twhr.epyfamily.ts',null,'N',0,null,'0001ZZ10000000058LCS','0001ZZ10000000058LFC','@@@@',1,null,null,null,'N',0,6,'pk_epyfamily','员工眷属',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,100);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psndoc',-1,'pk_psndoc.hi_psnjob.pk_post',null,'N',1,'N','Y',88,null,0,'hi_psnjob.pk_post','hrhi.hi_psnjob.pk_post',null,'N',0,null,'0001ZZ10000000058LCS','1001ZZ1000000000KD23',null,0,null,null,null,'N',1,10,'nhicalc','nhicalc',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psndoc',-1,'pk_psndoc.hi_psnjob.clerkcode',null,'N',1,'N','Y',85,null,0,'hi_psnjob.clerkcode','hrhi.hi_psnjob.clerkcode',null,'N',0,null,'0001ZZ10000000058LCS','1001ZZ1000000000KD24',null,0,null,null,null,'N',1,7,'nhicalc','nhicalc',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psndoc',-1,'pk_psndoc.name',null,'N',1,'N','Y',86,null,0,'name','hrhi.bd_psndoc.name',null,'N',0,null,'0001ZZ10000000058LCS','1001ZZ1000000000KD25',null,0,null,null,null,'N',1,8,'nhicalc','nhicalc',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psndoc',-1,'pk_psndoc.hi_psnjob.pk_dept',null,'N',1,'N','Y',87,null,0,'hi_psnjob.pk_dept','hrhi.hi_psnjob.pk_dept',null,'N',0,null,'0001ZZ10000000058LCS','1001ZZ1000000000KD26',null,0,null,null,null,'N',1,9,'nhicalc','nhicalc',0,'2018-09-13 09:54:47','N',null,null,null,1,1,'N',1,null,1);



insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,null,null,null,'0001ZZ10000000058LCS','1001ZZ1000000000KD2A',null,2,null,null,'auditInfo',0,'审计信息','2018-09-13 09:54:48',null,null,null);

insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'twhr.nhicalc','nhicalc',null,'0001ZZ10000000058LCS','1001ZZ1000000000KD2B',null,0,0,null,'nhicalc',0,'劳健保计算','2018-09-13 09:54:48',null,null,null);

insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'twhr.epyfamily','pk_epyfamily',null,'0001ZZ10000000058LCS','1001ZZ1000000000KD2C',null,1,null,null,'pk_epyfamily',0,'员工眷属','2018-09-13 09:54:48',null,null,null);

/
