insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_deptadj',0,'N',1,'N','N',1,null,0,'pk_deptadj','hrjf.deptadj.pk_deptadj',null,'N',0,null,'0001AA10000000HY5HKX','0001AA10000000HY5ICP','@@@@',0,null,null,null,'N',0,1,'deptadj','部门调整申请',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'adj_code',0,'N',1,'N','Y',9,null,0,'adj_code','hrjf.deptadj.adj_code',null,'N',0,null,'0001AA10000000HY5HKX','0001AA10000000HY5OIX','@@@@',0,null,null,null,'N',1,2,'deptadj','部门调整申请',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'effectivedate',0,'N',1,'N','Y',11,null,0,'effectivedate','hrjf.deptadj.effectivedate',null,'N',0,null,'0001AA10000000HY5HKX','0001AA10000000HY5Q2H','@@@@',0,null,null,null,'N',1,3,'deptadj','部门调整申请',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'billdate',0,'N',1,'N','Y',56,null,0,'billdate','hrjf.deptadj.billdate',null,'N',1,null,'0001AA10000000HY5HKX','0001AA10000000HY6OSH','@@@@',0,null,null,null,'N',1,4,'deptadj','部门调整申请',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,0,'部门调整前主键',null,0,1,null,-1,'N',null,20,'部门调整前主键',null,'N',1,'N','N',1,null,0,null,null,null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PL8UP',null,0,null,null,null,'N',0,1,'001','部门调整前信息',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'principal',null,'N',1,'N','Y',8,null,0,'principal','hrjf.deptadj.principal',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PLCPL',null,0,null,null,null,'N',1,8,'002','002',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'displayorder',null,'N',1,'N','Y',7,null,0,'displayorder','hrjf.deptadj.displayorder',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PLDHD',null,0,null,null,null,'N',1,7,'002','002',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_fatherorg',null,'N',1,'N','Y',4,null,0,'pk_fatherorg','hrjf.deptadj.pk_fatherorg',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PLE95',null,0,null,null,null,'N',1,4,'002','002',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'code',null,'N',1,'N','Y',2,null,0,'code','hrjf.deptadj.code',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PLF0X',null,0,null,null,null,'N',1,2,'002','002',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,0,'部门调整后主键',null,0,1,null,-1,'N',null,20,'部门调整后主键',null,'N',1,'N','N',1,null,0,null,null,null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PLFSP',null,0,null,null,null,'N',0,1,'002','部门调整后信息',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'mnecode',null,'N',1,'N','Y',6,null,0,'mnecode','hrjf.deptadj.mnecode',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PLGKH',null,0,null,null,null,'N',1,6,'002','002',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'shortname',null,'N',1,'N','Y',5,null,0,'shortname','hrjf.deptadj.shortname',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PLHC9',null,0,null,null,null,'N',1,5,'002','002',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'name',null,'N',1,'N','Y',3,null,0,'name','hrjf.deptadj.name',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PLI41',null,0,null,null,null,'N',1,3,'002','002',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',5,null,0,'pk_org','hrjf.deptadj.pk_org',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PLW01','@@@@',0,null,null,null,'N',1,5,'deptadj','deptadj',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.pk_fatherorg',0,'N',1,'N','Y',4,null,0,'pk_vid.pk_fatherorg','uap.dept_v.pk_fatherorg',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PO5SH','@@@@',0,null,null,null,'N',1,4,'001','001',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.displayorder',0,'N',1,'N','Y',7,null,0,'pk_vid.displayorder','uap.dept_v.displayorder',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PO6K9','@@@@',0,null,null,null,'N',1,7,'001','001',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.name',0,'N',1,'N','Y',3,null,0,'pk_vid.name','uap.dept_v.name',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PO7C1','@@@@',0,null,null,null,'N',1,3,'001','001',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.mnecode',0,'N',1,'N','Y',6,null,0,'pk_vid.mnecode','uap.dept_v.mnecode',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PO83T','@@@@',0,null,null,null,'N',1,6,'001','001',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.code',0,'N',1,'N','Y',2,null,0,'pk_vid.code','uap.dept_v.code',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PO8VL','@@@@',0,null,null,null,'N',1,2,'001','001',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_dept',0,'N',1,'N','Y',6,null,0,'pk_dept','hrjf.deptadj.pk_dept',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002PO9ND','@@@@',0,null,null,null,'N',1,6,'deptadj','deptadj',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.shortname',0,'N',1,'N','Y',5,null,0,'pk_vid.shortname','uap.dept_v.shortname',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002POAF5','@@@@',0,null,null,null,'N',1,5,'001','001',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_dept',-1,'pk_dept.pk_vid.principal',0,'N',1,'N','Y',8,null,0,'pk_vid.principal','uap.dept_v.principal',null,'N',0,null,'0001AA10000000HY5HKX','1001AA100000002POB6X','@@@@',0,null,null,null,'N',1,8,'001','001',0,'2018-11-04 19:05:49','N',null,null,null,1,1,'N',1,null,1)
/
