create table tbm_leaveplan (
pk_leaveplan char(20) NOT NULL,
pk_group varchar(20)  NULL,
pk_org varchar(20) default '~' NULL,
pk_org_v varchar(20) default '~' NULL,
pk_psndoc varchar(20) default '~' NULL,
pk_dept varchar(20) default '~' NULL,
pk_dept_v varchar(20) default '~' NULL,
pk_leavetype varchar(20) default '~' NULL,
begindate char(10) NULL,
enddate char(10) NULL,
enableddays int NULL,
useddays int NULL,
remaineddays int NULL,
isattachment char(1) NULL,
iscontinuous char(1) NULL,
lastmaketime char(19) NULL,
billmaker varchar(50) NULL,
pkorg varchar(50) NULL,
creator varchar(20) default '~' NULL,
creationtime char(19) NULL,
modifier varchar(20) default '~' NULL,
modifiedtime char(19) NULL,
name varchar(50) NULL,
code varchar(50) NULL,
dbilldate varchar(19) NULL,
def1 varchar(101) NULL,
def2 varchar(101) NULL,
def3 varchar(101) NULL,
def4 varchar(101) NULL,
def5 varchar(101) NULL,
def6 varchar(101) NULL,
def7 varchar(101) NULL,
def8 varchar(101) NULL,
def9 varchar(101) NULL,
def10 varchar(101) NULL,
def11 varchar(101) NULL,
def12 varchar(101) NULL,
def13 varchar(101) NULL,
def14 varchar(101) NULL,
def15 varchar(101) NULL,
def16 varchar(101) NULL,
def17 varchar(101) NULL,
def18 varchar(101) NULL,
def19 varchar(101) NULL,
def20 varchar(101) NULL,
id char(20)  NULL,
maketime char(19)  NULL,
rowno varchar(50) NULL,
CONSTRAINT PK_TBM_LEAVEPLAN PRIMARY KEY (pk_leaveplan),
ts char(19) NULL,
dr smallint default 0 
)


