
delete pub_query_condition where ( pk_templet in ('0001ZZ10000000001GQV') and (dr=0 or dr is null) );


delete pub_query_templet where ( id='0001ZZ10000000001GQV' and (pk_corp='@@@@') and (dr=0 or dr is null) );



insert into pub_query_templet(description,devorg,dr,fixcondition,fixquerytree,id,layer,metaclass,model_code,model_name,node_code,parentid,pk_corp,pk_org,resid,ts) values( null,null,null,null,null,'0001ZZ10000000001GQV',0,'c1aba202-c319-41d7-9225-b4622f59ee93','68J61025','級距表','68J61025',null,'@@@@',null,null,'2018-07-26 15:45:32');



insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,0,1,null,null,null,null,null,null,null,'pk_rangetable',null,null,'0001ZZ10000000001GQW','N','Y','N','N','N','N','N','N','N','N','N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2016-10-25 23:59:35','N',null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( 'IM,7cf8833e-118f-47ca-af94-3c1e0a0d4a02',6,1,1,null,0,null,null,null,null,null,'tabletype',null,null,'0001ZZ10000000001GQX','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@<>@','等于@不等于@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2014-07-29 17:21:25',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',3,2,0,null,null,null,null,null,null,null,'doctime',null,null,'0001ZZ10000000001GQY','N','Y','N','N','N','N','N','N','N','N','N','N','N','N','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2016-10-26 00:04:21','N',null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,3,1,null,null,null,null,null,null,null,'docno',null,null,'0001ZZ10000000001GQZ','N','Y','N','N','N','N','N','N','N','N','N','N','N','N','N',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2016-10-25 23:59:35','N',null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',3,4,1,null,null,null,null,null,null,null,'startdate',null,null,'0001ZZ10000000001GR0','N','Y','N','Y','N','N','N','N','N','N','N','N','N','Y','Y',null,'Y',9999,null,'<=@>=@','小于等于@大于等于@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2018-07-26 15:45:32','N','#day(0)#,#day(0)#');

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',3,5,1,null,null,null,null,null,null,null,'enddate',null,null,'0001ZZ10000000001GR1','N','Y','N','Y','N','N','N','N','N','N','N','N','N','Y','Y',null,'Y',9999,null,'>=@<=@','大于等于@小于等于@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2018-07-26 15:45:32','N','#day(0)#,#day(0)#');

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,6,1,null,0,null,null,null,null,null,'pk_rangeline',null,null,'0001ZZ10000000001GR2','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2014-07-29 17:21:25',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '集团',5,7,1,null,null,null,null,null,null,null,'pk_group',null,null,'0001ZZ10000000001GR3','N','Y','N','N','N','N','N','N','N','N','N','N','N','N','N',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2016-10-26 00:01:30','N',null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '人力资源组织',5,8,1,null,null,null,null,null,null,null,'pk_org',null,null,'0001ZZ10000000001GR4','N','Y','N','N','N','N','N','N','N','N','N','N','N','Y','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2018-07-26 10:53:44','N','#mainorg#');

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '人力资源组织版本',5,9,1,null,null,null,null,null,null,null,'pk_org_v',null,null,'0001ZZ10000000001GR5','N','Y','N','N','N','N','N','N','N','N','N','N','N','N','N',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2016-10-25 23:59:35','N',null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '用户',5,10,1,null,null,null,null,null,null,null,'creator',null,null,'0001ZZ10000000001GR6','N','Y','N','N','N','N','N','N','N','N','N','N','N','N','N',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2016-10-25 23:59:35','N',null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',8,11,1,null,null,null,null,null,null,null,'creationtime',null,null,'0001ZZ10000000001GR7','N','Y','N','N','N','N','N','N','N','N','N','N','N','Y','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2016-10-25 23:59:35','N',null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '用户',5,12,1,null,null,null,null,null,null,null,'modifier',null,null,'0001ZZ10000000001GR8','N','Y','N','N','N','N','N','N','N','N','N','N','N','N','N',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2016-10-25 23:59:35','N',null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',8,13,1,null,null,null,null,null,null,null,'modifiedtime',null,null,'0001ZZ10000000001GR9','N','Y','N','N','N','N','N','N','N','N','N','N','N','Y','N',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000001GQV',null,null,2,null,null,'2016-10-25 23:59:35','N',null);

