/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ta.leave;
	



/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:${vmObject.createdDate}
 * @author 
 * @version NCPrj ??
 */

public class LeaveSplitCalVO {
	
	
	private nc.vo.pub.lang.UFDouble leavehour;
	private java.lang.String pk_org ;
	private java.lang.String pk_psndoc ;
	private java.lang.String pk_leavetype;
	private nc.vo.pub.lang.UFLiteralDate leavebegindate;
	private nc.vo.pub.lang.UFLiteralDate leaveenddate;
	private nc.vo.pub.lang.UFDateTime approve_time;
	public nc.vo.pub.lang.UFDouble getLeavehour() {
		return leavehour;
	}
	public void setLeavehour(nc.vo.pub.lang.UFDouble leavehour) {
		this.leavehour = leavehour;
	}
	public java.lang.String getPk_org() {
		return pk_org;
	}
	public void setPk_org(java.lang.String pk_org) {
		this.pk_org = pk_org;
	}
	public java.lang.String getPk_psndoc() {
		return pk_psndoc;
	}
	public void setPk_psndoc(java.lang.String pk_psndoc) {
		this.pk_psndoc = pk_psndoc;
	}
	public java.lang.String getPk_leavetype() {
		return pk_leavetype;
	}
	public void setPk_leavetype(java.lang.String pk_leavetype) {
		this.pk_leavetype = pk_leavetype;
	}
	
	public nc.vo.pub.lang.UFLiteralDate getLeavebegindate() {
		return leavebegindate;
	}
	public void setLeavebegindate(nc.vo.pub.lang.UFLiteralDate leavebegindate) {
		this.leavebegindate = leavebegindate;
	}
	
	public nc.vo.pub.lang.UFLiteralDate getLeaveenddate() {
		return leaveenddate;
	}
	public void setLeaveenddate(nc.vo.pub.lang.UFLiteralDate leaveenddate) {
		this.leaveenddate = leaveenddate;
	}
	
	public nc.vo.pub.lang.UFDateTime getApprove_time() {
		return approve_time;
	}
	public void setApprove_time(nc.vo.pub.lang.UFDateTime approve_time) {
		this.approve_time = approve_time;
	}
	
	
	
	
			
	
} 
