
delete pub_billtemplet_t where ( pk_billtemplet in ('0001AA10000000004HAC') and (dr=0 or dr is null) )
go

delete pub_billtemplet_b where ( pk_billtemplet in ('0001AA10000000004HAC') and (dr=0 or dr is null) )
go

delete pub_billtemplet where ( pk_billtemplet='0001AA10000000004HAC' and (bill_templetname='SYSTEM') and (dr=0 or dr is null) )
go


insert into pub_billtemplet(bill_templetcaption,bill_templetname,devorg,dividerproportion,dr,funccode,layer,metadataclass,model_type,modulecode,nodecode,options,pk_billtemplet,pk_billtypecode,pk_corp,pk_org,resid,shareflag,ts,validateformula) values( '专案薪资','SYSTEM',null,null,0,null,0,'hrwa.projsalary',null,'HRWA','60130projsalary',null,'0001AA10000000004HAC','60130pjsa','@@@@',null,null,null,'2017-10-31 18:02:18',null)
go


insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def13',0,'N',1,'N','N',26,null,0,'def13','hrwa.projsalary.def13',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HB7','@@@@',0,null,null,null,'N',0,26,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def14',0,'N',1,'N','N',27,null,0,'def14','hrwa.projsalary.def14',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HB8','@@@@',0,null,null,null,'N',0,27,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def15',0,'N',1,'N','N',28,null,0,'def15','hrwa.projsalary.def15',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HB9','@@@@',0,null,null,null,'N',0,28,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def16',0,'N',1,'N','N',29,null,0,'def16','hrwa.projsalary.def16',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBA','@@@@',0,null,null,null,'N',0,29,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def17',0,'N',1,'N','N',30,null,0,'def17','hrwa.projsalary.def17',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBB','@@@@',0,null,null,null,'N',0,30,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def18',0,'N',1,'N','N',31,null,0,'def18','hrwa.projsalary.def18',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBC','@@@@',0,null,null,null,'N',0,31,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def19',0,'N',1,'N','N',32,null,0,'def19','hrwa.projsalary.def19',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBD','@@@@',0,null,null,null,'N',0,32,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def20',0,'N',1,'N','N',33,null,0,'def20','hrwa.projsalary.def20',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBE','@@@@',0,null,null,null,'N',0,33,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'cbilltypeid',0,'N',1,'N','N',40,null,0,'cbilltypeid','hrwa.projsalary.cbilltypeid',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBF','@@@@',0,null,null,null,'N',0,40,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ctrantypeid',0,'N',1,'N','N',41,null,0,'ctrantypeid','hrwa.projsalary.ctrantypeid',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBG','@@@@',0,null,null,null,'N',0,41,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'vtrantypecode',0,'N',1,'N','N',42,null,0,'vtrantypecode','hrwa.projsalary.vtrantypecode',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBH','@@@@',0,null,null,null,'N',0,42,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'cbiztypeid',0,'N',1,'N','N',43,null,0,'cbiztypeid','hrwa.projsalary.cbiztypeid',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBI','@@@@',0,null,null,null,'N',0,43,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'approver',0,'N',1,'N','N',44,null,0,'approver','hrwa.projsalary.approver',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBJ','@@@@',0,null,null,null,'N',0,44,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'taudittime',0,'N',1,'N','N',45,null,0,'taudittime','hrwa.projsalary.taudittime',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBK','@@@@',0,null,null,null,'N',0,45,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'vapprovenote',0,'N',1,'N','N',46,null,0,'vapprovenote','hrwa.projsalary.vapprovenote',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBL','@@@@',0,null,null,null,'N',0,46,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'1',0,1,null,-1,'N',null,-1,'fstatusflag',0,'N',1,'N','N',47,null,0,'fstatusflag','hrwa.projsalary.fstatusflag',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBM','@@@@',0,null,null,null,'N',0,47,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',48,null,0,'ts','hrwa.projsalary.ts',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HBN','@@@@',0,null,null,null,'N',0,48,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def12',0,'N',1,'N','N',25,null,0,'def12','hrwa.projsalary.def12',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HB6','@@@@',0,null,null,null,'N',0,25,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def11',0,'N',1,'N','N',24,null,0,'def11','hrwa.projsalary.def11',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HB5','@@@@',0,null,null,null,'N',0,24,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def10',0,'N',1,'N','N',23,null,0,'def10','hrwa.projsalary.def10',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HB4','@@@@',0,null,null,null,'N',0,23,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def9',0,'N',1,'N','N',22,null,0,'def9','hrwa.projsalary.def9',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HB3','@@@@',0,null,null,null,'N',0,22,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def8',0,'N',1,'N','N',21,null,0,'def8','hrwa.projsalary.def8',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HB2','@@@@',0,null,null,null,'N',0,21,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def7',0,'N',1,'N','N',20,null,0,'def7','hrwa.projsalary.def7',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HB1','@@@@',0,null,null,null,'N',0,20,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def6',0,'N',1,'N','N',19,null,0,'def6','hrwa.projsalary.def6',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HB0','@@@@',0,null,null,null,'N',0,19,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def5',0,'N',1,'N','N',18,null,0,'def5','hrwa.projsalary.def5',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAZ','@@@@',0,null,null,null,'N',0,18,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def4',0,'N',1,'N','N',17,null,0,'def4','hrwa.projsalary.def4',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAY','@@@@',0,null,null,null,'N',0,17,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def3',0,'N',1,'N','N',16,null,0,'def3','hrwa.projsalary.def3',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAX','@@@@',0,null,null,null,'N',0,16,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'专案代码',null,0,0,null,-1,'N',null,-1,'def2',0,'N',1,'N','Y',12,'def2->getcolvalue( "bd_defdoc", "code", "pk_defdoc", pk_project);',0,'def2','hrwa.projsalary.def2',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAW','@@@@',0,'BS000010000100001001','160130projsalary-00001',null,'N',1,12,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'专案名称',null,0,1,'pk_project->def1;def2->getcolvalue( "bd_defdoc", "code", "pk_defdoc", pk_project);',-1,'N',null,-1,'def1',0,'N',1,'N','Y',13,null,0,'def1','hrwa.projsalary.def1',null,'N',1,null,'0001AA10000000004HAC','0001AA10000000004HAV','@@@@',0,'1001A110000000002P11:指定專案代碼維護(自定义档案),code=Y','160130projsalary-00002',null,'N',1,13,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'salaryamt',0,'N',1,'N','Y',15,null,0,'salaryamt','hrwa.projsalary.salaryamt',null,'N',1,null,'0001AA10000000004HAC','0001AA10000000004HAU','@@@@',0,'2,-100000000000000000000.00,100000000000000000000.00',null,null,'N',1,15,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_classitem',0,'N',1,'N','Y',14,null,0,'pk_classitem','hrwa.projsalary.pk_classitem',null,'N',1,null,'0001AA10000000004HAC','0001AA10000000004HAT','@@@@',0,null,null,null,'N',1,14,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_project',0,'N',1,'N','N',11,null,0,'pk_project','hrwa.projsalary.pk_project',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAS','@@@@',0,null,null,null,'N',0,11,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_psndoc',0,'N',1,'N','N',9,null,0,'pk_psndoc','hrwa.projsalary.pk_psndoc',null,'N',1,null,'0001AA10000000004HAC','0001AA10000000004HAR','@@@@',0,null,null,null,'N',1,9,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'cperiod',0,'N',1,'N','N',4,null,0,'cperiod','hrwa.projsalary.cperiod',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAQ','@@@@',0,null,null,null,'N',0,4,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_wa_calss',0,'N',1,'N','N',3,null,0,'pk_wa_calss','hrwa.projsalary.pk_wa_calss',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAP','@@@@',0,null,null,null,'N',0,3,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','N',39,null,0,'modifiedtime','hrwa.projsalary.modifiedtime',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAO','@@@@',0,null,null,null,'N',0,39,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'modifier',0,'N',1,'N','N',38,null,0,'modifier','hrwa.projsalary.modifier',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAN','@@@@',0,null,null,null,'N',0,38,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','N',37,null,0,'creationtime','hrwa.projsalary.creationtime',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAM','@@@@',0,null,null,null,'N',0,37,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',36,null,0,'creator','hrwa.projsalary.creator',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAL','@@@@',0,null,null,null,'N',0,36,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'dmakedate',0,'N',1,'N','N',35,null,0,'dmakedate','hrwa.projsalary.dmakedate',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAK','@@@@',0,null,null,null,'N',0,35,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'billmaker',0,'N',1,'N','N',34,null,0,'billmaker','hrwa.projsalary.billmaker',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAJ','@@@@',0,null,null,null,'N',0,34,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','N',7,null,0,'dbilldate','hrwa.projsalary.dbilldate',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAI','@@@@',0,null,null,null,'N',0,7,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','N',6,null,0,'vbillcode','hrwa.projsalary.vbillcode',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAH','@@@@',0,null,null,null,'N',0,6,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',5,null,0,'pk_org_v','hrwa.projsalary.pk_org_v',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAG','@@@@',0,null,null,null,'N',0,5,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',2,null,0,'pk_org','hrwa.projsalary.pk_org',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAF','@@@@',0,null,null,null,'N',0,2,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',1,null,0,'pk_group','hrwa.projsalary.pk_group',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAE','@@@@',0,null,null,null,'N',0,1,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_projsalary',0,'N',1,'N','N',0,null,0,'pk_projsalary','hrwa.projsalary.pk_projsalary',null,'N',0,null,'0001AA10000000004HAC','0001AA10000000004HAD','@@@@',0,null,null,null,'N',0,0,'projsalary','专案薪资',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psndoc',-1,'pk_psndoc.code',null,'N',1,'N','Y',8,null,0,'code','hrhi.bd_psndoc.code',null,'N',1,null,'0001AA10000000004HAC','1001AA10000000002SB9',null,0,null,null,null,'N',1,8,'projsalary','projsalary',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psndoc',-1,'pk_psndoc.name',null,'N',1,'N','N',10,null,0,'name','hrhi.bd_psndoc.name',null,'N',1,null,'0001AA10000000004HAC','1001AA10000000002SBA',null,0,null,null,null,'N',1,10,'projsalary','projsalary',0,'2017-10-31 18:02:19','N',null,null,null,1,1,'N',1,null,1)
go


insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrwa.projsalary','projsalary',null,'0001AA10000000004HAC','1001AA10000000002W63',null,0,0,null,'projsalary',0,'专案薪资','2017-10-31 18:02:27',null,null,null)
go
