
delete pub_billtemplet_t where ( pk_billtemplet in ('0001AA10000000004HHH') and (dr=0 or dr is null) )
go

delete pub_billtemplet_b where ( pk_billtemplet in ('0001AA10000000004HHH') and (dr=0 or dr is null) )
go

delete pub_billtemplet where ( pk_billtemplet='0001AA10000000004HHH' and (bill_templetname='SYSTEM') and (dr=0 or dr is null) )
go


insert into pub_billtemplet(bill_templetcaption,bill_templetname,devorg,dividerproportion,dr,funccode,layer,metadataclass,model_type,modulecode,nodecode,options,pk_billtemplet,pk_billtypecode,pk_corp,pk_org,resid,shareflag,ts,validateformula) values( 'allocate产出','SYSTEM',null,null,0,null,0,'hrwa.allocate',null,'HRWA','60130allocate',null,'0001AA10000000004HHH','60130allo','@@@@',null,null,null,'2017-10-31 18:15:25',null)
go


insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_allocate',0,'N',1,'N','N',0,null,0,'pk_allocate','hrwa.allocate.pk_allocate',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHI','@@@@',0,null,null,null,'N',0,0,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',1,null,0,'pk_group','hrwa.allocate.pk_group',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHJ','@@@@',0,null,null,null,'N',0,1,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',2,null,0,'pk_org','hrwa.allocate.pk_org',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHK','@@@@',0,null,null,null,'N',1,2,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',3,null,0,'pk_org_v','hrwa.allocate.pk_org_v',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHL','@@@@',0,null,null,null,'N',0,3,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'vbillcode',0,'N',1,'N','N',4,null,0,'vbillcode','hrwa.allocate.vbillcode',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHM','@@@@',0,null,null,null,'N',1,4,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'dbilldate',0,'N',1,'N','N',5,null,0,'dbilldate','hrwa.allocate.dbilldate',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHN','@@@@',0,null,null,null,'N',1,5,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'billmaker',0,'N',1,'N','N',6,null,0,'billmaker','hrwa.allocate.billmaker',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHO','@@@@',0,null,null,null,'N',0,6,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'dmakedate',0,'N',1,'N','N',7,null,0,'dmakedate','hrwa.allocate.dmakedate',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHP','@@@@',0,null,null,null,'N',0,7,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',8,null,0,'creator','hrwa.allocate.creator',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHQ','@@@@',0,null,null,null,'N',0,8,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','N',9,null,0,'creationtime','hrwa.allocate.creationtime',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHR','@@@@',0,null,null,null,'N',0,9,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'modifier',0,'N',1,'N','N',10,null,0,'modifier','hrwa.allocate.modifier',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHS','@@@@',0,null,null,null,'N',0,10,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','N',11,null,0,'modifiedtime','hrwa.allocate.modifiedtime',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHT','@@@@',0,null,null,null,'N',0,11,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_wa_calss',0,'N',1,'N','N',12,null,0,'pk_wa_calss','hrwa.allocate.pk_wa_calss',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHU','@@@@',0,null,null,null,'N',0,12,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'cperiod',0,'N',1,'N','Y',13,null,0,'cperiod','hrwa.allocate.cperiod',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHV','@@@@',0,null,null,null,'N',1,13,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_psndoc',0,'N',1,'N','N',15,null,0,'pk_psndoc','hrwa.allocate.pk_psndoc',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHW','@@@@',0,null,null,null,'N',1,15,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_classitem',0,'N',1,'N','Y',17,null,0,'pk_classitem','hrwa.allocate.pk_classitem',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHX','@@@@',0,null,null,null,'N',1,17,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_project',0,'N',1,'N','N',18,null,0,'pk_project','hrwa.allocate.pk_project',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHY','@@@@',0,null,null,null,'N',0,18,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_costcenter',0,'N',1,'N','N',19,null,0,'pk_costcenter','hrwa.allocate.pk_costcenter',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HHZ','@@@@',0,null,null,null,'N',0,19,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_psnjob',0,'N',1,'N','N',20,null,0,'pk_psnjob','hrwa.allocate.pk_psnjob',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HI0','@@@@',0,null,null,null,'N',0,20,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'专案名称',null,0,1,'pk_project->def1;def3->getcolvalue( "bd_defdoc", "code", "pk_defdoc", pk_project);',-1,'N',null,-1,'def1',0,'N',1,'N','Y',22,null,0,'def1','hrwa.allocate.def1',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HI1','@@@@',0,'1001A110000000002P11:指定專案代碼維護(自定义档案),code=Y','160130allocate-00003',null,'N',1,22,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'分摊金额',null,0,1,null,-1,'N',null,-1,'def2',0,'N',1,'N','Y',23,null,0,'def2','hrwa.allocate.def2',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HI2','@@@@',0,'BS000010000100001031:2,,','160130allocate-00002',null,'N',1,23,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'专案代码',null,0,0,null,-1,'N',null,-1,'def3',0,'N',1,'N','Y',21,'def3->getcolvalue( "bd_defdoc", "code", "pk_defdoc", pk_project);',0,'def3','hrwa.allocate.def3',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HI3','@@@@',0,'BS000010000100001001','160130allocate-00001',null,'N',1,21,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def4',0,'N',1,'N','N',24,null,0,'def4','hrwa.allocate.def4',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HI4','@@@@',0,null,null,null,'N',0,24,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def5',0,'N',1,'N','N',25,null,0,'def5','hrwa.allocate.def5',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HI5','@@@@',0,null,null,null,'N',0,25,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def6',0,'N',1,'N','N',26,null,0,'def6','hrwa.allocate.def6',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HI6','@@@@',0,null,null,null,'N',0,26,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def7',0,'N',1,'N','N',27,null,0,'def7','hrwa.allocate.def7',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HI7','@@@@',0,null,null,null,'N',0,27,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def8',0,'N',1,'N','N',28,null,0,'def8','hrwa.allocate.def8',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HI8','@@@@',0,null,null,null,'N',0,28,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def9',0,'N',1,'N','N',29,null,0,'def9','hrwa.allocate.def9',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HI9','@@@@',0,null,null,null,'N',0,29,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def10',0,'N',1,'N','N',30,null,0,'def10','hrwa.allocate.def10',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIA','@@@@',0,null,null,null,'N',0,30,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def11',0,'N',1,'N','N',31,null,0,'def11','hrwa.allocate.def11',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIB','@@@@',0,null,null,null,'N',0,31,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def12',0,'N',1,'N','N',32,null,0,'def12','hrwa.allocate.def12',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIC','@@@@',0,null,null,null,'N',0,32,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def13',0,'N',1,'N','N',33,null,0,'def13','hrwa.allocate.def13',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HID','@@@@',0,null,null,null,'N',0,33,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def14',0,'N',1,'N','N',34,null,0,'def14','hrwa.allocate.def14',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIE','@@@@',0,null,null,null,'N',0,34,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def15',0,'N',1,'N','N',35,null,0,'def15','hrwa.allocate.def15',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIF','@@@@',0,null,null,null,'N',0,35,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def16',0,'N',1,'N','N',36,null,0,'def16','hrwa.allocate.def16',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIG','@@@@',0,null,null,null,'N',0,36,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def17',0,'N',1,'N','N',37,null,0,'def17','hrwa.allocate.def17',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIH','@@@@',0,null,null,null,'N',0,37,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def18',0,'N',1,'N','N',38,null,0,'def18','hrwa.allocate.def18',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HII','@@@@',0,null,null,null,'N',0,38,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def19',0,'N',1,'N','N',39,null,0,'def19','hrwa.allocate.def19',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIJ','@@@@',0,null,null,null,'N',0,39,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'def20',0,'N',1,'N','N',40,null,0,'def20','hrwa.allocate.def20',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIK','@@@@',0,null,null,null,'N',0,40,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'cbilltypeid',0,'N',1,'N','N',41,null,0,'cbilltypeid','hrwa.allocate.cbilltypeid',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIL','@@@@',0,null,null,null,'N',0,41,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ctrantypeid',0,'N',1,'N','N',42,null,0,'ctrantypeid','hrwa.allocate.ctrantypeid',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIM','@@@@',0,null,null,null,'N',0,42,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'vtrantypecode',0,'N',1,'N','N',43,null,0,'vtrantypecode','hrwa.allocate.vtrantypecode',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIN','@@@@',0,null,null,null,'N',0,43,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'cbiztypeid',0,'N',1,'N','N',44,null,0,'cbiztypeid','hrwa.allocate.cbiztypeid',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIO','@@@@',0,null,null,null,'N',0,44,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'approver',0,'N',1,'N','N',45,null,0,'approver','hrwa.allocate.approver',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIP','@@@@',0,null,null,null,'N',0,45,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'taudittime',0,'N',1,'N','N',46,null,0,'taudittime','hrwa.allocate.taudittime',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIQ','@@@@',0,null,null,null,'N',0,46,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'vapprovenote',0,'N',1,'N','N',47,null,0,'vapprovenote','hrwa.allocate.vapprovenote',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIR','@@@@',0,null,null,null,'N',0,47,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'1',0,1,null,-1,'N',null,-1,'fstatusflag',0,'N',1,'N','N',48,null,0,'fstatusflag','hrwa.allocate.fstatusflag',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIS','@@@@',0,null,null,null,'N',0,48,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',49,null,0,'ts','hrwa.allocate.ts',null,'N',0,null,'0001AA10000000004HHH','0001AA10000000004HIT','@@@@',0,null,null,null,'N',0,49,'allocate','allocate产出',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psndoc',-1,'pk_psndoc.code',null,'N',1,'N','Y',14,null,0,'code','hrhi.bd_psndoc.code',null,'N',0,null,'0001AA10000000004HHH','1001A1100000000030SX',null,0,null,null,null,'N',1,14,'allocate',null,0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psndoc',-1,'pk_psndoc.name',null,'N',1,'N','Y',16,null,0,'name','hrhi.bd_psndoc.name',null,'N',0,null,'0001AA10000000004HHH','1001A1100000000030SY',null,0,null,null,null,'N',1,16,'allocate','allocate',0,'2017-10-31 18:15:25','N',null,null,null,1,1,'N',1,null,1)
go


insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrwa.allocate','allocate',null,'0001AA10000000004HHH','1001AA10000000002W69',null,0,0,null,'allocate',0,'allocate产出','2017-10-31 18:15:26',null,null,null)
go
