
delete pub_query_condition where ( pk_templet in ('0001ZZ10000000058LFH') and (dr=0 or dr is null) );


delete pub_query_templet where ( id='0001ZZ10000000058LFH' and (pk_corp='@@@@') and (dr=0 or dr is null) );



insert into pub_query_templet(description,devorg,dr,fixcondition,fixquerytree,id,layer,metaclass,model_code,model_name,node_code,parentid,pk_corp,pk_org,resid,ts) values( null,null,0,null,null,'0001ZZ10000000058LFH',0,'fd6a567a-fc42-4014-9526-c32eb0d0d444','68J61707','劳健保计算','68J61707',null,'@@@@',null,null,'2018-09-10 10:59:17');



insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,0,1,null,0,null,null,null,null,null,'pk_nhicalc',null,null,'0001ZZ10000000058LFI','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00003',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,1,1,null,0,null,null,null,null,null,'pk_epyfamily',null,null,'0001ZZ10000000058LFJ','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000058LFH',null,'368861705-00007',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,2,1,null,0,null,null,null,null,null,'rowno',null,null,'0001ZZ10000000058LFK','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000058LFH',null,'2201112-000067',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '集团',5,3,1,null,0,null,null,null,null,null,'pk_group',null,null,'0001ZZ10000000058LFL','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000058LFH',null,'2UC000-001007',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '组织（包含全局）(所有)',5,4,1,null,0,null,null,null,null,null,'pk_org',null,null,'0001ZZ10000000058LFM','N','Y','N','Y',null,'N','N','N','Y',null,'N','N','N','Y','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001ZZ10000000058LFH',null,'2UC000-000693',2,null,null,'2018-09-10 10:59:17',null,'#mainorg#');

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '业务单元版本',5,5,1,null,0,null,null,null,null,null,'pk_org_v',null,null,'0001ZZ10000000058LFN','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000058LFH',null,'2UC000-000701',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '用户',5,6,1,null,0,null,null,null,null,null,'creator',null,null,'0001ZZ10000000058LFO','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000058LFH',null,'2201112-000004',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',8,7,1,null,0,null,null,null,null,null,'creationtime',null,null,'0001ZZ10000000058LFP','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'2201112-000003',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '用户',5,8,1,null,0,null,null,null,null,null,'modifier',null,null,'0001ZZ10000000058LFQ','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000058LFH',null,'2UC000-000098',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',8,9,1,null,0,null,null,null,null,null,'modifiedtime',null,null,'0001ZZ10000000058LFR','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'2UC000-000100',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( 'HR人员',5,10,1,null,0,null,null,null,null,null,'pk_psndoc',null,null,'0001ZZ10000000058LFS','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00063',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',4,11,1,null,0,null,null,null,null,null,'iscalculated',null,null,'0001ZZ10000000058LFT','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00012',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',4,12,1,null,0,null,null,null,null,null,'isaudit',null,null,'0001ZZ10000000058LFU','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00054',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,13,1,null,0,null,null,null,null,null,'cyear',null,null,'0001ZZ10000000058LFV','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00044',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,14,1,null,0,null,null,null,null,null,'cperiod',null,null,'0001ZZ10000000058LFW','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00056',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',3,15,1,null,0,null,null,null,null,null,'begindate',null,null,'0001ZZ10000000058LFX','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'2UC000-000944',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',3,16,1,null,0,null,null,null,null,null,'enddate',null,null,'0001ZZ10000000058LFY','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00058',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,17,1,null,0,null,null,null,null,null,'oldlaborsalary',null,null,'0001ZZ10000000058LFZ','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00043',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,18,1,null,0,null,null,null,null,null,'laborsalary',null,null,'0001ZZ10000000058LG0','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00070',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,19,1,null,0,null,null,null,null,null,'oldlaborrange',null,null,'0001ZZ10000000058LG1','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00009',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,20,1,null,0,null,null,null,null,null,'laborrange',null,null,'0001ZZ10000000058LG2','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00062',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,21,1,null,0,null,null,null,null,null,'oldretirerange',null,null,'0001ZZ10000000058LG3','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00011',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,22,1,null,0,null,null,null,null,null,'retirerange',null,null,'0001ZZ10000000058LG4','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00027',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,23,1,null,0,null,null,null,null,null,'oldhealthsalary',null,null,'0001ZZ10000000058LG5','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00035',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,24,1,null,0,null,null,null,null,null,'healthsalary',null,null,'0001ZZ10000000058LG6','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00007',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,25,1,null,0,null,null,null,null,null,'oldhealthrange',null,null,'0001ZZ10000000058LG7','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00049',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,26,1,null,0,null,null,null,null,null,'healthrange',null,null,'0001ZZ10000000058LG8','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00057',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,27,1,null,0,null,null,null,null,null,'labortsmd5',null,null,'0001ZZ10000000058LG9','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00014',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,28,1,null,0,null,null,null,null,null,'healthtsmd5',null,null,'0001ZZ10000000058LGA','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00045',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',4,29,1,null,0,null,null,null,null,null,'includelastmonth',null,null,'0001ZZ10000000058LGB','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00000',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',1,30,1,null,0,null,null,null,null,null,'lastmonthlabordays',null,null,'0001ZZ10000000058LGC','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00024',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,31,1,null,0,null,null,null,null,null,'lastmonthretirehirer',null,null,'0001ZZ10000000058LGD','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00019',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,32,1,null,0,null,null,null,null,null,'lastmonthretirestuff',null,null,'0001ZZ10000000058LGE','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00022',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,33,1,null,0,null,null,null,null,null,'lastmonthlaborhirer',null,null,'0001ZZ10000000058LGF','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00033',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,34,1,null,0,null,null,null,null,null,'lastmonthllaborstuff',null,null,'0001ZZ10000000058LGG','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00026',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,35,1,null,0,null,null,null,null,null,'lastmonthemphirer',null,null,'0001ZZ10000000058LGH','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00050',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,36,1,null,0,null,null,null,null,null,'lastmonthempstuff',null,null,'0001ZZ10000000058LGI','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00010',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,37,1,null,0,null,null,null,null,null,'lastmonthdishirer',null,null,'0001ZZ10000000058LGJ','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00064',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,38,1,null,0,null,null,null,null,null,'lastmonthdisstuff',null,null,'0001ZZ10000000058LGK','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00041',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,39,1,null,0,null,null,null,null,null,'lastmonthcomhirer',null,null,'0001ZZ10000000058LGL','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00008',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,40,1,null,0,null,null,null,null,null,'lastmonthcomstuff',null,null,'0001ZZ10000000058LGM','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00028',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',1,41,1,null,0,null,null,null,null,null,'labordays',null,null,'0001ZZ10000000058LGN','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00051',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,42,1,null,0,null,null,null,null,null,'retirehirer',null,null,'0001ZZ10000000058LGO','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00031',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,43,1,null,0,null,null,null,null,null,'retirestuff',null,null,'0001ZZ10000000058LGP','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00018',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,44,1,null,0,null,null,null,null,null,'laborhirer',null,null,'0001ZZ10000000058LGQ','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00021',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,45,1,null,0,null,null,null,null,null,'laborstuff',null,null,'0001ZZ10000000058LGR','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00066',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,46,1,null,0,null,null,null,null,null,'emphirer',null,null,'0001ZZ10000000058LGS','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00013',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,47,1,null,0,null,null,null,null,null,'empstuff',null,null,'0001ZZ10000000058LGT','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00037',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,48,1,null,0,null,null,null,null,null,'dishirer',null,null,'0001ZZ10000000058LGU','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00055',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,49,1,null,0,null,null,null,null,null,'disstuff',null,null,'0001ZZ10000000058LGV','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00040',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,50,1,null,0,null,null,null,null,null,'comhirer',null,null,'0001ZZ10000000058LGW','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00061',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,51,1,null,0,null,null,null,null,null,'comstuff',null,null,'0001ZZ10000000058LGX','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00032',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,52,1,null,0,null,null,null,null,null,'disablegrade',null,null,'0001ZZ10000000058LGY','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00005',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,53,1,null,0,null,null,null,null,null,'labortype',null,null,'0001ZZ10000000058LGZ','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00047',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,54,1,null,0,null,null,null,null,null,'comrate',null,null,'0001ZZ10000000058LH0','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00042',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,55,1,null,0,null,null,null,null,null,'comstuffrate',null,null,'0001ZZ10000000058LH1','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00002',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,56,1,null,0,null,null,null,null,null,'comhirerrate',null,null,'0001ZZ10000000058LH2','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00067',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,57,1,null,0,null,null,null,null,null,'disrate',null,null,'0001ZZ10000000058LH3','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00046',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,58,1,null,0,null,null,null,null,null,'disstuffrate',null,null,'0001ZZ10000000058LH4','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00020',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,59,1,null,0,null,null,null,null,null,'dishirerrate',null,null,'0001ZZ10000000058LH5','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00030',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,60,1,null,0,null,null,null,null,null,'emprate',null,null,'0001ZZ10000000058LH6','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00015',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,61,1,null,0,null,null,null,null,null,'empstuffrate',null,null,'0001ZZ10000000058LH7','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00038',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,62,1,null,0,null,null,null,null,null,'emphirerrate',null,null,'0001ZZ10000000058LH8','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00004',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,63,1,null,0,null,null,null,null,null,'retirestuffrate',null,null,'0001ZZ10000000058LH9','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00065',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,64,1,null,0,null,null,null,null,null,'retirehirerrate',null,null,'0001ZZ10000000058LHA','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00016',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,65,1,null,0,null,null,null,null,null,'laborsalaryextend',null,null,'0001ZZ10000000058LHB','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00053',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,66,1,null,0,null,null,null,null,null,'healthsalaryextend',null,null,'0001ZZ10000000058LHC','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'N',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00060',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',1,67,1,null,0,null,null,null,null,null,'dependentcount',null,null,'0001ZZ10000000058LHD','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00052',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,68,1,null,0,null,null,null,null,null,'healthstuff',null,null,'0001ZZ10000000058LHE','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00025',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,69,1,null,0,null,null,null,null,null,'healthhirer',null,null,'0001ZZ10000000058LHF','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00048',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,70,1,null,0,null,null,null,null,null,'healthgov',null,null,'0001ZZ10000000058LHG','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00034',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,71,1,null,0,null,null,null,null,null,'healthstuffact',null,null,'0001ZZ10000000058LHH','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00069',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,72,1,null,0,null,null,null,null,null,'repayfund',null,null,'0001ZZ10000000058LHI','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00001',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,73,1,null,0,null,null,null,null,null,'lastmonthrepayfund',null,null,'0001ZZ10000000058LHJ','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00006',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,74,1,null,0,null,null,null,null,null,'lastmonthhealthstuff',null,null,'0001ZZ10000000058LHK','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00023',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,75,1,null,0,null,null,null,null,null,'lastmonthhealthhirer',null,null,'0001ZZ10000000058LHL','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00017',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,76,1,null,0,null,null,null,null,null,'lastmonthhealthgov',null,null,'0001ZZ10000000058LHM','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00059',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,77,1,null,0,null,null,null,null,null,'lastmonthhealthstuffact',null,null,'0001ZZ10000000058LHN','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00036',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',1,78,1,null,0,null,null,null,null,null,'retiredays',null,null,'0001ZZ10000000058LHO','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00039',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',1,79,1,null,0,null,null,null,null,null,'lastmonthretiredays',null,null,'0001ZZ10000000058LHP','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00068',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '公司',5,80,1,null,0,null,null,null,null,null,'pk_corp',null,null,'0001ZZ10000000058LHQ','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00071',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,81,1,null,0,null,null,null,null,null,'healthpersamount',null,null,'0001ZZ10000000058LHR','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00072',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '8',2,82,1,null,0,null,null,null,null,null,'healthcommitamount',null,null,'0001ZZ10000000058LHS','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'268861705-00073',2,null,null,'2018-09-10 10:59:17',null,null);

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',3,83,0,null,0,null,null,null,null,null,'billdate',null,null,'0001ZZ10000000058LHT','N','Y','N','Y',null,'N','N','N','Y',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000058LFH',null,'368861705-00008',2,null,null,'2018-09-10 10:59:17',null,'#day(0)#,#day(0)#');

insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,84,1,null,0,null,null,null,null,null,'biiltype',null,null,'0001ZZ10000000058LHU','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000058LFH',null,'368861705-00009',2,null,null,'2018-09-10 10:59:17',null,null);

/
