/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ta.teamcalendar;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.UFBoolean;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class TeamCalendarVO extends SuperVO {
	private java.lang.String pk_teamcalendar;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String pk_team;
	private nc.vo.pub.lang.UFLiteralDate calendar;
	private java.lang.String original_shift_b4exg;
	private java.lang.String original_shift_b4cut;
	private java.lang.String pk_shift;
	private nc.vo.pub.lang.UFDouble gzsj;
	private nc.vo.pub.lang.UFBoolean if_rest;
	private nc.vo.pub.lang.UFBoolean cancelflag;
	private nc.vo.pub.lang.UFBoolean iswtrecreate;
	private nc.vo.pub.lang.UFBoolean isflexiblefinal;
	private nc.vo.pub.lang.UFBoolean ismanuctrl = UFBoolean.FALSE;
	private java.lang.String cwkid;
	private java.lang.String vnote;
	private java.lang.String pk_org_v;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private java.lang.Integer date_daytype;

	public static final String PK_TEAMCALENDAR = "pk_teamcalendar";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String PK_TEAM = "pk_team";
	public static final String CALENDAR = "calendar";
	public static final String ORIGINAL_SHIFT_B4EXG = "original_shift_b4exg";
	public static final String ORIGINAL_SHIFT_B4CUT = "original_shift_b4cut";
	public static final String PK_SHIFT = "pk_shift";
	public static final String GZSJ = "gzsj";
	public static final String IF_REST = "if_rest";
	public static final String CANCELFLAG = "cancelflag";
	public static final String ISWTRECREATE = "iswtrecreate";
	public static final String ISFLEXIBLEFINAL = "isflexiblefinal";
	public static final String ISMANUCTRL = "ismanuctrl";
	public static final String CWKID = "cwkid";
	public static final String VNOTE = "vnote";
	public static final String PK_ORG_V = "pk_org_v";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String DATE_DAYTYPE = "date_daytype";
	
	public java.lang.Integer getDate_daytype() {
		return date_daytype;
	}

	public void setDate_daytype(java.lang.Integer date_daytype) {
		this.date_daytype = date_daytype;
	}
			
	/**
	 * 属性pk_teamcalendar的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_teamcalendar () {
		return pk_teamcalendar;
	}   
	/**
	 * 属性pk_teamcalendar的Setter方法.
	 * 创建日期:
	 * @param newPk_teamcalendar java.lang.String
	 */
	public void setPk_teamcalendar (java.lang.String newPk_teamcalendar ) {
	 	this.pk_teamcalendar = newPk_teamcalendar;
	} 	  
	/**
	 * 属性pk_group的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_team的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_team () {
		return pk_team;
	}   
	/**
	 * 属性pk_team的Setter方法.
	 * 创建日期:
	 * @param newPk_team java.lang.String
	 */
	public void setPk_team (java.lang.String newPk_team ) {
	 	this.pk_team = newPk_team;
	} 	  
	/**
	 * 属性calendar的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFLiteralDate
	 */
	public nc.vo.pub.lang.UFLiteralDate getCalendar () {
		return calendar;
	}   
	/**
	 * 属性calendar的Setter方法.
	 * 创建日期:
	 * @param newCalendar nc.vo.pub.lang.UFLiteralDate
	 */
	public void setCalendar (nc.vo.pub.lang.UFLiteralDate newCalendar ) {
	 	this.calendar = newCalendar;
	} 	  
	/**
	 * 属性original_shift_b4exg的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOriginal_shift_b4exg () {
		return original_shift_b4exg;
	}   
	/**
	 * 属性original_shift_b4exg的Setter方法.
	 * 创建日期:
	 * @param newOriginal_shift_b4exg java.lang.String
	 */
	public void setOriginal_shift_b4exg (java.lang.String newOriginal_shift_b4exg ) {
	 	this.original_shift_b4exg = newOriginal_shift_b4exg;
	} 	  
	/**
	 * 属性original_shift_b4cut的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOriginal_shift_b4cut () {
		return original_shift_b4cut;
	}   
	/**
	 * 属性original_shift_b4cut的Setter方法.
	 * 创建日期:
	 * @param newOriginal_shift_b4cut java.lang.String
	 */
	public void setOriginal_shift_b4cut (java.lang.String newOriginal_shift_b4cut ) {
	 	this.original_shift_b4cut = newOriginal_shift_b4cut;
	} 	  
	/**
	 * 属性pk_shift的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_shift () {
		return pk_shift;
	}   
	/**
	 * 属性pk_shift的Setter方法.
	 * 创建日期:
	 * @param newPk_shift java.lang.String
	 */
	public void setPk_shift (java.lang.String newPk_shift ) {
	 	this.pk_shift = newPk_shift;
	} 	  
	/**
	 * 属性gzsj的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getGzsj () {
		return gzsj;
	}   
	/**
	 * 属性gzsj的Setter方法.
	 * 创建日期:
	 * @param newGzsj nc.vo.pub.lang.UFDouble
	 */
	public void setGzsj (nc.vo.pub.lang.UFDouble newGzsj ) {
	 	this.gzsj = newGzsj;
	} 	  
	/**
	 * 属性if_rest的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIf_rest () {
		return if_rest;
	}   
	/**
	 * 属性if_rest的Setter方法.
	 * 创建日期:
	 * @param newIf_rest nc.vo.pub.lang.UFBoolean
	 */
	public void setIf_rest (nc.vo.pub.lang.UFBoolean newIf_rest ) {
	 	this.if_rest = newIf_rest;
	} 	  
	/**
	 * 属性cancelflag的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getCancelflag () {
		return cancelflag;
	}   
	/**
	 * 属性cancelflag的Setter方法.
	 * 创建日期:
	 * @param newCancelflag nc.vo.pub.lang.UFBoolean
	 */
	public void setCancelflag (nc.vo.pub.lang.UFBoolean newCancelflag ) {
	 	this.cancelflag = newCancelflag;
	} 	  
	/**
	 * 属性iswtrecreate的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIswtrecreate () {
		return iswtrecreate;
	}   
	/**
	 * 属性iswtrecreate的Setter方法.
	 * 创建日期:
	 * @param newIswtrecreate nc.vo.pub.lang.UFBoolean
	 */
	public void setIswtrecreate (nc.vo.pub.lang.UFBoolean newIswtrecreate ) {
	 	this.iswtrecreate = newIswtrecreate;
	} 	  
	/**
	 * 属性isflexiblefinal的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsflexiblefinal () {
		return isflexiblefinal;
	}   
	/**
	 * 属性isflexiblefinal的Setter方法.
	 * 创建日期:
	 * @param newIsflexiblefinal nc.vo.pub.lang.UFBoolean
	 */
	public void setIsflexiblefinal (nc.vo.pub.lang.UFBoolean newIsflexiblefinal ) {
	 	this.isflexiblefinal = newIsflexiblefinal;
	} 	  
	public nc.vo.pub.lang.UFBoolean getIsmanuctrl() {
		return ismanuctrl;
	}
	public void setIsmanuctrl(nc.vo.pub.lang.UFBoolean ishrctrl) {
		this.ismanuctrl = ishrctrl;
	}
	public java.lang.String getCwkid() {
		return cwkid;
	}
	public void setCwkid(java.lang.String cwkid) {
		this.cwkid = cwkid;
	}
	public java.lang.String getVnote() {
		return vnote;
	}
	public void setVnote(java.lang.String vnote) {
		this.vnote = vnote;
	}
	public java.lang.String getPk_org_v() {
		return pk_org_v;
	}
	public void setPk_org_v(java.lang.String pk_org_v) {
		this.pk_org_v = pk_org_v;
	}
	/**
	 * 属性creator的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * 属性creator的Setter方法.
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * 属性creationtime的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * 属性creationtime的Setter方法.
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * 属性modifier的Getter方法.
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_teamcalendar";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "bd_teamcalendar";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "bd_teamcalendar";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public TeamCalendarVO() {
		super();	
	}    
     
     public boolean isHolidayCancel(){
 		return getCancelflag()!=null&&getCancelflag().booleanValue();
 	}
     
    public boolean isWTRcreate(){
    	return getIswtrecreate()!=null&&getIswtrecreate().booleanValue();
    }
    
    public boolean isManuCtrl(){
    	return getIsmanuctrl()!=null&&getIsmanuctrl().booleanValue();
    }
} 


