/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.wa.othersource;
	
import nc.vo.hr.itemsource.TypeEnumVO;
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class OtherSourceVO extends SuperVO {
	private java.lang.String pk_otherdatasource;
	private java.lang.String datasourcename;
	private java.lang.String datasourcename2;
	private java.lang.String datasourcename3;
	private java.lang.String datasourcename4;
	private java.lang.String datasourcename5;
	private java.lang.String datasourcename6;
	private java.lang.String formulastr;
	private java.lang.Integer datatype = TypeEnumVO.FLOATTYPE.toIntValue();
	private java.lang.String description;
	private java.lang.String demo;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_OTHERDATASOURCE = "pk_otherdatasource";
	public static final String DATASOURCENAME = "datasourcename";
	public static final String DATASOURCENAME2 = "datasourcename2";
	public static final String DATASOURCENAME3 = "datasourcename3";
	public static final String DATASOURCENAME4 = "datasourcename4";
	public static final String DATASOURCENAME5 = "datasourcename5";
	public static final String DATASOURCENAME6 = "datasourcename6";
	public static final String FORMULASTR = "formulastr";
	public static final String DATATYPE = "datatype";
	public static final String DESCRIPTION = "description";
	public static final String DEMO = "demo";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
			
	/**
	 * 属性pk_otherdatasource的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_otherdatasource () {
		return pk_otherdatasource;
	}   
	/**
	 * 属性pk_otherdatasource的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_otherdatasource java.lang.String
	 */
	public void setPk_otherdatasource (java.lang.String newPk_otherdatasource ) {
	 	this.pk_otherdatasource = newPk_otherdatasource;
	} 	  
	/**
	 * 属性datasourcename的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDatasourcename () {
		return datasourcename;
	}   
	/**
	 * 属性datasourcename的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newDatasourcename java.lang.String
	 */
	public void setDatasourcename (java.lang.String newDatasourcename ) {
	 	this.datasourcename = newDatasourcename;
	} 	  
	/**
	 * 属性datasourcename2的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDatasourcename2 () {
		return datasourcename2;
	}   
	/**
	 * 属性datasourcename2的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newDatasourcename2 java.lang.String
	 */
	public void setDatasourcename2 (java.lang.String newDatasourcename2 ) {
	 	this.datasourcename2 = newDatasourcename2;
	} 	  
	/**
	 * 属性datasourcename3的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDatasourcename3 () {
		return datasourcename3;
	}   
	/**
	 * 属性datasourcename3的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newDatasourcename3 java.lang.String
	 */
	public void setDatasourcename3 (java.lang.String newDatasourcename3 ) {
	 	this.datasourcename3 = newDatasourcename3;
	} 	  
	/**
	 * 属性datasourcename4的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDatasourcename4 () {
		return datasourcename4;
	}   
	/**
	 * 属性datasourcename4的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newDatasourcename4 java.lang.String
	 */
	public void setDatasourcename4 (java.lang.String newDatasourcename4 ) {
	 	this.datasourcename4 = newDatasourcename4;
	} 	  
	/**
	 * 属性datasourcename5的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDatasourcename5 () {
		return datasourcename5;
	}   
	/**
	 * 属性datasourcename5的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newDatasourcename5 java.lang.String
	 */
	public void setDatasourcename5 (java.lang.String newDatasourcename5 ) {
	 	this.datasourcename5 = newDatasourcename5;
	} 	  
	/**
	 * 属性datasourcename6的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDatasourcename6 () {
		return datasourcename6;
	}   
	/**
	 * 属性datasourcename6的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newDatasourcename6 java.lang.String
	 */
	public void setDatasourcename6 (java.lang.String newDatasourcename6 ) {
	 	this.datasourcename6 = newDatasourcename6;
	} 	  
	/**
	 * 属性formulastr的Getter方法.属性名：sql语句
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getFormulastr () {
		return formulastr;
	}   
	/**
	 * 属性formulastr的Setter方法.属性名：sql语句
	 * 创建日期:
	 * @param newFormulastr java.lang.String
	 */
	public void setFormulastr (java.lang.String newFormulastr ) {
	 	this.formulastr = newFormulastr;
	} 	  
	/**
	 * 属性datatype的Getter方法.属性名：类型
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDatatype () {
		return datatype;
	}   
	/**
	 * 属性datatype的Setter方法.属性名：类型
	 * 创建日期:
	 * @param newDatatype java.lang.Integer
	 */
	public void setDatatype (java.lang.Integer newDatatype ) {
	 	this.datatype = newDatatype;
	} 	  
	/**
	 * 属性description的Getter方法.属性名：描述
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDescription () {
		return description;
	}   
	/**
	 * 属性description的Setter方法.属性名：描述
	 * 创建日期:
	 * @param newDescription java.lang.String
	 */
	public void setDescription (java.lang.String newDescription ) {
	 	this.description = newDescription;
	} 	  
	/**
	 * 属性demo的Getter方法.属性名：实例
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getDemo () {
		return demo;
	}   
	/**
	 * 属性demo的Setter方法.属性名：实例
	 * 创建日期:
	 * @param newDemo java.lang.String
	 */
	public void setDemo (java.lang.String newDemo ) {
	 	this.demo = newDemo;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.属性名：集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_otherdatasource";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "wa_otherdatasource";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "wa_otherdatasource";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public OtherSourceVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.wa.othersource.OtherSourceVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


