
delete pub_billtemplet_t where ( pk_billtemplet in ('1001Z71000000000D832') and (dr=0 or dr is null) )
/

delete pub_billtemplet_b where ( pk_billtemplet in ('1001Z71000000000D832') and (dr=0 or dr is null) )
/

delete pub_billtemplet where ( PK_BILLTEMPLET='1001Z71000000000D832' and (bill_templetname='SYSTEM') and (dr=0 or dr is null) )
/


insert into pub_billtemplet(bill_templetcaption,bill_templetname,devorg,dividerproportion,dr,funccode,layer,metadataclass,model_type,modulecode,nodecode,options,pk_billtemplet,pk_billtypecode,pk_corp,pk_org,resid,shareflag,ts,validateformula) values( '薪资发放项目','SYSTEM',null,'0.772972972972973',0,null,0,'hrwa.wa_classitem',null,'HRWA','60130payitem',null,'1001Z71000000000D832','classitem','@@@@',null,'160130payitem0006',null,'2018-08-04 14:43:06',null)
/


insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',0,null,0,'ts','hrwa.wa_classitem.ts',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000D83V','@@@@',0,null,null,null,'N',0,27,'wa_classitem','薪资发放项目',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,6,'数据来源',null,0,1,null,-1,'N',null,20,'datasourcetype',0,'N',1,'N','N',0,null,0,null,null,null,'N',0,null,'1001Z71000000000D832','1001Z71000000000D85M','@@@@',0,null,'UC001-0000120',null,'N',1,1,'datasource','项目数据来源',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,4)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,1,null,-1,'N',null,-1,'clearflag',0,'N',1,'N','Y',0,null,0,'clearflag','hrwa.wa_classitem.clearflag',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000D85N','@@@@',0,null,null,null,'N',1,1,'closeoff','closeoff',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,12,'个人薪资项目下限',null,0,1,null,-1,'N',null,20,'psnfloor',null,'N',1,'N','N',0,null,0,null,null,null,'N',0,null,'1001Z71000000000D832','1001Z71000000000DLYX',null,0,null,'160130glbitem0007',null,'N',1,4,'prealert','预警条件设置',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,2)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,12,'薪资项目总额上限',null,0,1,null,-1,'N',null,20,'sumceil',null,'N',1,'N','N',0,null,0,null,null,null,'N',0,null,'1001Z71000000000D832','1001Z71000000000DLYY',null,0,null,'160130glbitem0004',null,'N',1,1,'prealert','预警条件设置',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,2)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,12,'薪资项目总额下限',null,0,1,null,-1,'N',null,20,'sumfloor',null,'N',1,'N','N',0,null,0,null,null,null,'N',0,null,'1001Z71000000000D832','1001Z71000000000DLYZ',null,0,null,'160130glbitem0005',null,'N',1,2,'prealert','预警条件设置',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,2)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,12,'个人薪资项目上限',null,0,1,null,-1,'N',null,20,'psnceil',null,'N',1,'N','N',0,null,0,null,null,null,'Y',0,null,'1001Z71000000000D832','1001Z71000000000DLZ0',null,0,null,'160130glbitem0006',null,'N',1,3,'prealert','预警条件设置',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,2)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',0,null,0,'pk_org','hrwa.wa_classitem.pk_org',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000DLZA','@@@@',0,null,null,null,'N',0,28,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','Y',0,null,0,'pk_group','hrwa.wa_classitem.pk_group',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000DLZB','@@@@',0,null,null,null,'N',0,29,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_wa_item',-1,'pk_wa_item.iflddecimal',null,'N',1,'N','N',0,null,0,'iflddecimal','hrwa.waitem.iflddecimal',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000ELGZ',null,0,null,null,null,'N',0,15,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_wa_item',-1,'pk_wa_item.ifldwidth',null,'N',1,'N','N',0,null,0,'ifldwidth','hrwa.waitem.ifldwidth',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000ELH0',null,0,null,null,null,'N',0,13,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_wa_item',-1,'pk_wa_item.iproperty',null,'N',1,'N','N',0,null,0,'iproperty','hrwa.waitem.iproperty',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000ELH1',null,0,null,null,null,'N',0,11,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_wa_item',-1,'pk_wa_item.iitemtype',null,'N',1,'N','N',0,null,0,'iitemtype','hrwa.waitem.iitemtype',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000ELH2',null,0,null,null,null,'N',0,9,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'公共项目分类',null,0,0,null,-1,'N','pk_wa_item',-1,'pk_wa_item.category_id',0,'N',1,'N','N',0,null,0,'category_id','hrwa.waitem.category_id',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000F9DT','@@@@',0,'薪资项目分类(自定义档案)','160130payitem0003',null,'N',0,7,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'itemkey',0,'N',1,'N','N',0,null,0,'itemkey','hrwa.wa_classitem.itemkey',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000ULUP','@@@@',0,null,null,null,'N',0,30,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'工资卡',null,0,1,null,-1,'N',null,-1,'bankaccount',0,'N',1,'N','Y',0,null,0,'bankaccount','hrwa.wa_classitem.bankaccount',null,'N',0,null,'1001Z71000000000D832','1004Z710000000004H9L','@@@@',0,null,'160130payitem0004',null,'N',1,17,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,0,null,-1,'N','pk_wa_item',-1,'pk_wa_item.mid',null,'N',1,'N','N',0,null,0,'mid','hrwa.waitem.mid',null,'N',0,null,'1001Z71000000000D832','1004Z710000000004VXV',null,0,null,null,null,'N',0,20,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','Y',0,null,0,'creationtime','hrwa.wa_classitem.creationtime',null,'N',0,null,'1001Z71000000000D832','1004Z7100000000056Q9','@@@@',2,null,null,null,'N',1,2,'AuditInfo','AuditInfo',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','Y',0,null,0,'modifier','hrwa.wa_classitem.modifier',null,'N',0,null,'1001Z71000000000D832','1004Z7100000000056QA','@@@@',2,null,null,null,'N',1,3,'AuditInfo','AuditInfo',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',0,'N',1,'N','Y',0,null,0,'creator','hrwa.wa_classitem.creator',null,'N',0,null,'1001Z71000000000D832','1004Z7100000000056QB','@@@@',2,null,null,null,'N',1,1,'AuditInfo','AuditInfo',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','Y',0,null,0,'modifiedtime','hrwa.wa_classitem.modifiedtime',null,'N',0,null,'1001Z71000000000D832','1004Z7100000000056QC','@@@@',2,null,null,null,'N',1,4,'AuditInfo','AuditInfo',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'项目分类',null,0,1,null,-1,'N',null,-1,'category_id',null,'N',1,'N','Y',0,null,0,'category_id','hrwa.wa_classitem.category_id',null,'N',0,null,'1001Z71000000000D832','1004Z710000000005UND',null,0,null,'160130payitem0005',null,'N',1,8,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'0',0,1,null,-1,'N',null,-1,'round_type',null,'N',1,'N','Y',0,null,0,'round_type','hrwa.wa_classitem.round_type',null,'N',0,null,'1001Z71000000000D832','1004Z710000000005UNE',null,0,null,null,null,'N',1,18,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,1,null,-1,'N',null,-1,'inapproveditem',0,'N',1,'N','Y',0,null,0,'inapproveditem','hrwa.wa_classitem.inapproveditem',null,'N',0,null,'1001Z71000000000D832','1004Z710000000005UNK','@@@@',0,null,null,null,'N',1,31,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_wa_item',0,'N',1,'Y','Y',0,null,0,'pk_wa_item','hrwa.wa_classitem.pk_wa_item','name=name,category_id=category_id,iitemtype=iitemtype,iproperty=iproperty,ifldwidth=ifldwidth,iflddecimal=iflddecimal,taxflag=taxflag,itemkey=itemkey,mid=mid','N',0,null,'1001Z71000000000D832','1004Z7100000000068JD','@@@@',0,null,null,null,'N',1,5,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'数据类型',null,0,1,null,-1,'N',null,-1,'iitemtype',0,'N',1,'N','Y',0,null,0,'iitemtype','hrwa.wa_classitem.iitemtype',null,'N',0,null,'1001Z71000000000D832','1004Z7100000000068JE','@@@@',0,null,'UC000-0002279',null,'N',1,10,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'iflddecimal',0,'N',1,'N','Y',0,null,0,'iflddecimal','hrwa.wa_classitem.iflddecimal',null,'N',0,null,'1001Z71000000000D832','1004Z7100000000068JF','@@@@',0,null,null,null,'N',1,16,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ifldwidth',0,'N',1,'N','Y',0,null,0,'ifldwidth','hrwa.wa_classitem.ifldwidth',null,'N',0,null,'1001Z71000000000D832','1004Z7100000000068JG','@@@@',0,null,null,null,'N',1,14,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'iproperty',0,'N',1,'N','Y',0,null,0,'iproperty','hrwa.wa_classitem.iproperty',null,'N',0,null,'1001Z71000000000D832','1004Z7100000000068JH','@@@@',0,null,null,null,'N',1,12,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,0,null,-1,'N',null,-1,'mid',null,'N',1,'N','Y',0,null,0,'mid','hrwa.wa_classitem.mid',null,'N',0,null,'1001Z71000000000D832','1004Z710000000006KW7',null,0,null,null,null,'N',1,21,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,12,'结转设置',null,0,1,null,-1,'N',null,20,'transfer',null,'N',1,'N','N',0,null,0,null,null,null,'N',0,null,'1001Z71000000000D832','1001Z7100000000023M9',null,0,null,'160130payitem0001',null,'N',1,2,'closeoff','结转设置',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,3)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_wa_classitem',0,'N',1,'N','N',0,null,0,'pk_wa_classitem','hrwa.wa_classitem.pk_wa_classitem',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000D833','@@@@',0,null,null,null,'N',0,1,'wa_classitem','薪资发放项目',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_wa_class',0,'N',1,'N','N',0,null,0,'pk_wa_class','hrwa.wa_classitem.pk_wa_class',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000D834','@@@@',0,null,null,null,'N',0,2,'wa_classitem','薪资发放项目',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'cyear',0,'N',1,'N','N',0,null,0,'cyear','hrwa.wa_classitem.cyear',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000D835','@@@@',0,null,null,null,'N',0,3,'wa_classitem','薪资发放项目',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'cperiod',0,'N',1,'N','N',0,null,0,'cperiod','hrwa.wa_classitem.cperiod',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000D836','@@@@',0,null,null,null,'N',0,4,'wa_classitem','薪资发放项目',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'name',0,'N',1,'N','Y',0,null,0,'name','hrwa.wa_classitem.name',null,'N',1,null,'1001Z71000000000D832','1001Z71000000000D838','@@@@',0,null,null,null,'N',1,6,'wa_classitem','薪资发放项目',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'扣税','true',0,1,null,-1,'N',null,-1,'taxflag',0,'N',1,'N','Y',0,null,0,'taxflag','hrwa.wa_classitem.taxflag',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000D83A','@@@@',0,null,'160130payitem0002',null,'N',1,19,'wa_classitem','薪资发放项目',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'icomputeseq',0,'N',1,'N','N',0,null,0,'icomputeseq','hrwa.wa_classitem.icomputeseq',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000D83E','@@@@',0,null,null,null,'N',0,22,'wa_classitem','薪资发放项目',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'idisplayseq',0,'N',1,'N','N',0,null,0,'idisplayseq','hrwa.wa_classitem.idisplayseq',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000D83F','@@@@',0,null,null,null,'N',0,23,'wa_classitem','薪资发放项目',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,1,null,-1,'N',null,-1,'showflag',0,'N',1,'N','N',0,null,0,'showflag','hrwa.wa_classitem.showflag',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000D83O','@@@@',0,null,null,null,'N',0,24,'wa_classitem','薪资发放项目',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,0,null,-1,'N',null,-1,'issysformula',0,'N',1,'N','N',0,null,0,'issysformula','hrwa.wa_classitem.issysformula',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000D83P','@@@@',0,null,null,null,'N',0,25,'wa_classitem','薪资发放项目',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'dr',0,'N',1,'N','N',0,null,0,'dr','hrwa.wa_classitem.dr',null,'N',0,null,'1001Z71000000000D832','1001Z71000000000D83U','@@@@',0,null,null,null,'N',0,26,'wa_classitem','薪资发放项目',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,0,null,-1,'N','pk_wa_item',-1,'pk_wa_item.isnhiitem_30',0,'N',1,'N','Y',32,null,0,'isnhiitem_30','hrwa.waitem.isnhiitem_30',null,'N',0,null,'1001Z71000000000D832','1001ZZ10000000000PGZ','@@@@',0,null,null,null,'N',1,32,'wa_classitem',null,0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,0,null,-1,'N','pk_wa_item',-1,'pk_wa_item.ishealthinsexsum_30',0,'N',1,'N','Y',32,null,0,'ishealthinsexsum_30','hrwa.waitem.ishealthinsexsum_30',null,'N',0,null,'1001Z71000000000D832','1001EXNHI00000000PGZ','@@@@',0,null,null,null,'N',1,32,'wa_classitem',null,0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'debitentry',0,'N',1,'N','Y',34,null,0,'debitentry','hrwa.wa_classitem.debitentry',null,'N',0,null,'1001Z71000000000D832','1001X21000000001KR2B','@@@@',0,'插入中间级-会计科目',null,null,'N',1,34,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'credisubject_b',0,'N',1,'N','Y',37,null,0,'credisubject_b','hrwa.wa_classitem.credisubject_b',null,'N',0,null,'1001Z71000000000D832','1001X21000000001KR2C','@@@@',0,null,null,null,'N',1,37,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'debitentry_b',0,'N',1,'N','Y',35,null,0,'debitentry_b','hrwa.wa_classitem.debitentry_b',null,'N',0,null,'1001Z71000000000D832','1001X21000000001KR2D','@@@@',0,null,null,null,'N',1,35,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'trano',0,'N',1,'N','Y',38,null,0,'trano','hrwa.wa_classitem.trano',null,'N',0,null,'1001Z71000000000D832','1001X21000000001KR2E','@@@@',0,null,null,null,'N',1,38,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'creditsubject',0,'N',1,'N','Y',36,null,0,'creditsubject','hrwa.wa_classitem.creditsubject',null,'N',0,null,'1001Z71000000000D832','1001X21000000001KR2F','@@@@',0,null,null,null,'N',1,36,'wa_classitem','wa_classitem',0,'2018-08-04 14:43:06','N',null,null,null,1,1,'N',1,null,1)
/


insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrwa.wa_classitem',null,2,'1001Z71000000000D832','1001ZZ10000000021A67',null,2,2,'UC001-0000095','AuditInfo',0,'审计信息','2018-08-04 14:43:13',null,null,null)
/
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrwa.wa_classitem','wa_classitem',null,'1001Z71000000000D832','1001ZZ10000000021A68',null,0,0,'160130payitem0006','wa_classitem',0,'薪资发放项目','2018-08-04 14:43:13',null,null,null)
/
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( 'wa_classitem',0,'hrwa.wa_classitem',null,null,'1001Z71000000000D832','1001ZZ10000000021A69',null,0,0,'160130glbitem0009','datasource',1,'项目数据来源','2018-08-04 14:43:13',null,null,null)
/
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( 'wa_classitem',0,'hrwa.wa_classitem',null,null,'1001Z71000000000D832','1001ZZ10000000021A6A',null,0,0,'160130payitem0001','closeoff',2,'结转设置','2018-08-04 14:43:13',null,null,null)
/
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( 'wa_classitem',0,null,null,null,'1001Z71000000000D832','1001ZZ10000000021A6B',null,0,0,'160130glbitem0010','prealert',3,'预警条件设置','2018-08-04 14:43:13',null,null,null)
/
