/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.wa.category;

import nc.hr.utils.MultiLangHelper;
import nc.vo.jcom.lang.StringUtil;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.wa.grade.WaPsnhiBVO;
import nc.vo.wa.grade.WaPsnhiVO;
import nc.vo.wa.periodsate.WaPeriodstateVO;
import nc.vo.wa.unitclass.UnitClassVO;

import org.apache.commons.lang.ArrayUtils;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:2009-11-12 15:37:51
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WaClassVO extends SuperVO {
	private java.lang.String pk_wa_class;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.String name2;
	private java.lang.String name3;
	private java.lang.String name4;
	private java.lang.String name5;
	private java.lang.String name6;
	private java.lang.String pk_country;
	
	
	public java.lang.String getPk_country() {
		return pk_country;
	}

	public void setPk_country(java.lang.String pk_country) {
		this.pk_country = pk_country;
	}

	public static final String TABLE_NAME = "wa_waclass";
	public java.lang.String getName4() {
		return name4;
	}

	public void setName4(java.lang.String name4) {
		this.name4 = name4;
	}

	public java.lang.String getName5() {
		return name5;
	}

	public void setName5(java.lang.String name5) {
		this.name5 = name5;
	}

	public java.lang.String getName6() {
		return name6;
	}

	public void setName6(java.lang.String name6) {
		this.name6 = name6;
	}

	private java.lang.String pk_periodscheme;
	private java.lang.String currid;
	private java.lang.String taxcurrid;

	private java.lang.String displaytaxitem;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	//该薪资方案的业务年度与业务期间（最新年度与最新期间）
	private java.lang.String cyear;
	private java.lang.String cperiod;
	
	private java.lang.String startyear;
	private java.lang.Integer  idisplayorder = 1;
	
	//记录当前方案的父方案
	private java.lang.String pk_prnt_class = null;
	//记录最新发放次
	private java.lang.Integer  batch = null;
	private java.lang.Integer  taxmode = 1;
	
	//打印模板
	private java.lang.String startyearperiod;
	
	
	
	public java.lang.Integer getTaxmode() {
		return taxmode;
	}

	public void setTaxmode(java.lang.Integer taxmode) {
		this.taxmode = taxmode;
	}

	public java.lang.Integer getIdisplayorder() {
		return idisplayorder;
	}

	public void setIdisplayorder(java.lang.Integer idisplayorder) {
		this.idisplayorder = idisplayorder;
	}

	/**
	 * @author zhangg on 2010-7-1 
	 * @return the startyear
	 */
	public java.lang.String getStartyear() {
		return startyear;
	}

	/**
	 * @author zhangg on 2010-7-1 
	 * @param startyear the startyear to set
	 */
	public void setStartyear(java.lang.String startyear) {
		this.startyear = startyear;
	}

	/**
	 * @author zhangg on 2010-7-1 
	 * @return the startperiod
	 */
	public java.lang.String getStartperiod() {
		return startperiod;
	}

	/**
	 * @author zhangg on 2010-7-1 
	 * @param startperiod the startperiod to set
	 */
	public void setStartperiod(java.lang.String startperiod) {
		this.startperiod = startperiod;
	}

	private java.lang.String startperiod;
	private nc.vo.pub.lang.UFBoolean voucherflag;
	private nc.vo.pub.lang.UFBoolean collectflag;

	private nc.vo.pub.lang.UFBoolean addflag;
	private nc.vo.pub.lang.UFBoolean checkflowflag;
	private nc.vo.pub.lang.UFBoolean isapporve;
	private nc.vo.pub.lang.UFBoolean stopflag;

	private nc.vo.pub.lang.UFBoolean mutipleflag = UFBoolean.FALSE;
	
	private nc.vo.pub.lang.UFBoolean leaveflag = UFBoolean.FALSE;
	
	//add by ward 2018-01-15 begin
	private String declareform;//申报格式
	
	private UFBoolean isferry=UFBoolean.FALSE;//是否福委
	//end 
	public nc.vo.pub.lang.UFBoolean getLeaveflag() {
		return leaveflag;
	}

	public void setLeaveflag(nc.vo.pub.lang.UFBoolean leaveflag) {
		this.leaveflag = leaveflag;
	}

	public nc.vo.pub.lang.UFBoolean getMutipleTrueflag() {
		return UFBoolean.TRUE;
	}
	
	public nc.vo.pub.lang.UFBoolean getMutipleflag() {
		return mutipleflag;
	}

	public void setMutipleflag(nc.vo.pub.lang.UFBoolean mutipleflag) {
		this.mutipleflag = mutipleflag;
	}

	public nc.vo.pub.lang.UFBoolean getShowflag() {
		return showflag;
	}

	public void setShowflag(nc.vo.pub.lang.UFBoolean showflag) {
		this.showflag = showflag;
	}

	private nc.vo.pub.lang.UFBoolean showflag = UFBoolean.TRUE;
    private String rangeRule;

	private WaPsnhiVO[] waPsnhiVOs = null;
	
	

	public WaPsnhiVO[] getWaPsnhiVOs() {
		return waPsnhiVOs;
	}

	public void setWaPsnhiVOs(WaPsnhiVO[] waPsnhiVOs) {
		this.waPsnhiVOs = waPsnhiVOs;
	}

	//薪资方案关联的总账
	
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	private UnitClassVO[] unitclassvos;
	private WaInludeclassVO[] waInludeclassVO;
	public WaInludeclassVO[] getWaInludeclassVO() {
		return waInludeclassVO;
	}

	public void setWaInludeclassVO(WaInludeclassVO[] waInludeclassVO) {
		this.waInludeclassVO = waInludeclassVO;
	}
	
	private WaFiorgVO[]  waclassFiorgvo = null;
	

	public WaFiorgVO[] getWaclassFiorgvo() {
		return waclassFiorgvo;
	}

	public void setWaclassFiorgvo(WaFiorgVO[] waclassFiorgvo) {
		this.waclassFiorgvo = waclassFiorgvo;
	}

	private WaPeriodstateVO[] periodstates;
	private AssignclsVO[] assignclavos;

	private WaPsnhiBVO[] waPsnhiBVOs;

	public WaPsnhiBVO[] getWaPsnhiBVOs() {
		return waPsnhiBVOs;
	}

	public void setWaPsnhiBVOs(WaPsnhiBVO[] waPsnhiBVOs) {
		this.waPsnhiBVOs = waPsnhiBVOs;
	}

	public AssignclsVO[] getAssignclavos() {
		return assignclavos;
	}

	public void setAssignclavos(AssignclsVO[] assignclavos) {
		this.assignclavos = assignclavos;
	}

	public WaPeriodstateVO[] getPeriodstates() {
		return periodstates;
	}

	public void setPeriodstates(WaPeriodstateVO[] periodstates) {
		this.periodstates = periodstates;
	}

	public java.lang.String getStartyearperiod() {
		if (StringUtil.isEmpty(getStartyear())) {
			return null;
		}
		return getStartyear() + getStartperiod();
	}

	public void setStartyearperiod(java.lang.String startyearperiod) {
		if(startyearperiod!=null&&startyearperiod.length()>0){
			this.setStartyear(startyearperiod.substring(0, 4));
			this.setStartperiod(startyearperiod.substring(4));
		}
	}

	public static final String PK_WA_CLASS = "pk_wa_class";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String CODE = "code";
	public static final String NAME = "name";
	public static final String NAME2 = "name2";
	public static final String NAME3 = "name3";
	public static final String PK_PERIODSCHEME = "pk_periodscheme";
	public static final String CURRID = "currid";
	public static final String TAXCURRID = "taxcurrid";

	public static final String RANGERULE = "rangeRule";

	public static final String TAXTABLEID = "taxtableid";
	public static final String DISPLAYTAXITEM = "displaytaxitem";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String CYEAR = "cyear";
	public static final String CPERIOD = "cperiod";
	public static final String STARTYEAR = "startyear";
	public static final String STARTPERIOD = "startperiod";
	public static final String VOUCHERFLAG = "voucherflag";
	public static final String COLLECTFLAG = "collectflag";
	public static final String CHECKFLOWFLAG = "checkflowflag";
	public static final String ISAPPORVE = "isapporve";
	public static final String ADDFLAG = "addflag";
	public static final String STOPFLAG = "stopflag";
	public static final String SEALYEARMONTH = "sealyearmonth";

	public static final String STARTYEARPERIOD = "startyearperiod";
	public static final String WARANGE = "waRange";
	public static final String IDISPLAYORDER = "idisplayorder";
	
	public static final String MUTIPLEFLAG = "mutipleflag";
	public static final String SHOWFLAG = "showflag";

	public static final String WAFIORG = "fiorg";
	public static final String LEAVEFLAG="leaveflag";
	//add by ward 2018-01-15 begin
	public static final String DECLAREFORM="declareform";
	public static final String ISFERRY="isferry";
	//end 

	/**
	 * 属性pk_wa_class的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_wa_class() {
		return pk_wa_class;
	}

	/**
	 * 属性pk_wa_class的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newPk_wa_class
	 *            java.lang.String
	 */
	public void setPk_wa_class(java.lang.String newPk_wa_class) {
		this.pk_wa_class = newPk_wa_class;
	}

	/**
	 * 属性pk_group的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group() {
		return pk_group;
	}

	public java.lang.String getTaxcurrid() {
		return taxcurrid;
	}

	public void setTaxcurrid(java.lang.String taxcurrid) {
		this.taxcurrid = taxcurrid;
	}

	public String getRangeRuleCode() {

		return getStringRangRuleCode();
	}

	public String[] getRangeRulePK() {

		return getStringRangRulePK();
	}
	
	public String[] getWaFiorgPKs() {

		return getStringWaFiorPK();
	}

	private String getStringRangRuleCode() {
		WaPsnhiVO[] tempvos = getWaPsnhiVOs();
		if (ArrayUtils.isEmpty(tempvos)) {
			return null;
		}
		StringBuilder sbd = new StringBuilder();

		for (int index = 0; index < tempvos.length; index++) {
			sbd.append(tempvos[index].getAttributeValue(WaPsnhiVO.VFLDCODE));
			if (index < tempvos.length - 1) {
				sbd.append(",");
			}
		}

		return sbd.toString();
	}

	private String[] getStringRangRulePK() {
		WaPsnhiVO[] tempvos = getWaPsnhiVOs();
		if (ArrayUtils.isEmpty(tempvos)) {
			return null;
		}
		String[] pks = new String[tempvos.length];
		for (int index = 0; index < tempvos.length; index++) {
			pks[index] = tempvos[index].getAttributeValue(WaPsnhiVO.PK_FLDDICT)
					.toString();

		}

		return pks;
	}
	
	
	private String[] getStringWaFiorPK() {
		WaFiorgVO[] tempvos = getWaclassFiorgvo();
		if (ArrayUtils.isEmpty(tempvos)) {
			return null;
		}
		String[] pks = new String[tempvos.length];
		for (int index = 0; index < tempvos.length; index++) {
			pks[index] = tempvos[index].getAttributeValue(WaFiorgVO.PK_FINANCEORG)
					.toString();

		}

		return pks;
	}

	/**
	 * 属性pk_group的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newPk_group
	 *            java.lang.String
	 */
	public void setPk_group(java.lang.String newPk_group) {
		this.pk_group = newPk_group;
	}

	/**
	 * 属性pk_org的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org() {
		return pk_org;
	}

	/**
	 * 属性pk_org的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newPk_org
	 *            java.lang.String
	 */
	public void setPk_org(java.lang.String newPk_org) {
		this.pk_org = newPk_org;
	}

	/**
	 * 属性code的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCode() {
		return code;
	}

	/**
	 * 属性code的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newCode
	 *            java.lang.String
	 */
	public void setCode(java.lang.String newCode) {
		this.code = newCode;
	}

	/**
	 * 属性name的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	public String getName()
    {
        return name;
    } 
	
	public String getMultilangName() {
		return MultiLangHelper.getName(this);
	}


	/**
	 * 属性name的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newName
	 *            java.lang.String
	 */
	public void setName(java.lang.String newName) {
		this.name = newName;
	}

	/**
	 * 属性name2的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getName2() {
		return name2;
	}

	/**
	 * 属性name2的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newName2
	 *            java.lang.String
	 */
	public void setName2(java.lang.String newName2) {
		this.name2 = newName2;
	}

	/**
	 * 属性name3的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getName3() {
		return name3;
	}

	/**
	 * 属性name3的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newName3
	 *            java.lang.String
	 */
	public void setName3(java.lang.String newName3) {
		this.name3 = newName3;
	}

	/**
	 * 属性pk_periodscheme的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_periodscheme() {
		return pk_periodscheme;
	}

	/**
	 * 属性pk_periodscheme的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newPk_periodscheme
	 *            java.lang.String
	 */
	public void setPk_periodscheme(java.lang.String newPk_periodscheme) {
		this.pk_periodscheme = newPk_periodscheme;
	}

	/**
	 * 属性currid的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCurrid() {
		return currid;
	}

	/**
	 * 属性currid的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newCurrid
	 *            java.lang.String
	 */
	public void setCurrid(java.lang.String newCurrid) {
		this.currid = newCurrid;
	}

	/**
	 * 属性displaytaxitem的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDisplaytaxitem() {
		return displaytaxitem;
	}

	/**
	 * 属性displaytaxitem的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newDisplaytaxitem
	 *            java.lang.String
	 */
	public void setDisplaytaxitem(java.lang.String newDisplaytaxitem) {
		this.displaytaxitem = newDisplaytaxitem;
	}

	/**
	 * 属性creator的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCreator() {
		return creator;
	}

	/**
	 * 属性creator的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newCreator
	 *            java.lang.String
	 */
	public void setCreator(java.lang.String newCreator) {
		this.creator = newCreator;
	}

	/**
	 * 属性creationtime的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime() {
		return creationtime;
	}

	/**
	 * 属性creationtime的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newCreationtime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime(nc.vo.pub.lang.UFDateTime newCreationtime) {
		this.creationtime = newCreationtime;
	}

	/**
	 * 属性modifier的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getModifier() {
		return modifier;
	}

	/**
	 * 属性modifier的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newModifier
	 *            java.lang.String
	 */
	public void setModifier(java.lang.String newModifier) {
		this.modifier = newModifier;
	}

	/**
	 * 属性modifiedtime的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime() {
		return modifiedtime;
	}

	/**
	 * 属性modifiedtime的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newModifiedtime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime(nc.vo.pub.lang.UFDateTime newModifiedtime) {
		this.modifiedtime = newModifiedtime;
	}

	/**
	 * 得到薪资方案已经结账到的最新的业务年
	 * @return java.lang.String
	 */
	public java.lang.String getCyear() {
		return cyear;
	}

	/**
	 * 属性cyear的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newCyear
	 *            java.lang.String
	 */
	public void setCyear(java.lang.String newCyear) {
		this.cyear = newCyear;
	}

	/**
	 * 得到薪资方案已经结账到的最新的业务期间

	 * @return java.lang.String
	 */
	public java.lang.String getCperiod() {
		return cperiod;
	}

	/**
	 * 属性cperiod的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newCperiod
	 *            java.lang.String
	 */
	public void setCperiod(java.lang.String newCperiod) {
		this.cperiod = newCperiod;
	}

	


	/**
	 * 属性checkflag的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.Integer
	 */
	/*
	 * public java.lang.Integer getCheckflag () { return checkflag; }
	 *//**
	 * 属性checkflag的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newCheckflag
	 *            java.lang.Integer
	 */
	/*
	 * public void setCheckflag (java.lang.Integer newCheckflag ) {
	 * this.checkflag = newCheckflag; }
	 */
	/**
	 * 属性voucherflag的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getVoucherflag() {
		return voucherflag;
	}

	/**
	 * 属性voucherflag的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newVoucherflag
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setVoucherflag(nc.vo.pub.lang.UFBoolean newVoucherflag) {
		this.voucherflag = newVoucherflag;
	}

	/**
	 * 属性collectflag的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getCollectflag() {
		return collectflag;
	}

	/**
	 * 属性collectflag的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newCollectflag
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setCollectflag(nc.vo.pub.lang.UFBoolean newCollectflag) {
		this.collectflag = newCollectflag;
	}

	/**
	 * 属性addflag的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getAddflag() {
		return addflag;
	}

	/**
	 * 属性addflag的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newAddflag
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setAddflag(nc.vo.pub.lang.UFBoolean newAddflag) {
		this.addflag = newAddflag;
	}

	/**
	 * 属性approvetype的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getCheckflowflag() {
		return checkflowflag;
	}

	/**
	 * 属性approvetype的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newApprovetype
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setCheckflowflag(nc.vo.pub.lang.UFBoolean newApprovetype) {
		this.checkflowflag = newApprovetype;
	}
	/**
	 * 属性isapporve的Getter方法. 创建日期:2013-10-16 10:37:51
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsapporve() {
		return isapporve;
	}

	/**
	 * 属性isapporve的Setter方法. 创建日期:2013-10-16 10:37:51
	 * 
	 * @param newIsapporve
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setIsapporve(nc.vo.pub.lang.UFBoolean newIsapporve) {
		this.isapporve = newIsapporve;
	}
	/**
	 * 属性sealflag的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getStopflag() {
		return stopflag;
	}

	/**
	 * 属性sealflag的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newSealflag
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setStopflag(nc.vo.pub.lang.UFBoolean newSealflag) {
		this.stopflag = newSealflag;
	}

	// /**
	// * 属性sealyearmonth的Getter方法.
	// * 创建日期:2009-11-12 15:37:51
	// * @return java.lang.String
	// */
	// public java.lang.String getSealyearmonth () {
	// return sealyearmonth;
	// }
	// /**
	// * 属性sealyearmonth的Setter方法.
	// * 创建日期:2009-11-12 15:37:51
	// * @param newSealyearmonth java.lang.String
	// */
	// public void setSealyearmonth (java.lang.String newSealyearmonth ) {
	// this.sealyearmonth = newSealyearmonth;
	// }
	/**
	 * 属性dr的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newDr
	 *            java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * 属性ts的Getter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法. 创建日期:2009-11-12 15:37:51
	 * 
	 * @param newTs
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getPKFieldName() {
		return "pk_wa_class";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2009-11-12 15:37:51
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getTableName() {
		return "wa_waclass";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2009-11-12 15:37:51
	 */
	public WaClassVO() {
		super();
	}

	public UnitClassVO[] getUnitclassvos() {
		return unitclassvos;
	}

	public void setUnitclassvos(UnitClassVO[] unitclassvos) {
		this.unitclassvos = unitclassvos;
	}

	@Override
	public String toString() {
		return getMultilangName() ;
	}

	public void setBatch(java.lang.Integer batch) {
		this.batch = batch;
	}

	public java.lang.Integer getBatch() {
		return batch;
	}

	public void setPk_prnt_class(java.lang.String pk_prnt_class) {
		this.pk_prnt_class = pk_prnt_class;
	}

	public java.lang.String getPk_prnt_class() {
		return pk_prnt_class;
	}

	public String getRangeRule() {
		return rangeRule;
	}

	public void setRangeRule(String rangeRule) {
		this.rangeRule = rangeRule;
	}

	public String getDeclareform() {
		return declareform;
	}

	public void setDeclareform(String declareform) {
		this.declareform = declareform;
	}

	public UFBoolean getIsferry() {
		return isferry;
	}

	public void setIsferry(UFBoolean isferry) {
		this.isferry = isferry;
	}
	
	
}
