insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,0,1,null,0,null,null,null,null,null,'pk_deptadj',null,null,'0001ZZ10000000057EYP','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-001',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '集团',5,1,1,null,0,null,null,null,null,null,'pk_group',null,null,'0001ZZ10000000057EYQ','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-002',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '人力资源组织',5,2,1,null,null,null,null,null,null,null,'pk_org',null,null,'0001ZZ10000000057EYR','N','Y','N','Y','N','N','N','N','Y','N','N','N','N','Y','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-003',2,null,null,'2018-11-06 12:45:22','N','#mainorg#')
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '业务单元版本',5,3,1,null,0,null,null,null,null,null,'pk_org_v',null,null,'0001ZZ10000000057EYS','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-004',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '用户',5,4,1,null,0,null,null,null,null,null,'creator',null,null,'0001ZZ10000000057EYT','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-005',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',8,5,1,null,0,null,null,null,null,null,'creationtime',null,null,'0001ZZ10000000057EYU','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-006',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '用户',5,6,1,null,0,null,null,null,null,null,'modifier',null,null,'0001ZZ10000000057EYV','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-007',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',8,7,1,null,0,null,null,null,null,null,'modifiedtime',null,null,'0001ZZ10000000057EYW','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-008',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,8,1,null,0,null,null,null,null,null,'adj_code',null,null,'0001ZZ10000000057EYX','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-009',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( 'HR部门版本',5,9,1,null,0,null,null,null,null,null,'pk_dept_v',null,null,'0001ZZ10000000057EYY','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-010',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',10,10,1,null,0,null,null,null,null,null,'effectivedate',null,null,'0001ZZ10000000057EYZ','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-011',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',4,11,1,null,0,null,null,null,null,null,'iseffective',null,null,'0001ZZ10000000057EZ0','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-012',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '部门HR',5,12,1,null,0,null,null,null,null,null,'pk_dept',null,null,'0001ZZ10000000057EZ1','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-013',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,13,1,null,0,null,null,null,null,null,'code',null,null,'0001ZZ10000000057EZ2','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-014',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,14,1,null,0,null,null,null,null,null,'name',null,null,'0001ZZ10000000057EZ3','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-015',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,15,1,null,0,null,null,null,null,null,'innercode',null,null,'0001ZZ10000000057EZ4','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-016',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '部门HR',5,16,1,null,0,null,null,null,null,null,'pk_fatherorg',null,null,'0001ZZ10000000057EZ5','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-017',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( 'IM,32d8fdf6-9428-40a2-8201-d10dc0efb3f9',6,17,1,null,0,null,null,null,null,null,'depttype',null,null,'0001ZZ10000000057EZ6','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@<>@','等于@不等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-018',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '部门级别(自定义档案)',5,18,1,null,0,null,null,null,null,null,'deptlevel',null,null,'0001ZZ10000000057EZ7','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-019',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,19,1,null,0,null,null,null,null,null,'deptduty',null,null,'0001ZZ10000000057EZ8','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-020',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',10,20,1,null,0,null,null,null,null,null,'createdate',null,null,'0001ZZ10000000057EZ9','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-021',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,21,1,null,0,null,null,null,null,null,'shortname',null,null,'0001ZZ10000000057EZA','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-022',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,22,1,null,0,null,null,null,null,null,'mnecode',null,null,'0001ZZ10000000057EZB','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-023',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',4,23,1,null,0,null,null,null,null,null,'hrcanceled',null,null,'0001ZZ10000000057EZC','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-024',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',10,24,1,null,0,null,null,null,null,null,'deptcanceldate',null,null,'0001ZZ10000000057EZD','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-025',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( 'IM,6b533ffa-3e43-4147-8670-ba0f5471fd40',6,25,1,null,0,null,null,null,null,null,'enablestate',null,null,'0001ZZ10000000057EZE','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@<>@','等于@不等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-026',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',1,26,1,null,0,null,null,null,null,null,'displayorder',null,null,'0001ZZ10000000057EZF','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-027',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( 'IM,28b94d24-6d65-4cc5-b6ac-ca1b638b0da3',6,27,1,null,0,null,null,null,null,null,'dataoriginflag',null,null,'0001ZZ10000000057EZG','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@<>@','等于@不等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-028',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',4,28,1,null,0,null,null,null,null,null,'orgtype13',null,null,'0001ZZ10000000057EZH','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-029',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',4,29,1,null,0,null,null,null,null,null,'orgtype17',null,null,'0001ZZ10000000057EZI','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-030',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( 'HR人员',5,30,1,null,0,null,null,null,null,null,'principal',null,null,'0001ZZ10000000057EZJ','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-031',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,31,1,null,0,null,null,null,null,null,'tel',null,null,'0001ZZ10000000057EZK','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-032',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '地址簿',5,32,1,null,0,null,null,null,null,null,'address',null,null,'0001ZZ10000000057EZL','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-033',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,33,1,null,0,null,null,null,null,null,'memo',null,null,'0001ZZ10000000057EZM','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-034',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',4,34,1,null,0,null,null,null,null,null,'islastversion',null,null,'0001ZZ10000000057EZN','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-035',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,35,1,null,0,null,null,null,null,null,'def1',null,null,'0001ZZ10000000057EZO','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-036',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,36,1,null,0,null,null,null,null,null,'def2',null,null,'0001ZZ10000000057EZP','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-037',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,37,1,null,0,null,null,null,null,null,'def3',null,null,'0001ZZ10000000057EZQ','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-038',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,38,1,null,0,null,null,null,null,null,'def4',null,null,'0001ZZ10000000057EZR','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-039',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,39,1,null,0,null,null,null,null,null,'def5',null,null,'0001ZZ10000000057EZS','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-040',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,40,1,null,0,null,null,null,null,null,'def6',null,null,'0001ZZ10000000057EZT','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-041',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,41,1,null,0,null,null,null,null,null,'def7',null,null,'0001ZZ10000000057EZU','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-042',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,42,1,null,0,null,null,null,null,null,'def8',null,null,'0001ZZ10000000057EZV','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-043',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,43,1,null,0,null,null,null,null,null,'def9',null,null,'0001ZZ10000000057EZW','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-044',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,44,1,null,0,null,null,null,null,null,'def10',null,null,'0001ZZ10000000057EZX','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-045',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,45,1,null,0,null,null,null,null,null,'def11',null,null,'0001ZZ10000000057EZY','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-046',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,46,1,null,0,null,null,null,null,null,'def12',null,null,'0001ZZ10000000057EZZ','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-047',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,47,1,null,0,null,null,null,null,null,'def13',null,null,'0001ZZ10000000057F00','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-048',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,48,1,null,0,null,null,null,null,null,'def14',null,null,'0001ZZ10000000057F01','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-049',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,49,1,null,0,null,null,null,null,null,'def15',null,null,'0001ZZ10000000057F02','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-050',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,50,1,null,0,null,null,null,null,null,'def16',null,null,'0001ZZ10000000057F03','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-051',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,51,1,null,0,null,null,null,null,null,'def17',null,null,'0001ZZ10000000057F04','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-052',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,52,1,null,0,null,null,null,null,null,'def18',null,null,'0001ZZ10000000057F05','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-053',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,53,1,null,0,null,null,null,null,null,'def19',null,null,'0001ZZ10000000057F06','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-054',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',0,54,1,null,0,null,null,null,null,null,'def20',null,null,'0001ZZ10000000057F07','N','Y','N','N',null,'N','N','N','N',null,'N','N','N','N','Y',null,'Y',9999,null,'=@like@left like@right like@','等于@包含@左包含@右包含@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-055',2,null,null,'2018-11-06 12:34:10',null,null)
/
insert into pub_query_condition(consult_code,data_type,disp_sequence,disp_type,disp_value,dr,ext1,ext2,ext3,ext4,ext5,field_code,field_name,guideline,id,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value) values( '-99',3,55,0,null,0,null,null,null,null,null,'billdate',null,null,'0001ZZ10000000057F08','N','Y','N','Y',null,'N','N','N','Y',null,'N','N','N','Y','Y',null,'Y',9999,null,'between@=@>@>=@<@<=@','介于@等于@大于@大于等于@小于@小于等于@',0,'@@@@','0001ZZ10000000057EYO',null,'deptadj-056',2,null,null,'2018-11-06 12:34:10',null,'#day(0)#,#day(0)#')
/
