/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.wa.item;

import java.io.Serializable;

import nc.md.model.IEnumValue;
import nc.md.model.impl.MDEnum;
import nc.vo.hr.itemsource.ItemPropertyConst;

/**
 * 薪资项目的数据来源类型
 * 
 * @author
 * @version NCPrj ??
 */
/**
 * @author sunsx_000
 * 
 */
public class FromEnumVO extends MDEnum implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 5943469387328909968L;

	public FromEnumVO(IEnumValue enumvalue) {
		super(enumvalue);
	}

	/**
	 * 公式(公式编辑器中的公式)
	 */
	public static final FromEnumVO FORMULA = MDEnum.valueOf(FromEnumVO.class,
			ItemPropertyConst.FORMULA);
	/**
	 * 薪资规则表
	 */
	public static final FromEnumVO WA_WAGEFORM = MDEnum.valueOf(
			FromEnumVO.class, ItemPropertyConst.WA_WAGEFORM);
	/**
	 * 手工输入
	 */
	public static final FromEnumVO USER_INPUT = MDEnum.valueOf(
			FromEnumVO.class, ItemPropertyConst.USER_INPUT);
	/**
	 * 固定值
	 */
	public static final FromEnumVO FIX_VALUE = MDEnum.valueOf(FromEnumVO.class,
			ItemPropertyConst.FIX_VALUE);
	/**
	 * 薪资标准表
	 */
	public static final FromEnumVO WA_GRADE = MDEnum.valueOf(FromEnumVO.class,
			ItemPropertyConst.WA_GRADE);
	/**
	 * 其他系统
	 */
	public static final FromEnumVO OTHER_SYSTEM = MDEnum.valueOf(
			FromEnumVO.class, ItemPropertyConst.OTHER_SYSTEM);

	/**
	 * 其他系统薪资
	 */
	public static final FromEnumVO WAORTHER = MDEnum.valueOf(FromEnumVO.class,
			ItemPropertyConst.WAORTHER);

	/**
	 * 其他系统人事
	 */
	public static final FromEnumVO HI = MDEnum.valueOf(FromEnumVO.class,
			ItemPropertyConst.HI);

	/**
	 * 数据来源 "发放次数汇总"
	 */
	public static final FromEnumVO TIMESCOLLECT = MDEnum.valueOf(
			FromEnumVO.class, ItemPropertyConst.TIMESCOLLECT);

	/**
	 * 其他系统考勤
	 */
	public static final FromEnumVO TA = MDEnum.valueOf(FromEnumVO.class,
			ItemPropertyConst.TA);

	/**
	 * 其他系统社保
	 */
	public static final FromEnumVO BM = MDEnum.valueOf(FromEnumVO.class,
			ItemPropertyConst.BM);

	/**
	 * 其他系统绩效
	 */
	public static final FromEnumVO PE = MDEnum.valueOf(FromEnumVO.class,
			ItemPropertyConst.PE);

	/**
	 * 外部数据源
	 */
	public static final FromEnumVO OTHERSOURCE= MDEnum.valueOf(FromEnumVO.class, ItemPropertyConst.OTHERSOURCE);

	/**
	 * 其他系统-劳健保参数设置 ssx added for TWHR on 2017-07-24
	 */
	public static final FromEnumVO TWHR = MDEnum.valueOf(FromEnumVO.class,
			ItemPropertyConst.TWBASEDOC);

	@Override
	public Integer value() {
		return (Integer) super.value();
	}

}
