/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ta.signcard;

import nc.vo.pub.lang.UFDateTime;
import nc.vo.ta.timebill.annotation.PkPsnjobFieldName;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:${vmObject.createdDate}
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
@PkPsnjobFieldName(fieldName="pk_psnjob")
public class SignbVO extends SignCommonVO{
	private java.lang.String pk_signb;
	private java.lang.String pk_signh;
	private java.lang.String transtypeid;//流程类型（批量新增时为在listView中显示）	
	private java.lang.String transtype;
	private String signarea;
	private String signshift;
	
	public static final String TRANSTYPEID = "transtypeid";
	public static final String TRANSTYPE = "transtype";
	public static final String PK_SIGNB = "pk_signb";
	public static final String PK_SIGNH = "pk_signh";
	public static final String SIGNAREA="signarea";
	public static final String SIGNSHIFT="signshift";	
	
	/**
	 * 属性pk_signb的Getter方法.
	 * 创建日期:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getPk_signb () {
		return pk_signb;
	}   
	/**
	 * 属性pk_signb的Setter方法.
	 * 创建日期:$vmObject.createdDate
	 * @param newPk_signb java.lang.String
	 */
	public void setPk_signb (java.lang.String newPk_signb ) {
	 	this.pk_signb = newPk_signb;
	} 	  
	/**
	 * 属性pk_signh的Getter方法.
	 * 创建日期:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getPk_signh () {
		return pk_signh;
	}   
	/**
	 * 属性pk_signh的Setter方法.
	 * 创建日期:$vmObject.createdDate
	 * @param newPk_signh java.lang.String
	 */
	public void setPk_signh (java.lang.String newPk_signh ) {
	 	this.pk_signh = newPk_signh;
	} 	  
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:${vmObject.createdDate}
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_signb";
	}
    
	public java.lang.String getTranstype() {
		return transtype;
	}
	public void setTranstype(java.lang.String transtype) {
		this.transtype = transtype;
	}
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:${vmObject.createdDate}
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "tbm_signb";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:${vmObject.createdDate}
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "tbm_signb";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:${vmObject.createdDate}
	  */
     public SignbVO() {
		super();	
	}
    
   //处理人
    public String getCreator (){
    	return null;
    }
 	
  //处理日期
 	public UFDateTime getCreationtime(){
 		return null;
 	}
	public java.lang.String getTranstypeid() {
		return transtypeid;
	}
	public void setTranstypeid(java.lang.String transtypeid) {
		this.transtypeid = transtypeid;
	}
	@Override
	public boolean isAppBill() {
		return true;
	}
	@Override
	public void setAppBill(boolean isAppBill) {
		
	}
	public String getSignarea() {
		return signarea;
	}
	public void setSignarea(String signarea) {
		this.signarea = signarea;
	}
	public String getSignshift() {
		return signshift;
	}
	public void setSignshift(String signshift) {
		this.signshift = signshift;
	}
} 


