/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.bd.workcalendrule;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class WorkCalendarRuleVO extends SuperVO {
	private java.lang.String pk_workcalendrule;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String code;
	private java.lang.String name;
	private java.lang.String name2;
	private java.lang.String name3;
	private java.lang.String name4;
	private java.lang.String name5;
	private java.lang.String name6;
	private java.lang.String ondutytime;
	private java.lang.String offdutytime;
	private java.lang.String memo;
	private nc.vo.pub.lang.UFBoolean sunday;
	private nc.vo.pub.lang.UFBoolean monday;
	private nc.vo.pub.lang.UFBoolean tuesday;
	private nc.vo.pub.lang.UFBoolean wednesday;
	private nc.vo.pub.lang.UFBoolean thursday;
	private nc.vo.pub.lang.UFBoolean friday;
	private nc.vo.pub.lang.UFBoolean saturday;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.Integer dataoriginflag = 0;
	private nc.vo.pub.lang.UFBoolean sunday1;
	private nc.vo.pub.lang.UFBoolean monday1;
	private nc.vo.pub.lang.UFBoolean tuesday1;
	private nc.vo.pub.lang.UFBoolean wednesday1;
	private nc.vo.pub.lang.UFBoolean thursday1;
	private nc.vo.pub.lang.UFBoolean friday1;
	private nc.vo.pub.lang.UFBoolean saturday1;
	
	private nc.vo.pub.lang.UFBoolean sunday2;
	private nc.vo.pub.lang.UFBoolean monday2;
	private nc.vo.pub.lang.UFBoolean tuesday2;
	private nc.vo.pub.lang.UFBoolean wednesday2;
	private nc.vo.pub.lang.UFBoolean thursday2;
	private nc.vo.pub.lang.UFBoolean friday2;
	private nc.vo.pub.lang.UFBoolean saturday2;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_WORKCALENDRULE = "pk_workcalendrule";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String CODE = "code";
	public static final String NAME = "name";
	public static final String NAME2 = "name2";
	public static final String NAME3 = "name3";
	public static final String NAME4 = "name4";
	public static final String NAME5 = "name5";
	public static final String NAME6 = "name6";
	public static final String ONDUTYTIME = "ondutytime";
	public static final String OFFDUTYTIME = "offdutytime";
	public static final String MEMO = "memo";
	public static final String SUNDAY = "sunday";
	public static final String MONDAY = "monday";
	public static final String TUESDAY = "tuesday";
	public static final String WEDNESDAY = "wednesday";
	public static final String THURSDAY = "thursday";
	public static final String FRIDAY = "friday";
	public static final String SATURDAY = "saturday";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String DATAORIGINFLAG = "dataoriginflag";
	public static final String SUNDAY1 = "sunday1";
	public static final String MONDAY1 = "monday1";
	public static final String TUESDAY1 = "tuesday1";
	public static final String WEDNESDAY1 = "wednesday1";
	public static final String THURSDAY1 = "thursday1";
	public static final String FRIDAY1 = "friday1";
	public static final String SATURDAY1 = "saturday1";
	
	public static final String SUNDAY2 = "sunday2";
	public static final String MONDAY2 = "monday2";
	public static final String TUESDAY2 = "tuesday2";
	public static final String WEDNESDAY2 = "wednesday2";
	public static final String THURSDAY2 = "thursday2";
	public static final String FRIDAY2 = "friday2";
	public static final String SATURDAY2= "saturday2";
			
	/**
	 * 属性pk_workcalendrule的Getter方法.属性名：主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_workcalendrule () {
		return pk_workcalendrule;
	}   
	/**
	 * 属性pk_workcalendrule的Setter方法.属性名：主键
	 * 创建日期:
	 * @param newPk_workcalendrule java.lang.String
	 */
	public void setPk_workcalendrule (java.lang.String newPk_workcalendrule ) {
	 	this.pk_workcalendrule = newPk_workcalendrule;
	} 	  
	/**
	 * 属性pk_group的Getter方法.属性名：所属集团
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**3333
	 * 属性pk_group的Setter方法.属性名：所属集团
	 * 创建日期:
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.属性名：所属组织
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.属性名：所属组织
	 * 创建日期:
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性code的Getter方法.属性名：工作日历规则编码
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCode () {
		return code;
	}   
	/**
	 * 属性code的Setter方法.属性名：工作日历规则编码
	 * 创建日期:
	 * @param newCode java.lang.String
	 */
	public void setCode (java.lang.String newCode ) {
	 	this.code = newCode;
	} 	  
	/**
	 * 属性name的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName java.lang.String
	 */
	public void setName (java.lang.String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性name2的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName2 () {
		return name2;
	}   
	/**
	 * 属性name2的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName2 java.lang.String
	 */
	public void setName2 (java.lang.String newName2 ) {
	 	this.name2 = newName2;
	} 	  
	/**
	 * 属性name3的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName3 () {
		return name3;
	}   
	/**
	 * 属性name3的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName3 java.lang.String
	 */
	public void setName3 (java.lang.String newName3 ) {
	 	this.name3 = newName3;
	} 	  
	/**
	 * 属性name4的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName4 () {
		return name4;
	}   
	/**
	 * 属性name4的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName4 java.lang.String
	 */
	public void setName4 (java.lang.String newName4 ) {
	 	this.name4 = newName4;
	} 	  
	/**
	 * 属性name5的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName5 () {
		return name5;
	}   
	/**
	 * 属性name5的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName5 java.lang.String
	 */
	public void setName5 (java.lang.String newName5 ) {
	 	this.name5 = newName5;
	} 	  
	/**
	 * 属性name6的Getter方法.属性名：$map.displayName
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getName6 () {
		return name6;
	}   
	/**
	 * 属性name6的Setter方法.属性名：$map.displayName
	 * 创建日期:
	 * @param newName6 java.lang.String
	 */
	public void setName6 (java.lang.String newName6 ) {
	 	this.name6 = newName6;
	} 	  
	/**
	 * 属性ondutytime的Getter方法.属性名：上班时间
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOndutytime () {
		return ondutytime;
	}   
	/**
	 * 属性ondutytime的Setter方法.属性名：上班时间
	 * 创建日期:
	 * @param newOndutytime java.lang.String
	 */
	public void setOndutytime (java.lang.String newOndutytime ) {
	 	this.ondutytime = newOndutytime;
	} 	  
	/**
	 * 属性offdutytime的Getter方法.属性名：下班时间
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getOffdutytime () {
		return offdutytime;
	}   
	/**
	 * 属性offdutytime的Setter方法.属性名：下班时间
	 * 创建日期:
	 * @param newOffdutytime java.lang.String
	 */
	public void setOffdutytime (java.lang.String newOffdutytime ) {
	 	this.offdutytime = newOffdutytime;
	} 	  
	/**
	 * 属性memo的Getter方法.属性名：备注
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.属性名：备注
	 * 创建日期:
	 * @param newMemo java.lang.String
	 */
	public void setMemo (java.lang.String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性sunday的Getter方法.属性名：周日
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getSunday () {
		return sunday;
	}   
	/**
	 * 属性sunday的Setter方法.属性名：周日
	 * 创建日期:
	 * @param newSunday nc.vo.pub.lang.UFBoolean
	 */
	public void setSunday (nc.vo.pub.lang.UFBoolean newSunday ) {
	 	this.sunday = newSunday;
	} 	  
	/**
	 * 属性monday的Getter方法.属性名：周一
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getMonday () {
		return monday;
	}   
	/**
	 * 属性monday的Setter方法.属性名：周一
	 * 创建日期:
	 * @param newMonday nc.vo.pub.lang.UFBoolean
	 */
	public void setMonday (nc.vo.pub.lang.UFBoolean newMonday ) {
	 	this.monday = newMonday;
	} 	  
	/**
	 * 属性tuesday的Getter方法.属性名：周二
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getTuesday () {
		return tuesday;
	}   
	/**
	 * 属性tuesday的Setter方法.属性名：周二
	 * 创建日期:
	 * @param newTuesday nc.vo.pub.lang.UFBoolean
	 */
	public void setTuesday (nc.vo.pub.lang.UFBoolean newTuesday ) {
	 	this.tuesday = newTuesday;
	} 	  
	/**
	 * 属性wednesday的Getter方法.属性名：周三
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getWednesday () {
		return wednesday;
	}   
	/**
	 * 属性wednesday的Setter方法.属性名：周三
	 * 创建日期:
	 * @param newWednesday nc.vo.pub.lang.UFBoolean
	 */
	public void setWednesday (nc.vo.pub.lang.UFBoolean newWednesday ) {
	 	this.wednesday = newWednesday;
	} 	  
	/**
	 * 属性thursday的Getter方法.属性名：周四
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getThursday () {
		return thursday;
	}   
	/**
	 * 属性thursday的Setter方法.属性名：周四
	 * 创建日期:
	 * @param newThursday nc.vo.pub.lang.UFBoolean
	 */
	public void setThursday (nc.vo.pub.lang.UFBoolean newThursday ) {
	 	this.thursday = newThursday;
	} 	  
	/**
	 * 属性friday的Getter方法.属性名：周五
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getFriday () {
		return friday;
	}   
	/**
	 * 属性friday的Setter方法.属性名：周五
	 * 创建日期:
	 * @param newFriday nc.vo.pub.lang.UFBoolean
	 */
	public void setFriday (nc.vo.pub.lang.UFBoolean newFriday ) {
	 	this.friday = newFriday;
	} 	  
	/**
	 * 属性saturday的Getter方法.属性名：周六
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getSaturday () {
		return saturday;
	}   
	/**
	 * 属性saturday的Setter方法.属性名：周六
	 * 创建日期:
	 * @param newSaturday nc.vo.pub.lang.UFBoolean
	 */
	public void setSaturday (nc.vo.pub.lang.UFBoolean newSaturday ) {
	 	this.saturday = newSaturday;
	} 	  
	/**
	 * 属性creator的Getter方法.属性名：创建人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * 属性creator的Setter方法.属性名：创建人
	 * 创建日期:
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * 属性creationtime的Getter方法.属性名：创建时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * 属性creationtime的Setter方法.属性名：创建时间
	 * 创建日期:
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * 属性modifier的Getter方法.属性名：最后修改人
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * 属性modifier的Setter方法.属性名：最后修改人
	 * 创建日期:
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * 属性modifiedtime的Getter方法.属性名：最后修改时间
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * 属性modifiedtime的Setter方法.属性名：最后修改时间
	 * 创建日期:
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * 属性dataoriginflag的Getter方法.属性名：分布式
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDataoriginflag () {
		return dataoriginflag;
	}   
	/**
	 * 属性dataoriginflag的Setter方法.属性名：分布式
	 * 创建日期:
	 * @param newDataoriginflag java.lang.Integer
	 */
	public void setDataoriginflag (java.lang.Integer newDataoriginflag ) {
	 	this.dataoriginflag = newDataoriginflag;
	} 	  
	/**
	 * 属性sunday1的Getter方法.属性名：周日1
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getSunday1 () {
		return sunday1;
	}   
	/**
	 * 属性sunday1的Setter方法.属性名：周日1
	 * 创建日期:
	 * @param newSunday1 nc.vo.pub.lang.UFBoolean
	 */
	public void setSunday1 (nc.vo.pub.lang.UFBoolean newSunday1 ) {
	 	this.sunday1 = newSunday1;
	} 	  
	/**
	 * 属性monday1的Getter方法.属性名：周一1
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getMonday1 () {
		return monday1;
	}   
	/**
	 * 属性monday1的Setter方法.属性名：周一1
	 * 创建日期:
	 * @param newMonday1 nc.vo.pub.lang.UFBoolean
	 */
	public void setMonday1 (nc.vo.pub.lang.UFBoolean newMonday1 ) {
	 	this.monday1 = newMonday1;
	} 	  
	/**
	 * 属性tuesday1的Getter方法.属性名：周二1
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getTuesday1 () {
		return tuesday1;
	}   
	/**
	 * 属性tuesday1的Setter方法.属性名：周二1
	 * 创建日期:
	 * @param newTuesday1 nc.vo.pub.lang.UFBoolean
	 */
	public void setTuesday1 (nc.vo.pub.lang.UFBoolean newTuesday1 ) {
	 	this.tuesday1 = newTuesday1;
	} 	  
	/**
	 * 属性wednesday1的Getter方法.属性名：周三1
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getWednesday1 () {
		return wednesday1;
	}   
	/**
	 * 属性wednesday1的Setter方法.属性名：周三1
	 * 创建日期:
	 * @param newWednesday1 nc.vo.pub.lang.UFBoolean
	 */
	public void setWednesday1 (nc.vo.pub.lang.UFBoolean newWednesday1 ) {
	 	this.wednesday1 = newWednesday1;
	} 	  
	/**
	 * 属性thursday1的Getter方法.属性名：周四1
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getThursday1 () {
		return thursday1;
	}   
	/**
	 * 属性thursday1的Setter方法.属性名：周四1
	 * 创建日期:
	 * @param newThursday1 nc.vo.pub.lang.UFBoolean
	 */
	public void setThursday1 (nc.vo.pub.lang.UFBoolean newThursday1 ) {
	 	this.thursday1 = newThursday1;
	} 	  
	/**
	 * 属性friday1的Getter方法.属性名：周五1
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getFriday1 () {
		return friday1;
	}   
	/**
	 * 属性friday1的Setter方法.属性名：周五1
	 * 创建日期:
	 * @param newFriday1 nc.vo.pub.lang.UFBoolean
	 */
	public void setFriday1 (nc.vo.pub.lang.UFBoolean newFriday1 ) {
	 	this.friday1 = newFriday1;
	} 	  
	/**
	 * 属性saturday1的Getter方法.属性名：周六1
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getSaturday1 () {
		return saturday1;
	}   
	/**
	 * 属性saturday1的Setter方法.属性名：周六1
	 * 创建日期:
	 * @param newSaturday1 nc.vo.pub.lang.UFBoolean
	 */
	public void setSaturday1 (nc.vo.pub.lang.UFBoolean newSaturday1 ) {
	 	this.saturday1 = newSaturday1;
	} 	  
	
	/**
	 * 属性sunday2的Getter方法.属性名：周日2
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getSunday2 () {
		return sunday2;
	}   
	/**
	 * 属性sunday2的Setter方法.属性名：周日2
	 * 创建日期:
	 * @param newSunday2 nc.vo.pub.lang.UFBoolean
	 */
	public void setSunday2 (nc.vo.pub.lang.UFBoolean newSunday2 ) {
	 	this.sunday2 = newSunday2;
	} 	  
	/**
	 * 属性monday2的Getter方法.属性名：周一2
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getMonday2 () {
		return monday2;
	}   
	/**
	 * 属性monday2的Setter方法.属性名：周一2
	 * 创建日期:
	 * @param newMonday2 nc.vo.pub.lang.UFBoolean
	 */
	public void setMonday2 (nc.vo.pub.lang.UFBoolean newMonday2 ) {
	 	this.monday2 = newMonday2;
	} 	  
	/**
	 * 属性tuesday2的Getter方法.属性名：周二2
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getTuesday2 () {
		return tuesday2;
	}   
	/**
	 * 属性tuesday2的Setter方法.属性名：周二2
	 * 创建日期:
	 * @param newTuesday2 nc.vo.pub.lang.UFBoolean
	 */
	public void setTuesday2 (nc.vo.pub.lang.UFBoolean newTuesday2 ) {
	 	this.tuesday2 = newTuesday2;
	} 	  
	/**
	 * 属性wednesday2的Getter方法.属性名：周三2
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getWednesday2 () {
		return wednesday2;
	}   
	/**
	 * 属性wednesday2的Setter方法.属性名：周三2
	 * 创建日期:
	 * @param newWednesday2 nc.vo.pub.lang.UFBoolean
	 */
	public void setWednesday2 (nc.vo.pub.lang.UFBoolean newWednesday2 ) {
	 	this.wednesday2 = newWednesday2;
	} 	  
	/**
	 * 属性thursday2的Getter方法.属性名：周四2
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getThursday2 () {
		return thursday2;
	}   
	/**
	 * 属性thursday2的Setter方法.属性名：周四2
	 * 创建日期:
	 * @param newThursday2 nc.vo.pub.lang.UFBoolean
	 */
	public void setThursday2 (nc.vo.pub.lang.UFBoolean newThursday2 ) {
	 	this.thursday2 = newThursday2;
	} 	  
	/**
	 * 属性friday2的Getter方法.属性名：周五2
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getFriday2 () {
		return friday2;
	}   
	/**
	 * 属性friday2的Setter方法.属性名：周五2
	 * 创建日期:
	 * @param newFriday2 nc.vo.pub.lang.UFBoolean
	 */
	public void setFriday2 (nc.vo.pub.lang.UFBoolean newFriday2 ) {
	 	this.friday2 = newFriday2;
	} 	  
	/**
	 * 属性saturday2的Getter方法.属性名：周六2
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getSaturday2 () {
		return saturday2;
	}   
	/**
	 * 属性saturday2的Setter方法.属性名：周六2
	 * 创建日期:
	 * @param newSaturday2 nc.vo.pub.lang.UFBoolean
	 */
	public void setSaturday2 (nc.vo.pub.lang.UFBoolean newSaturday2 ) {
	 	this.saturday2 = newSaturday2;
	} 	  
	
	
	/**
	 * 属性dr的Getter方法.属性名：dr
	 * 创建日期:
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.属性名：dr
	 * 创建日期:
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.属性名：ts
	 * 创建日期:
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.属性名：ts
	 * 创建日期:
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_workcalendrule";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "bd_workcalendrule";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "bd_workcalendrule";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:
	  */
     public WorkCalendarRuleVO() {
		super();	
	}    
	
	@nc.vo.annotation.MDEntityInfo(beanFullclassName =  "nc.vo.bd.workcalendrule.WorkCalendarRuleVO" )
	public IVOMeta getMetaData() {
   		return null;
  	}
} 


