create table om_deptadj (
pk_deptadj char(20) NOT NULL,
pk_group varchar(20) default '~' NULL,
pk_org varchar(20) default '~' NULL,
pk_org_v varchar(20) default '~' NULL,
creator varchar(20) default '~' NULL,
creationtime char(19) NULL,
modifier varchar(20) default '~' NULL,
modifiedtime char(19) NULL,
adj_code varchar(50) NULL,
pk_dept_v varchar(20) default '~' NULL,
effectivedate char(10) NOT NULL,
iseffective char(1) NULL,
pk_dept varchar(50) NULL,
code varchar(50) NULL,
name varchar(50) NULL,
innercode varchar(50) NULL,
pk_fatherorg varchar(20) default '~' NULL,
depttype smallint NULL,
deptlevel varchar(20) default '~' NULL,
deptduty varchar(200) NULL,
createdate char(10) NULL,
shortname varchar(50) NULL,
mnecode varchar(50) NULL,
hrcanceled char(1) NULL,
deptcanceldate char(10) NULL,
enablestate int NULL,
displayorder int NULL,
dataoriginflag int NULL,
orgtype13 char(1) NULL,
orgtype17 char(1) NULL,
principal varchar(20) default '~' NULL,
tel varchar(50) NULL,
address varchar(20) default '~' NULL,
memo varchar(200) NULL,
islastversion char(1) NULL,
def1 varchar(100) NULL,
def2 varchar(100) NULL,
def3 varchar(100) NULL,
def4 varchar(100) NULL,
def5 varchar(100) NULL,
def6 varchar(100) NULL,
def7 varchar(100) NULL,
def8 varchar(100) NULL,
def9 varchar(100) NULL,
def10 varchar(100) NULL,
def11 varchar(100) NULL,
def12 varchar(100) NULL,
def13 varchar(100) NULL,
def14 varchar(100) NULL,
def15 varchar(100) NULL,
def16 varchar(100) NULL,
def17 varchar(100) NULL,
def18 varchar(100) NULL,
def19 varchar(100) NULL,
def20 varchar(100) NULL,
billdate char(19) NULL,
CONSTRAINT PK_OM_DEPTADJ PRIMARY KEY (pk_deptadj),
ts char(19) NULL,
dr smallint default 0 
)


