
delete pub_billtemplet_t where ( pk_billtemplet in ('1001Z710000000006DXV') and (dr=0 or dr is null) );


delete pub_billtemplet_b where ( pk_billtemplet in ('1001Z710000000006DXV') and (dr=0 or dr is null) );


delete pub_billtemplet where ( pk_billtemplet='1001Z710000000006DXV' and (bill_templetname='SYSTEM') and (dr=0 or dr is null) );



insert into pub_billtemplet(bill_templetcaption,bill_templetname,devorg,dividerproportion,dr,funccode,layer,metadataclass,model_type,modulecode,nodecode,options,pk_billtemplet,pk_billtypecode,pk_corp,pk_org,resid,shareflag,ts,validateformula) values( '公共薪资项目','SYSTEM',null,'0.8041666666666667',0,null,0,'hrwa.waitem',null,'HRWA','60130glbitem',null,'1001Z710000000006DXV','waitem','@@@@',null,'160130glbitem0008',null,'2018-09-22 15:54:38',null);



insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,1,null,-1,'N',null,-1,'ishealthinsexsum_30',0,'N',1,'N','Y',24,null,0,'ishealthinsexsum_30','hrwa.waitem.ishealthinsexsum_30',null,'N',0,null,'1001Z710000000006DXV','1001TW100000000GHIES','@@@@',0,null,null,null,'N',1,24,'waitem','waitem',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_wa_item',0,'N',1,'N','N',0,null,0,'pk_wa_item','hrwa.waitem.pk_wa_item',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000006DXW','@@@@',0,null,null,null,'N',0,18,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'公共项目编码',null,0,1,null,-1,'N',null,-1,'code',0,'N',1,'Y','Y',0,null,0,'code','hrwa.waitem.code',null,'N',1,null,'1001Z710000000006DXV','1001Z710000000006DXX','@@@@',0,null,'160130glbitem0001',null,'N',1,3,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'公共项目名称',null,0,1,null,-1,'N',null,-1,'name',0,'N',1,'N','Y',0,null,0,'name','hrwa.waitem.name',null,'N',1,null,'1001Z710000000006DXV','1001Z710000000006DXY','@@@@',0,null,'160130glbitem0002',null,'N',1,4,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',0,null,0,'pk_group','hrwa.waitem.pk_group',null,'Y',0,null,'1001Z710000000006DXV','1001Z710000000006DXZ','@@@@',0,null,null,null,'N',0,1,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',0,null,0,'pk_org','hrwa.waitem.pk_org',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000006DY0','@@@@',0,null,null,null,'N',1,2,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'category_id',0,'N',1,'N','N',0,null,0,'category_id','hrwa.waitem.category_id',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000006DY6','@@@@',0,'薪资项目分类(自定义档案)',null,null,'N',1,5,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'true',0,1,null,-1,'N',null,-1,'mid',0,'N',1,'N','Y',0,null,0,'mid','hrwa.waitem.mid',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000006DY7','@@@@',0,null,null,null,'N',1,12,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'iitemtype',0,'N',1,'N','Y',0,null,0,'iitemtype','hrwa.waitem.iitemtype',null,'N',1,null,'1001Z710000000006DXV','1001Z710000000006DY9','@@@@',0,null,null,null,'N',1,6,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'true',0,0,null,-1,'N',null,-1,'defaultflag',0,'N',1,'N','N',0,null,0,'defaultflag','hrwa.waitem.defaultflag',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000006DYA','@@@@',0,null,null,null,'N',1,13,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'iproperty',0,'N',1,'N','Y',0,null,0,'iproperty','hrwa.waitem.iproperty',null,'N',1,null,'1001Z710000000006DXV','1001Z710000000006DYB','@@@@',0,null,null,null,'N',1,7,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'iflddecimal',0,'N',1,'N','Y',0,null,0,'iflddecimal','hrwa.waitem.iflddecimal',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000006DYC','@@@@',0,null,null,null,'N',1,9,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'iprivil',0,'N',1,'N','N',0,null,0,'iprivil','hrwa.waitem.iprivil',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000006DYD','@@@@',0,null,null,null,'N',0,19,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'纳入薪酬体系','true',0,1,null,-1,'N',null,-1,'isinhi',0,'N',1,'N','Y',0,null,0,'isinhi','hrwa.waitem.isinhi',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000006DYE','@@@@',0,null,'160130glbitem0003',null,'N',1,14,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'true',0,1,null,-1,'N',null,-1,'taxflag',0,'N',1,'N','Y',0,null,0,'taxflag','hrwa.waitem.taxflag',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000006DYG','@@@@',0,null,null,null,'N',1,15,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'true',0,1,null,-1,'N',null,-1,'clearflag',0,'N',1,'N','Y',0,null,0,'clearflag','hrwa.waitem.clearflag',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000006DYK','@@@@',0,null,null,null,'N',1,16,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'dr',0,'N',1,'N','N',0,null,0,'dr','hrwa.waitem.dr',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000006DYV','@@@@',0,null,null,null,'N',0,20,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',0,null,0,'ts','hrwa.waitem.ts',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000006DYW','@@@@',0,null,null,null,'N',0,21,'waitem','公共薪资项目',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'itemkey',null,'N',1,'N','N',0,null,0,'itemkey','hrwa.waitem.itemkey',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000007I2E',null,0,null,null,null,'N',0,17,'waitem','waitem',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,6,'数据来源',null,0,1,null,-1,'N',null,20,'datasourcetype',0,'N',1,'N','N',0,null,0,null,null,null,'N',0,null,'1001Z710000000006DXV','1001Z710000000009AVL','@@@@',0,null,'UC001-0000120',null,'N',1,1,'datasource','项目数据来源',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,4);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,12,'薪资项目预算上限',null,0,1,null,-1,'N',null,50,'sumceil',0,'N',1,'N','N',0,null,0,null,null,null,'N',0,null,'1001Z710000000006DXV','1001Z710000000009AW2','@@@@',0,null,'160130glbitem0004',null,'N',1,1,'prealert','预警条件设置',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,3);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,12,'薪资项目预算下限',null,0,1,null,-1,'N',null,50,'sumfloor',0,'N',1,'N','N',0,null,0,null,null,null,'N',0,null,'1001Z710000000006DXV','1001Z710000000009AWF','@@@@',0,null,'160130glbitem0005',null,'N',1,2,'prealert','预警条件设置',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,3);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,12,'个人薪资项目上限',null,0,1,null,-1,'N',null,50,'psnceil',null,'N',1,'N','N',0,null,0,null,null,null,'Y',0,null,'1001Z710000000006DXV','1001Z710000000009AWO',null,0,null,'160130glbitem0006',null,'N',1,3,'prealert','预警条件设置',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,3);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,12,'个人薪资项目下限',null,0,1,null,-1,'N',null,50,'psnfloor',null,'N',1,'N','N',0,null,0,null,null,null,'N',0,null,'1001Z710000000006DXV','1001Z710000000009AWP',null,0,null,'160130glbitem0007',null,'N',1,4,'prealert','预警条件设置',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,3);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ifldwidth',0,'N',1,'N','Y',0,null,0,'ifldwidth','hrwa.waitem.ifldwidth',null,'N',0,null,'1001Z710000000006DXV','1001Z710000000009RUP','@@@@',0,null,null,null,'N',1,8,'waitem','waitem',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'true',0,0,null,-1,'N',null,-1,'intotalitem',0,'N',1,'N','N',0,null,0,'intotalitem','hrwa.waitem.intotalitem',null,'N',0,null,'1001Z710000000006DXV','1001Z71000000000Y4E9','@@@@',0,null,null,null,'N',0,11,'waitem','waitem',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'totalitem',0,'N',1,'N','N',0,null,0,'totalitem','hrwa.waitem.totalitem',null,'N',0,null,'1001Z710000000006DXV','1001Z71000000000Y4EA','@@@@',0,null,null,null,'N',1,10,'waitem','waitem',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'isnhiitem_30',0,'N',1,'N','Y',23,null,0,'isnhiitem_30','hrwa.waitem.isnhiitem_30',null,'N',0,null,'1001Z710000000006DXV','1001ZZ10000000000PGU','@@@@',0,null,null,null,'N',1,23,'waitem','waitem',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ishealthinsparttime',0,'N',1,'N','Y',25,null,0,'ishealthinsparttime','hrwa.waitem.ishealthinsparttime',null,'N',0,null,'1001Z710000000006DXV','1001ZZ1000000000SEDQ','@@@@',0,null,null,null,'N',1,25,'waitem','waitem',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'avgcalcsalflag',null,'N',1,'N','Y',27,null,0,'avgcalcsalflag','hrwa.waitem.avgcalcsalflag',null,'N',0,null,'1001Z710000000006DXV','1001ZZ1000000000SW4L',null,0,null,null,null,'N',1,27,'waitem','waitem',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'isattend',null,'N',1,'N','Y',26,null,0,'isattend','hrwa.waitem.isattend',null,'N',0,null,'1001Z710000000006DXV','1001ZZ1000000000SW4M',null,0,null,null,null,'N',1,26,'waitem','waitem',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',null,'N',1,'N','Y',0,null,0,'creationtime','hrwa.waitem.creationtime',null,'N',0,null,'1001Z710000000006DXV','1004Z7100000000057I3',null,2,null,null,null,'N',1,2,'AuditInfo','AuditInfo',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',null,'N',1,'N','Y',0,null,0,'modifier','hrwa.waitem.modifier',null,'N',0,null,'1001Z710000000006DXV','1004Z7100000000057I4',null,2,null,null,null,'N',1,3,'AuditInfo','AuditInfo',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',null,'N',1,'N','Y',0,null,0,'creator','hrwa.waitem.creator',null,'N',0,null,'1001Z710000000006DXV','1004Z7100000000057I5',null,2,null,null,null,'N',1,1,'AuditInfo','AuditInfo',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',null,'N',1,'N','Y',0,null,0,'modifiedtime','hrwa.waitem.modifiedtime',null,'N',0,null,'1001Z710000000006DXV','1004Z7100000000057I6',null,2,null,null,null,'N',1,4,'AuditInfo','AuditInfo',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);

insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'idisplayseq',null,'N',1,'N','N',0,null,0,'idisplayseq','hrwa.waitem.idisplayseq',null,'N',0,null,'1001Z710000000006DXV','1004Z710000000006IKH',null,0,null,null,null,'N',0,22,'waitem','waitem',0,'2018-09-22 15:54:38','N',null,null,null,1,1,'N',1,null,1);



insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrwa.waitem',null,null,'1001Z710000000006DXV','1001ZZ1000000000SW4R',null,2,null,'UC001-0000095','AuditInfo',0,'审计信息','2018-09-22 15:54:42',null,null,null);

insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrwa.waitem','waitem',null,'1001Z710000000006DXV','1001ZZ1000000000SW4S',null,0,0,'160130glbitem0008','waitem',0,'公共薪资项目','2018-09-22 15:54:42',null,null,null);

insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( 'waitem',0,'hrwa.waitem',null,1,'1001Z710000000006DXV','1001ZZ1000000000SW4T',null,0,0,'160130glbitem0009','datasource',1,'项目数据来源','2018-09-22 15:54:42',null,null,null);

insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( 'waitem',0,null,null,1,'1001Z710000000006DXV','1001ZZ1000000000SW4U',null,0,0,'160130glbitem0010','prealert',2,'预警条件设置','2018-09-22 15:54:42',null,null,null);

