--考勤增加不同步班次標識  by George 20200326 特性 #33851
--TABLE 考勤档案(tbm_psndoc)新增欄位為 不同步班組工作日曆(isNotsyncal) 
ALTER TABLE tbm_psndoc ADD notsyncal char(1);
-- 新增 元數據 屬性 不同步班組工作日曆(isNotsyncal) 
insert into md_property ( id, accessorclassname, classid, createtime, creator, datatype, datatypestyle, defaultvalue, description, displayname, dr, help, isactive, hided, nullable, readonly, attrlength, attrmaxvalue, attrminvalue, modifier, modifytime, name, precise, refmodelname, attrsequence, ts, visibility, versiontype, fixedlength, calculation, isauthen, resid, customattr, notserialize, dynamicattr, dynamictable, accesspower, accesspowergroup, industry ) values (  'a01dacb7-b662-4ae0-b24b-7350dd0b8703', null, '6754de13-b3ee-4326-8e15-bc44029e64b2', null, null, 'BS000010000100001032',300, null, null, '不同步班組工作日曆',0, null, 'Y', 'N', 'Y', 'N',1, null, null, null, null, 'notsyncal',0, null,1, '2020-03-24 19:28:05',0,0, 'N', 'N', 'Y', null, 'N', 'N', 'N', null, 'N', null, '0' ); 
-- 新增 元數據 屬性與欄位與所屬table連結 不同步班組工作日曆(isNotsyncal) 
insert into md_ORMap ( attributeid, classid, columnid, dr, tableid, ts ) values (  'a01dacb7-b662-4ae0-b24b-7350dd0b8703', '6754de13-b3ee-4326-8e15-bc44029e64b2', 'tbm_psndoc@@@notsyncal',0, 'tbm_psndoc', '2020-03-24 19:28:05' ); 
-- 新增 元數據 欄位 不同步班組工作日曆(isNotsyncal) 
insert into md_column ( id, sqldatetype, createtime, creator, defaultvalue, description, displayname, dr, help, incrementseed, incrementstep, isactive, identitied, pkey, nullable, columnlength, modifier, modifytime, name, precise, columnsequence, tableid, ts, versiontype, resid, groupid, columntype, forlocale ) values (  'tbm_psndoc@@@notsyncal', 'char', null, null, null, null, '不同步班組工作日曆',0, null,null,null, 'Y', null, 'N', 'Y',1, null, null, 'notsyncal',0,26, 'tbm_psndoc', '2020-03-24 19:28:05',0, null, null,0, 'N' ); 
--節點:考勤档案，畫面依需求新增邏輯欄位為 不同步班組工作日曆(isNotsyncal)
INSERT INTO PUB_BILLTEMPLET_B (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, HYPERLINKFLAG, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTHYPERLINKFLAG, LISTSHOWFLAG, LISTSHOWORDER, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH) VALUES (1, 4, '不同步班組工作日曆', null, 0, 1, null, -1, 'N', null, 20, 'notsyncal', 0, 'N', 1, 'N', 'Y', 17, null, 0, 'notsyncal', 'hrta.tbm_psndoc.notsyncal', null, 'N', 0, null, '1001Z71000000000G50P', '1001ZZ100000000TNWG3', '@@@@', 0, null, null, null, 'N', 1, 17, 'tbminf', '考勤信息', 0, '2020-03-24 21:12:20', 'N', null, null, null, 1, 1, 'N', 1, null, 1);

