DROP INDEX IX_SEGDETAIL_PSNDOC;
DROP INDEX IX_SEGDTAIL_PSNDOC_OVERTIMEREG;
DROP INDEX IX_SEGDTAIL_PSNDOC_REGDATE;

CREATE INDEX IX_SEGDETAIL_PSNDOC ON HRTA_SEGDETAIL (PK_PSNDOC);
CREATE INDEX IX_SEGDTAIL_PSNDOC_OVERTIMEREG ON HRTA_SEGDETAIL (PK_PSNDOC, PK_OVERTIMEREG);
CREATE INDEX IX_SEGDTAIL_PSNDOC_REGDATE ON HRTA_SEGDETAIL (PK_PSNDOC, REGDATE);
