/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ta.leave;
	
import nc.vo.ta.annotation.IDColumn;
import nc.vo.ta.timebill.annotation.BeginTimeFieldName;
import nc.vo.ta.timebill.annotation.BillBeginDateFieldName;
import nc.vo.ta.timebill.annotation.BillEndDateFieldName;
import nc.vo.ta.timebill.annotation.EndTimeFieldName;
import nc.vo.ta.timebill.annotation.PkJobOrgFieldName;
import nc.vo.ta.timebill.annotation.PkPsndocFieldName;
import nc.vo.ta.timebill.annotation.PkPsnjobFieldName;


/**
 * <b> ??????????????????? </b>
 * <p>
 *     ??????????????????
 * </p>
 * ????????:${vmObject.createdDate}
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
@IDColumn(idColumn="pk_leavereg")
@BeginTimeFieldName(fieldName="leavebegintime")
@EndTimeFieldName(fieldName="leaveendtime")
@PkPsndocFieldName(fieldName="pk_psndoc")
@PkPsnjobFieldName(fieldName="pk_psnjob")
@PkJobOrgFieldName(fieldName="pk_joborg")
@BillBeginDateFieldName(fieldName="leavebegindate")
@BillEndDateFieldName(fieldName="leaveenddate")
public class LeaveRegVO extends LeaveCommonVO {
	private java.lang.String pk_leavereg;
	private java.lang.String leaveremark;
	private java.lang.String relatetel;
	private java.lang.String workprocess;
	private nc.vo.pub.lang.UFBoolean isleaveoff;
	private nc.vo.pub.lang.UFDateTime backtime;
	private java.lang.Integer billsource;
	private java.lang.String pk_billsourceh;
	private java.lang.String pk_billsourceb;
	private java.lang.String pk_adminorg;
	private java.lang.String creator;
	private nc.vo.pub.lang.UFDateTime creationtime;
	private java.lang.String modifier;
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	private java.lang.String leaveplan;
//add by chenklb@yonyou.com 2018.5.4   新增字段生效日期begin	
	private nc.vo.pub.lang.UFLiteralDate effectivedate;
	private nc.vo.pub.lang.UFDateTime approve_time;
	private java.lang.String waperiod;
	public java.lang.String getWaperiod() {
		return waperiod;
	}
	public void setWaperiod(java.lang.String waperiod) {
		this.waperiod = waperiod;
	}
	public nc.vo.pub.lang.UFDateTime getApprove_time() {
		return approve_time;
	}
	public void setApprove_time(nc.vo.pub.lang.UFDateTime approve_time) {
		this.approve_time = approve_time;
	}
		public String getLeaveplan(){
		return leaveplan;
	}
	public void setLeaveplan(String leaveplan){
		this.leaveplan=leaveplan;
	}
	public static final String PK_LEAVEREG = "pk_leavereg";
	public static final String LEAVEBEGINTIME = "leavebegintime";
	public static final String LEAVEENDTIME = "leaveendtime";
	public static final String LEAVEREMARK = "leaveremark";
	public static final String RELATETEL = "relatetel";
	public static final String PK_AGENTPSN = "pk_agentpsn";
	public static final String WORKPROCESS = "workprocess";
	public static final String ISLEAVEOFF = "isleaveoff";
	public static final String BACKTIME = "backtime";
	public static final String LEAVEBEGINDATE = "leavebegindate";
	public static final String LEAVEENDDATE = "leaveenddate";
	public static final String BILLSOURCE = "billsource";
	public static final String PK_BILLSOURCEH = "pk_billsourceh";
	public static final String PK_BILLSOURCEB = "pk_billsourceb";
	public static final String PK_ADMINORG = "pk_adminorg";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String APPROVE_TIME = "approve_time";	
	public static final String LEAVEPLAN = "leaveplan";
	//add by chenklb@yonyou.com 2018.5.4   新增字段生效日期begin
	public static final String EFFECTIVEDATE = "effectivedate";
	//add by chenklb@yonyou.com 2018.5.4   新增字段生效日期	end
	/**
	 * ????pk_leavereg??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getPk_leavereg () {
		return pk_leavereg;
	}   
	/**
	 * ????pk_leavereg??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newPk_leavereg java.lang.String
	 */
	public void setPk_leavereg (java.lang.String newPk_leavereg ) {
	 	this.pk_leavereg = newPk_leavereg;
	}
	/**
	 * ????leaveremark??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getLeaveremark () {
		return leaveremark;
	}   
	/**
	 * ????leaveremark??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newLeaveremark java.lang.String
	 */
	public void setLeaveremark (java.lang.String newLeaveremark ) {
	 	this.leaveremark = newLeaveremark;
	} 	  
	/**
	 * ????relatetel??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getRelatetel () {
		return relatetel;
	}   
	/**
	 * ????relatetel??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newRelatetel java.lang.String
	 */
	public void setRelatetel (java.lang.String newRelatetel ) {
	 	this.relatetel = newRelatetel;
	} 	  
	/**
	 * ????workprocess??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getWorkprocess () {
		return workprocess;
	}   
	/**
	 * ????workprocess??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newWorkprocess java.lang.String
	 */
	public void setWorkprocess (java.lang.String newWorkprocess ) {
	 	this.workprocess = newWorkprocess;
	} 	  
	
	/**
	 * ????isleaveoff??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsleaveoff () {
		return isleaveoff;
	}   
	/**
	 * ????isleaveoff??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newIsleaveoff nc.vo.pub.lang.UFBoolean
	 */
	public void setIsleaveoff (nc.vo.pub.lang.UFBoolean newIsleaveoff ) {
	 	this.isleaveoff = newIsleaveoff;
	} 	  
	/**
	 * ????backtime??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getBacktime () {
		return backtime;
	}   
	/**
	 * ????backtime??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newBacktime nc.vo.pub.lang.UFDateTime
	 */
	public void setBacktime (nc.vo.pub.lang.UFDateTime newBacktime ) {
	 	this.backtime = newBacktime;
	} 	  
	
	/**
	 * ????billsource??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getBillsource () {
		return billsource;
	}   
	/**
	 * ????billsource??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newBillsource java.lang.Integer
	 */
	public void setBillsource (java.lang.Integer newBillsource ) {
	 	this.billsource = newBillsource;
	} 	  
	/**
	 * ????pk_billsourceh??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getPk_billsourceh () {
		return pk_billsourceh;
	}   
	/**
	 * ????pk_billsourceh??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newPk_billsourceh java.lang.String
	 */
	public void setPk_billsourceh (java.lang.String newPk_billsourceh ) {
	 	this.pk_billsourceh = newPk_billsourceh;
	} 	  
	/**
	 * ????pk_billsourceb??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getPk_billsourceb () {
		return pk_billsourceb;
	}   
	/**
	 * ????pk_billsourceb??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newPk_billsourceb java.lang.String
	 */
	public void setPk_billsourceb (java.lang.String newPk_billsourceb ) {
	 	this.pk_billsourceb = newPk_billsourceb;
	} 	  
	public java.lang.String getPk_adminorg() {
		return pk_adminorg;
	}
	public void setPk_adminorg(java.lang.String pk_adminorg) {
		this.pk_adminorg = pk_adminorg;
	}
	/**
	 * ????creator??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getCreator () {
		return creator;
	}   
	/**
	 * ????creator??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newCreator java.lang.String
	 */
	public void setCreator (java.lang.String newCreator ) {
	 	this.creator = newCreator;
	} 	  
	/**
	 * ????creationtime??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime () {
		return creationtime;
	}   
	/**
	 * ????creationtime??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newCreationtime nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime (nc.vo.pub.lang.UFDateTime newCreationtime ) {
	 	this.creationtime = newCreationtime;
	} 	  
	/**
	 * ????modifier??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.String
	 */
	public java.lang.String getModifier () {
		return modifier;
	}   
	/**
	 * ????modifier??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newModifier java.lang.String
	 */
	public void setModifier (java.lang.String newModifier ) {
	 	this.modifier = newModifier;
	} 	  
	/**
	 * ????modifiedtime??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime () {
		return modifiedtime;
	}   
	/**
	 * ????modifiedtime??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newModifiedtime nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime (nc.vo.pub.lang.UFDateTime newModifiedtime ) {
	 	this.modifiedtime = newModifiedtime;
	} 	  
	/**
	 * ????dr??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * ????dr??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * ????ts??Getter????.
	 * ????????:$vmObject.createdDate
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * ????ts??Setter????.
	 * ????????:$vmObject.createdDate
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>????VO???????.
	  * <p>
	  * ????????:${vmObject.createdDate}
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>????????.
	  * <p>
	  * ????????:${vmObject.createdDate}
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_leavereg";
	}
    
	/**
	 * <p>?????????.
	 * <p>
	 * ????????:${vmObject.createdDate}
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "tbm_leavereg";
	}    
	
	/**
	 * <p>?????????.
	 * <p>
	 * ????????:${vmObject.createdDate}
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "tbm_leavereg";
	}    
    
    /**
	  * ???????????????????.
	  *
	  * ????????:${vmObject.createdDate}
	  */
     public LeaveRegVO() {
		super();	
	}
	@Override
	public boolean isAppBill() {
		return false;
	}
	@Override
	public void setAppBill(boolean isAppBill) {
		
	}
	public nc.vo.pub.lang.UFLiteralDate getEffectivedate() {
		return effectivedate;
	}
	public void setEffectivedate(nc.vo.pub.lang.UFLiteralDate effectivedate) {
		this.effectivedate = effectivedate;
	}
} 
