
delete pub_billtemplet_t where ( pk_billtemplet in ('1001Z7100000000095H7') and (dr=0 or dr is null) )
go

delete pub_billtemplet_b where ( pk_billtemplet in ('1001Z7100000000095H7') and (dr=0 or dr is null) )
go

delete pub_billtemplet where ( pk_billtemplet='1001Z7100000000095H7' and (bill_templetname='SYSTEM') and (dr=0 or dr is null) )
go


insert into pub_billtemplet(bill_templetcaption,bill_templetname,devorg,dividerproportion,dr,funccode,layer,metadataclass,model_type,modulecode,nodecode,options,pk_billtemplet,pk_billtypecode,pk_corp,pk_org,resid,shareflag,ts,validateformula) values( '加班登记表','SYSTEM',null,'0.6547085201793722',0,null,0,'hrta.hrtaovertimereg',null,'hrta','60170otreg',null,'1001Z7100000000095H7','ovtmreg','@@@@',null,'160170otreg0002',null,'2017-09-11 10:54:55',null)
go


insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'组织',null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','Y',0,null,0,'pk_org_v','hrta.hrtaovertimereg.pk_org_v',null,'N',0,null,'1001Z7100000000095H7','0001Z71000000000F9F2','@@@@',0,null,'160170awayapply0001',null,'N',1,2,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'部门',null,0,0,null,-1,'N',null,-1,'pk_dept_v',0,'N',1,'N','Y',0,null,0,'pk_dept_v','hrta.hrtaovertimereg.pk_dept_v',null,'N',0,null,'1001Z7100000000095H7','0001Z71000000000F9F3','@@@@',0,null,'UC000-0004064',null,'N',1,2,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,5,'項目',null,0,1,null,-1,'N',null,20,'Proj',null,'N',1,'N','Y',17,null,0,null,null,null,'N',0,null,'1001Z7100000000095H7','1001A110000000000RX2',null,0,'项目',null,null,'N',1,17,'ovtm','加班資訊',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'approve_time',0,'N',1,'N','Y',19,null,0,'approve_time','hrta.hrtaovertimereg.approve_time',null,'N',0,null,'1001Z7100000000095H7','1001AA10000000002QRN','@@@@',0,null,null,null,'N',1,19,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'projectcode',0,'N',1,'N','Y',18,null,0,'projectcode','hrta.hrtaovertimereg.projectcode',null,'N',0,null,'1001Z7100000000095H7','1001AA10000000002QRO','@@@@',0,'专案代码(自定义档案)',null,null,'N',1,18,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'endtimebeforecheck',0,'N',1,'N','N',0,null,0,'endtimebeforecheck','hrta.hrtaovertimereg.endtimebeforecheck',null,'N',0,null,'1001Z7100000000095H7','1001Z710000000004VYK','@@@@',0,null,null,null,'N',0,16,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'begintimebeforecheck',0,'N',1,'N','N',0,null,0,'begintimebeforecheck','hrta.hrtaovertimereg.begintimebeforecheck',null,'N',0,null,'1001Z7100000000095H7','1001Z710000000004VYL','@@@@',0,null,null,null,'N',0,15,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'员工号',null,0,1,null,-1,'N',null,-1,'pk_psnjob',null,'N',1,'Y','Y',0,null,0,'pk_psnjob','hrta.hrtaovertimereg.pk_psnjob',null,'N',1,null,'1001Z7100000000095H7','1001Z7100000000095G1',null,0,'<nc.ui.ta.psndoc.ref.TBMPsndocRefModel>,code=Y','160170awayapply0006',null,'N',1,1,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_overtimereg',0,'N',1,'N','N',0,null,0,'pk_overtimereg','hrta.hrtaovertimereg.pk_overtimereg',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095H8','@@@@',0,null,null,null,'N',0,8,'pk_overtimereg','加班登记表主键',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_psndoc',0,'N',1,'N','N',0,null,0,'pk_psndoc','hrta.hrtaovertimereg.pk_psndoc',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095H9','@@@@',0,null,null,null,'N',0,9,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'overtimealready',null,'N',1,'N','N',0,null,0,'overtimealready','hrta.hrtaovertimereg.overtimealready',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095HC',null,0,null,null,null,'N',0,14,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_billsourceh',null,'N',1,'N','N',0,null,0,'pk_billsourceh','hrta.hrtaovertimereg.pk_billsourceh',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095HD',null,0,null,null,null,'N',0,16,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'torestyear',null,'N',1,'N','N',0,null,0,'torestyear','hrta.hrtaovertimereg.torestyear',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095HJ',null,0,null,null,null,'N',0,12,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'开始时间',null,0,1,null,-1,'N',null,-1,'overtimebegintime',null,'N',1,'N','Y',0,null,0,'overtimebegintime','hrta.hrtaovertimereg.overtimebegintime',null,'N',1,null,'1001Z7100000000095H7','1001Z7100000000095HK',null,0,null,'UC000-0001894',null,'N',1,3,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'overtimebegindate',null,'N',1,'N','N',0,null,0,'overtimebegindate','hrta.hrtaovertimereg.overtimebegindate',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095HL',null,0,null,null,null,'N',0,10,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',0,null,0,'pk_group','hrta.hrtaovertimereg.pk_group',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095HO',null,0,null,null,null,'N',0,18,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'toresthour',null,'N',1,'N','N',0,null,0,'toresthour','hrta.hrtaovertimereg.toresthour',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095HS',null,0,null,null,null,'N',0,7,'ovtm',null,0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',0,null,0,'pk_org','hrta.hrtaovertimereg.pk_org',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095HT',null,0,null,null,null,'N',0,19,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'overtimeenddate',null,'N',1,'N','N',0,null,0,'overtimeenddate','hrta.hrtaovertimereg.overtimeenddate',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095HV',null,0,null,null,null,'N',0,11,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_psndoc.code',null,'N',1,'N','Y',0,null,0,'pk_psndoc.code','hrhi.bd_psndoc.code',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095HX',null,0,null,null,null,'N',1,1,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_psndoc.name',null,'N',1,'N','Y',0,null,0,'pk_psndoc.name','hrhi.bd_psndoc.name',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095I0',null,0,null,null,null,'N',1,1,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_billsourceb',null,'N',1,'N','N',0,null,0,'pk_billsourceb','hrta.hrtaovertimereg.pk_billsourceb',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095I3',null,0,null,null,null,'N',0,17,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_overtimetypecopy',null,'N',1,'N','N',0,null,0,'pk_overtimetypecopy','hrta.hrtaovertimereg.pk_overtimetypecopy',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095I4',null,0,null,null,null,'N',0,20,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_overtimegen',null,'N',1,'N','N',0,null,0,'pk_overtimegen','hrta.hrtaovertimereg.pk_overtimegen',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095I5',null,0,null,null,null,'N',0,15,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'torestmonth',null,'N',1,'N','N',0,null,0,'torestmonth','hrta.hrtaovertimereg.torestmonth',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095I6',null,0,null,null,null,'N',0,13,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',null,'N',1,'N','N',0,null,0,'modifiedtime','hrta.hrtaovertimereg.modifiedtime',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095IP',null,2,null,null,null,'N',1,4,'creator','creator',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',null,'N',1,'N','N',0,null,0,'creator','hrta.hrtaovertimereg.creator',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095IQ',null,2,null,null,null,'N',1,1,'creator','审计信息',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',null,'N',1,'N','N',0,null,0,'creationtime','hrta.hrtaovertimereg.creationtime',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095IR',null,2,null,null,null,'N',1,2,'creator','creator',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',null,'N',1,'N','N',0,null,0,'modifier','hrta.hrtaovertimereg.modifier',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095IS',null,2,null,null,null,'N',1,3,'creator','creator',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,0,null,-1,'N',null,-1,'istorest',null,'N',1,'N','Y',0,null,0,'istorest','hrta.hrtaovertimereg.istorest',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095JE',null,0,null,null,null,'N',1,11,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'申请时长',null,0,0,null,-1,'N',null,-1,'overtimehour',null,'N',1,'N','Y',0,null,0,'overtimehour','hrta.hrtaovertimereg.overtimehour',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095JF',null,0,null,'160170otapply0005',null,'N',1,5,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'overtimeremark',null,'N',1,'N','Y',0,null,0,'overtimeremark','hrta.hrtaovertimereg.overtimeremark',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095JG',null,0,null,null,null,'N',1,13,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,1,null,-1,'N',null,-1,'isneedcheck',null,'N',1,'N','Y',0,null,0,'isneedcheck','hrta.hrtaovertimereg.isneedcheck',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095JH',null,0,null,null,null,'N',1,10,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'结束时间',null,0,1,null,-1,'N',null,-1,'overtimeendtime',null,'N',1,'N','Y',0,null,0,'overtimeendtime','hrta.hrtaovertimereg.overtimeendtime',null,'N',1,null,'1001Z7100000000095H7','1001Z7100000000095JI',null,0,null,'UC000-0003232',null,'N',1,3,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'billsource',null,'N',1,'N','Y',0,null,0,'billsource','hrta.hrtaovertimereg.billsource',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095JJ',null,0,null,null,null,'N',1,14,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'扣除时间（分钟）',null,0,1,null,-1,'N',null,-1,'deduct',null,'N',1,'N','Y',0,null,0,'deduct','hrta.hrtaovertimereg.deduct',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095JL',null,0,null,'160170otreg0001',null,'N',1,4,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_overtimetype',null,'N',1,'N','Y',0,null,0,'pk_overtimetype','hrta.hrtaovertimereg.pk_overtimetype',null,'N',1,null,'1001Z7100000000095H7','1001Z7100000000095JM',null,0,'加班类别,code=N',null,null,'N',1,1,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'实际时长',null,0,0,null,-1,'N',null,-1,'acthour',null,'N',1,'N','Y',0,null,0,'acthour','hrta.hrtaovertimereg.acthour',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095JN',null,0,null,'160170otapply0001',null,'N',1,6,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,0,null,-1,'N',null,-1,'ischeck',null,'N',1,'N','Y',0,null,0,'ischeck','hrta.hrtaovertimereg.ischeck',null,'N',0,null,'1001Z7100000000095H7','1001Z7100000000095JO',null,0,null,null,null,'N',1,12,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',0,null,0,'ts','hrta.hrtaovertimereg.ts',null,'N',0,null,'1001Z7100000000095H7','1002Z710000000004EY9','@@@@',0,null,null,null,'N',0,21,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_job',0,'N',1,'N','N',0,null,0,'pk_job','hrhi.hi_psnjob.pk_job',null,'N',0,null,'1001Z7100000000095H7','1002Z7100000000064PS','@@@@',0,null,null,null,'N',1,7,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_post',0,'N',1,'N','N',0,null,0,'pk_post','hrhi.hi_psnjob.pk_post',null,'N',0,null,'1001Z7100000000095H7','1002Z7100000000064PT','@@@@',0,null,null,null,'N',1,6,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_overtimetypecopy',-1,'pk_overtimetypecopy.timeitemunit',0,'N',1,'N','Y',0,null,0,'timeitemunit','hrta.overtimetypecopy.timeitemunit',null,'N',0,null,'1001Z7100000000095H7','1002Z710000000009ORX','@@@@',0,null,null,null,'N',0,9,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_psnorg',0,'N',1,'N','N',0,null,0,'pk_psnorg','hrta.hrtaovertimereg.pk_psnorg',null,'N',0,null,'1001Z7100000000095H7','1002Z71000000000NHOO','@@@@',0,null,null,null,'N',0,22,'pk_overtimereg','pk_overtimereg',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'diffhour',0,'N',1,'N','Y',0,null,0,'diffhour','hrta.hrtaovertimereg.diffhour',null,'N',0,null,'1001Z7100000000095H7','1002Z71000000000ZEOX','@@@@',0,null,null,null,'N',1,8,'ovtm','ovtm',0,'2017-09-11 10:54:55','N',null,null,null,1,1,'N',1,null,1)
go


insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrta.hrtaovertimereg',null,null,'1001Z7100000000095H7','1001AA10000000002QRZ',null,2,null,'UC001-0000095','creator',0,'审计信息','2017-09-11 10:54:57',null,null,null)
go
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrta.hrtaovertimereg',null,null,'1001Z7100000000095H7','1001AA10000000002QS0',null,0,0,'160170otreg0003','pk_overtimereg',0,'加班登记表主键','2017-09-11 10:54:57',null,null,null)
go
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( 'pk_overtimereg',0,'hrta.hrtaovertimereg',null,null,'1001Z7100000000095H7','1001AA10000000002QS1',null,0,0,'160170otapply0010','ovtm',1,'加班信息','2017-09-11 10:54:57',null,null,null)
go
