
delete pub_billtemplet_t where ( pk_billtemplet in ('1001Z710000000003IJS') and (dr=0 or dr is null) )
go

delete pub_billtemplet_b where ( pk_billtemplet in ('1001Z710000000003IJS') and (dr=0 or dr is null) )
go

delete pub_billtemplet where ( pk_billtemplet='1001Z710000000003IJS' and (bill_templetname='SYSTEM') and (dr=0 or dr is null) )
go


insert into pub_billtemplet(bill_templetcaption,bill_templetname,devorg,dividerproportion,dr,funccode,layer,metadataclass,model_type,modulecode,nodecode,options,pk_billtemplet,pk_billtypecode,pk_corp,pk_org,resid,shareflag,ts,validateformula) values( '加班申请单','SYSTEM',null,null,0,null,0,'hrta.hrtaovertimeh',null,'hrta','60170otapply',null,'1001Z710000000003IJS','overtime','@@@@',null,'160170otapply0007',null,'2017-09-11 11:03:32',null)
go


insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'组织',null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','Y',0,null,0,'pk_org_v','hrta.hrtaovertimeh.pk_org_v',null,'N',0,null,'1001Z710000000003IJS','0001Z71000000000F9EU','@@@@',0,null,'160170awayapply0001',null,'N',1,2,'psnjob','psnjob',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'部门',null,0,0,null,-1,'N',null,-1,'pk_dept_v',0,'N',1,'N','Y',0,null,0,'pk_dept_v','hrta.hrtaovertimeh.pk_dept_v',null,'N',0,null,'1001Z710000000003IJS','0001Z71000000000F9EV','@@@@',0,null,'UC000-0004064',null,'N',1,2,'psnjob','psnjob',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'开始时间',null,0,1,null,-1,'N',null,-1,'overtimebegintime',0,'N',1,'N','Y',0,null,0,'overtimebegintime','hrta.hrtaovertimeb.overtimebegintime',null,'N',1,null,'1001Z710000000003IJS','0001Z71000000000F9EW','@@@@',1,null,'UC000-0001894',null,'N',1,2,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,150)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'结束时间',null,0,1,null,-1,'N',null,-1,'overtimeendtime',0,'N',1,'N','Y',0,null,0,'overtimeendtime','hrta.hrtaovertimeb.overtimeendtime',null,'N',1,null,'1001Z710000000003IJS','0001Z71000000000F9EY','@@@@',1,null,'UC000-0003232',null,'N',1,2,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,150)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'projectcode',0,'N',1,'N','Y',16,null,0,'projectcode','hrta.hrtaovertimeb.projectcode',null,'N',0,null,'1001Z710000000003IJS','1001AA10000000002QRS','@@@@',1,'专案代码(自定义档案),code=N',null,null,'N',1,16,'overtime_sub','overtime_sub',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_overtimeh',0,'N',1,'N','N',0,null,0,'pk_overtimeh','hrta.hrtaovertimeh.pk_overtimeh',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IJT','@@@@',0,null,null,null,'N',0,13,'pk_overtimeh','加班单主键',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_overtimeb',0,'N',1,'N','N',0,null,0,'pk_overtimeb','hrta.hrtaovertimeb.pk_overtimeb',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IJV','@@@@',1,null,null,null,'N',0,10,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',0,null,0,'ts','hrta.hrtaovertimeb.ts',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IJW','@@@@',1,null,null,null,'N',0,9,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'approve_state',0,'N',1,'N','Y',0,null,0,'approve_state','hrta.hrtaovertimeh.approve_state',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IJX','@@@@',0,null,null,null,'N',1,5,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'实际时长',null,0,0,null,-1,'N',null,-1,'acthour',0,'N',1,'N','N',0,null,0,'acthour','hrta.hrtaovertimeb.acthour',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IJY','@@@@',1,null,'160170otapply0001',null,'N',0,5,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'overtimeenddate',0,'N',1,'N','N',0,null,0,'overtimeenddate','hrta.hrtaovertimeb.overtimeenddate',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IK1','@@@@',1,null,null,null,'N',0,14,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'billmaker',0,'N',1,'N','Y',0,null,0,'billmaker','hrta.hrtaovertimeh.billmaker',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IK2','@@@@',0,null,null,null,'N',1,6,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'approve_time',0,'N',1,'N','N',0,null,0,'approve_time','hrta.hrtaovertimeh.approve_time',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IK3','@@@@',0,null,null,null,'N',0,10,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'approve_note',0,'N',1,'N','N',0,null,0,'approve_note','hrta.hrtaovertimeh.approve_note',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IK4','@@@@',0,null,null,null,'N',0,12,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'流程类型code',null,0,0,null,-1,'N',null,-1,'transtype',0,'N',1,'N','N',0,null,0,'transtype','hrta.hrtaovertimeh.transtype',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IK5','@@@@',0,'影响因素单据类型','160170otapply0002',null,'N',0,4,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'fun_code',0,'N',1,'N','N',0,null,0,'fun_code','hrta.hrtaovertimeh.fun_code',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IK6','@@@@',0,null,null,null,'N',0,8,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'申请单编码',null,0,1,null,-1,'N',null,-1,'bill_code',0,'N',1,'Y','Y',0,null,0,'bill_code','hrta.hrtaovertimeh.bill_code',null,'N',1,null,'1001Z710000000003IJS','1001Z710000000003IKA','@@@@',0,null,'UC000-0002964',null,'N',1,1,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'overtimebegindate',0,'N',1,'N','N',0,null,0,'overtimebegindate','hrta.hrtaovertimeb.overtimebegindate',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKB','@@@@',1,null,null,null,'N',0,15,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'isneedcheck',0,'N',1,'N','Y',0,null,0,'isneedcheck','hrta.hrtaovertimeb.isneedcheck',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKC','@@@@',1,null,null,null,'N',1,8,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',0,null,0,'pk_group','hrta.hrtaovertimeh.pk_group',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKD','@@@@',0,null,null,null,'N',0,14,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','N',0,null,0,'creationtime','hrta.hrtaovertimeh.creationtime',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKH','@@@@',2,null,null,null,'N',1,2,'creator','creator',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'扣除时间(分钟)',null,0,1,null,-1,'N',null,-1,'deduct',0,'N',1,'N','Y',0,null,0,'deduct','hrta.hrtaovertimeb.deduct',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKI','@@@@',1,null,'160170otapply0003',null,'N',1,4,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'overtimealready',0,'N',1,'N','Y',0,null,0,'overtimealready','hrta.hrtaovertimeb.overtimealready',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKJ','@@@@',1,null,null,null,'N',1,6,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','N',0,null,0,'modifiedtime','hrta.hrtaovertimeh.modifiedtime',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKK','@@@@',2,null,null,null,'N',1,4,'creator','creator',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'overtimeremark',0,'N',1,'N','Y',0,null,0,'overtimeremark','hrta.hrtaovertimeb.overtimeremark',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKL','@@@@',1,null,null,null,'N',1,7,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',0,null,0,'pk_org','hrta.hrtaovertimeb.pk_org',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKM','@@@@',1,null,null,null,'N',0,13,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'approver',0,'N',1,'N','N',0,null,0,'approver','hrta.hrtaovertimeh.approver',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKN','@@@@',0,null,null,null,'N',0,11,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'apply_date',0,'N',1,'N','Y',0,null,0,'apply_date','hrta.hrtaovertimeh.apply_date',null,'N',1,null,'1001Z710000000003IJS','1001Z710000000003IKO','@@@@',0,null,null,null,'N',1,7,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'申请时长',null,0,0,null,-1,'N',null,-1,'overtimehour',0,'N',1,'N','Y',0,null,0,'overtimehour','hrta.hrtaovertimeb.overtimehour',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKP','@@@@',1,null,'160170otapply0005',null,'N',1,3,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',0,null,0,'pk_group','hrta.hrtaovertimeb.pk_group',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKQ','@@@@',1,null,null,null,'N',0,12,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',0,null,0,'creator','hrta.hrtaovertimeh.creator',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKR','@@@@',2,null,null,null,'N',1,1,'creator','创建人',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,0,null,-1,'N',null,-1,'ishrssbill',0,'N',1,'N','N',0,null,0,'ishrssbill','hrta.hrtaovertimeh.ishrssbill',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKT','@@@@',0,null,null,null,'N',0,9,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','N',0,null,0,'modifier','hrta.hrtaovertimeh.modifier',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKU','@@@@',2,null,null,null,'N',1,3,'creator','creator',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_overtimeh',0,'N',1,'N','N',0,null,0,'pk_overtimeh','hrta.hrtaovertimeb.pk_overtimeh',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKW','@@@@',1,null,null,null,'N',0,11,'overtime_sub','加班明细',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,100)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',0,null,0,'pk_org','hrta.hrtaovertimeh.pk_org',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003IKX','@@@@',0,null,null,null,'N',0,15,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'员工号',null,0,1,null,-1,'N',null,-1,'pk_psnjob',0,'N',1,'N','Y',0,null,0,'pk_psnjob','hrta.hrtaovertimeh.pk_psnjob',null,'N',1,null,'1001Z710000000003IJS','1001Z710000000003N6F','@@@@',0,'<nc.ui.ta.psndoc.ref.TBMPsndocRefModel>,code=Y','160170awayapply0006',null,'N',1,1,'psnjob','psnjob',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_psndoc.code',0,'N',1,'N','Y',0,null,0,'pk_psndoc.code','hrhi.bd_psndoc.code',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003N6G','@@@@',0,null,null,null,'N',1,1,'psnjob','psnjob',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_psndoc',0,'N',1,'N','N',0,null,0,'pk_psndoc','hrta.hrtaovertimeh.pk_psndoc',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003N6H','@@@@',0,null,null,null,'N',0,8,'psnjob','psnjob',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_psndoc.name',0,'N',1,'N','Y',0,null,0,'pk_psndoc.name','hrhi.bd_psndoc.name',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000003N6I','@@@@',0,null,null,null,'N',1,1,'psnjob','psnjob',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_overtimetype',0,'N',1,'N','N',0,null,0,'pk_overtimetype','hrta.hrtaovertimeh.pk_overtimetype',null,'N',1,null,'1001Z710000000003IJS','1001Z710000000003N6J','@@@@',0,'加班类别,code=N',null,null,'N',1,1,'type','type',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_overtimetypecopy',0,'N',1,'N','N',0,null,0,'pk_overtimetypecopy','hrta.hrtaovertimeh.pk_overtimetypecopy',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000004LWB','@@@@',0,null,null,null,'N',0,2,'type','type',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'sumhour',0,'N',1,'N','Y',0,null,0,'sumhour','hrta.hrtaovertimeh.sumhour',null,'N',0,null,'1001Z710000000003IJS','1001Z710000000006OQP','@@@@',0,null,null,null,'N',1,3,'type','type',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_billtype',0,'N',1,'N','N',0,null,0,'pk_billtype','hrta.hrtaovertimeh.pk_billtype',null,'N',0,null,'1001Z710000000003IJS','1002Z710000000004NFT','@@@@',0,null,null,null,'N',0,3,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'流程类型',null,0,1,null,-1,'N',null,-1,'transtypeid',0,'N',1,'N','Y',0,null,0,'transtypeid','hrta.hrtaovertimeh.transtypeid',null,'N',0,null,'1001Z710000000003IJS','1002Z710000000004NFU','@@@@',0,'影响因素交 易类型,code=N','160170otapply0006',null,'N',1,2,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',0,null,0,'ts','hrta.hrtaovertimeh.ts',null,'N',0,null,'1001Z710000000003IJS','1002Z710000000004NG5','@@@@',0,null,null,null,'N',0,16,'pk_overtimeh','pk_overtimeh',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_post',0,'N',1,'N','N',0,null,0,'pk_post','hrhi.hi_psnjob.pk_post',null,'N',0,null,'1001Z710000000003IJS','1002Z7100000000064PL','@@@@',0,null,null,null,'N',1,6,'psnjob','psnjob',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_job',0,'N',1,'N','N',0,null,0,'pk_job','hrhi.hi_psnjob.pk_job',null,'N',0,null,'1001Z710000000003IJS','1002Z7100000000064PM','@@@@',0,null,null,null,'N',1,7,'psnjob','psnjob',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_overtimetypecopy',-1,'pk_overtimetypecopy.timeitemunit',0,'N',1,'N','Y',0,null,0,'timeitemunit','hrta.overtimetypecopy.timeitemunit',null,'N',0,null,'1001Z710000000003IJS','1002Z710000000009ORN','@@@@',0,null,null,null,'N',0,4,'type','type',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_psnorg',0,'N',1,'N','N',0,null,0,'pk_psnorg','hrta.hrtaovertimeh.pk_psnorg',null,'N',0,null,'1001Z710000000003IJS','1002Z71000000000NHOI','@@@@',0,null,null,null,'N',0,9,'psnjob','psnjob',0,'2017-09-11 11:03:32','N',null,null,null,1,1,'N',1,null,1)
go


insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrta.hrtaovertimeh',null,null,'1001Z710000000003IJS','1001AA10000000002QSI',null,2,null,'UC001-0000095','creator',0,'审计信息','2017-09-11 11:03:33',null,null,null)
go
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrta.hrtaovertimeb','overtime_sub',null,'1001Z710000000003IJS','1001AA10000000002QSJ',null,1,1,'160170otapply0008','overtime_sub',0,'加班明细','2017-09-11 11:03:33',null,null,null)
go
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrta.hrtaovertimeh',null,null,'1001Z710000000003IJS','1001AA10000000002QSK',null,0,0,'160170otapply0009','pk_overtimeh',0,'加班单主键','2017-09-11 11:03:33',null,null,null)
go
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( 'pk_overtimeh',0,'hrta.hrtaovertimeh',null,null,'1001Z710000000003IJS','1001AA10000000002QSL',null,0,0,'160170awayapply0010','psnjob',1,'人员信息','2017-09-11 11:03:33',null,null,null)
go
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( 'pk_overtimeh',0,'hrta.hrtaovertimeh',null,null,'1001Z710000000003IJS','1001AA10000000002QSM',null,0,0,'160170otapply0010','type',2,'加班信息','2017-09-11 11:03:33',null,null,null)
go
