
delete pub_billtemplet_t where ( pk_billtemplet in ('1001Z710000000000CCM') and (dr=0 or dr is null) )
go

delete pub_billtemplet_b where ( pk_billtemplet in ('1001Z710000000000CCM') and (dr=0 or dr is null) )
go

delete pub_billtemplet where ( pk_billtemplet='1001Z710000000000CCM' and (bill_templetname='SYSTEM') and (dr=0 or dr is null) )
go


insert into pub_billtemplet(bill_templetcaption,bill_templetname,devorg,dividerproportion,dr,funccode,layer,metadataclass,model_type,modulecode,nodecode,options,pk_billtemplet,pk_billtypecode,pk_corp,pk_org,resid,shareflag,ts,validateformula) values( '休假登记表','SYSTEM',null,null,0,null,0,'hrta.hrtaleavereg',null,'hrta','60170lvreg',null,'1001Z710000000000CCM','6017leareg','@@@@',null,'160170lvreg0001',null,'2017-09-13 11:24:42',null)
go


insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'部门',null,0,0,null,-1,'N',null,-1,'pk_dept_v',0,'N',1,'N','Y',0,null,0,'pk_dept_v','hrta.hrtaleavereg.pk_dept_v',null,'N',0,null,'1001Z710000000000CCM','0001Z71000000000F9EP','@@@@',0,null,'UC000-0004064',null,'N',1,4,'hrtaleavereg','hrtaleavereg',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'组织',null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','Y',0,null,0,'pk_org_v','hrta.hrtaleavereg.pk_org_v',null,'N',0,null,'1001Z710000000000CCM','0001Z71000000000F9EQ','@@@@',0,null,'160170awayapply0001',null,'N',1,3,'hrtaleavereg','hrtaleavereg',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',0,null,0,'pk_org','hrta.hrtaleavereg.pk_org',null,'N',0,null,'1001Z710000000000CCM','0001Z71000000000I1P0',null,0,null,null,null,'N',0,15,'hrtaleavereg','hrtaleavereg',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'usefuldayorhour',0,'N',1,'N','Y',0,null,0,'usefuldayorhour','hrta.hrtaleavereg.usefuldayorhour',null,'N',0,null,'1001Z710000000000CCM','0001Z71000000002B1Z4','@@@@',0,'2,-100000000000000000000.00,100000000000000000000.00',null,null,'N',1,13,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'freezedayorhour',0,'N',1,'N','Y',0,null,0,'freezedayorhour','hrta.hrtaleavereg.freezedayorhour',null,'N',0,null,'1001Z710000000000CCM','0001Z71000000002B1Z5','@@@@',0,'2,-100000000000000000000.00,100000000000000000000.00',null,null,'N',1,15,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'approve_time',0,'N',1,'N','Y',26,null,0,'approve_time','hrta.hrtaleavereg.approve_time',null,'N',0,null,'1001Z710000000000CCM','1001AA10000000002W63','@@@@',0,null,null,null,'N',1,26,'leaveinf','leaveinf',0,'2017-09-13 11:24:43','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_leavereg',0,'N',1,'N','Y',0,null,0,'pk_leavereg','hrta.hrtaleavereg.pk_leavereg',null,'N',0,null,'1001Z710000000000CCM','1001Z710000000000CCN','@@@@',0,null,null,null,'N',1,11,'hrtaleavereg','人员信息',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_billsourceb',0,'N',1,'N','Y',0,null,0,'pk_billsourceb','hrta.hrtaleavereg.pk_billsourceb',null,'N',0,null,'1001Z710000000000CCM','1001Z710000000000CCT','@@@@',0,null,null,null,'N',1,9,'hrtaleavereg','人员信息',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',0,null,0,'ts','hrta.hrtaleavereg.ts',null,'N',0,null,'1001Z710000000000CCM','1001Z710000000000CD0','@@@@',0,null,null,null,'N',0,10,'hrtaleavereg','人员信息',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_billsourceh',0,'N',1,'N','Y',0,null,0,'pk_billsourceh','hrta.hrtaleavereg.pk_billsourceh',null,'N',0,null,'1001Z710000000000CCM','1001Z710000000000CD7','@@@@',0,null,null,null,'N',1,8,'hrtaleavereg','人员信息',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','Y',0,null,0,'pk_group','hrta.hrtaleavereg.pk_group',null,'N',0,null,'1001Z710000000000CCM','1001Z710000000000CD9','@@@@',0,null,null,null,'N',1,7,'hrtaleavereg','人员信息',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'员工号',null,0,1,null,-1,'N',null,-1,'pk_psnjob',0,'N',1,'Y','Y',0,null,0,'pk_psnjob','hrta.hrtaleavereg.pk_psnjob',null,'N',0,null,'1001Z710000000000CCM','1001Z710000000000CDA','@@@@',0,'<nc.ui.ta.psndoc.ref.TBMPsndocRefModel>,code=Y','160170lvapl0009',null,'N',1,1,'hrtaleavereg','人员信息',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_psndoc',0,'N',1,'N','Y',0,null,0,'pk_psndoc','hrta.hrtaleavereg.pk_psndoc',null,'N',0,null,'1001Z710000000000CCM','1001Z710000000000CDI','@@@@',0,null,null,null,'N',1,12,'hrtaleavereg','人员信息',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'creator',0,'N',1,'N','N',0,null,0,'creator','hrta.hrtaleavereg.creator',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DRDD','@@@@',2,null,null,null,'N',1,1,'hrtaleavereg_t','审计信息',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','N',0,null,0,'creationtime','hrta.hrtaleavereg.creationtime',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DRDE','@@@@',2,null,null,null,'N',1,2,'hrtaleavereg_t','审计信息',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'modifier',0,'N',1,'N','N',0,null,0,'modifier','hrta.hrtaleavereg.modifier',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DRDF','@@@@',2,null,null,null,'N',1,3,'hrtaleavereg_t','审计信息',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','N',0,null,0,'modifiedtime','hrta.hrtaleavereg.modifiedtime',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DRDG','@@@@',2,null,null,null,'N',1,4,'hrtaleavereg_t','审计信息',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lactationholidaytype',0,'N',1,'N','Y',0,null,0,'lactationholidaytype','hrta.hrtaleavereg.lactationholidaytype',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTOP','@@@@',0,null,null,null,'N',1,7,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'leaveenddate',0,'N',1,'N','N',0,null,0,'leaveenddate','hrta.hrtaleavereg.leaveenddate',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTOQ','@@@@',0,null,null,null,'N',1,6,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'backtime',0,'N',1,'N','Y',0,null,0,'backtime','hrta.hrtaleavereg.backtime',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTOR','@@@@',0,null,null,null,'N',1,21,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'realdayorhour',0,'N',1,'N','Y',0,null,0,'realdayorhour','hrta.hrtaleavereg.realdayorhour',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTOS','@@@@',0,'2,-1000000000000.00,1000000000000.00',null,null,'N',1,11,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'leavehour',0,'N',1,'N','Y',0,null,0,'leavehour','hrta.hrtaleavereg.leavehour',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTOT','@@@@',0,'2,-1000000000000.00,1000000000000.00',null,null,'N',1,9,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'leavebegindate',0,'N',1,'N','N',0,null,0,'leavebegindate','hrta.hrtaleavereg.leavebegindate',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTOU','@@@@',0,null,null,null,'N',1,5,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'restdayorhour',0,'N',1,'N','Y',0,null,0,'restdayorhour','hrta.hrtaleavereg.restdayorhour',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTOV','@@@@',0,'2,-1000000000000.00,1000000000000.00',null,null,'N',1,12,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_leavetypecopy',0,'N',1,'N','N',0,null,0,'pk_leavetypecopy','hrta.hrtaleavereg.pk_leavetypecopy',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTOW','@@@@',0,null,null,null,'N',0,2,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'resteddayorhour',0,'N',1,'N','Y',0,null,0,'resteddayorhour','hrta.hrtaleavereg.resteddayorhour',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTOX','@@@@',0,'2,-1000000000000.00,1000000000000.00',null,null,'N',1,10,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,1,null,-1,'N',null,-1,'isleaveoff',0,'N',1,'N','Y',0,null,0,'isleaveoff','hrta.hrtaleavereg.isleaveoff',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTOY','@@@@',0,null,null,null,'N',1,20,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'leavebegintime',0,'N',1,'N','Y',0,null,0,'leavebegintime','hrta.hrtaleavereg.leavebegintime',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTOZ','@@@@',0,null,null,null,'N',1,3,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'leaveyear',0,'N',1,'N','Y',0,null,0,'leaveyear','hrta.hrtaleavereg.leaveyear',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTP0','@@@@',0,null,null,null,'N',1,1,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'leavemonth',0,'N',1,'N','Y',0,null,0,'leavemonth','hrta.hrtaleavereg.leavemonth',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTP1','@@@@',0,null,null,null,'N',1,2,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_leavetype',0,'N',1,'N','Y',0,null,0,'pk_leavetype','hrta.hrtaleavereg.pk_leavetype',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTP2','@@@@',0,'休假类别,code=N',null,null,'N',1,0,'leaveinf','休假信息',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,1,null,-1,'N',null,-1,'islactation',0,'N',1,'N','N',0,null,0,'islactation','hrta.hrtaleavereg.islactation',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTP3','@@@@',0,null,null,null,'N',0,9,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'leaveendtime',0,'N',1,'N','Y',0,null,0,'leaveendtime','hrta.hrtaleavereg.leaveendtime',null,'N',0,null,'1001Z710000000000CCM','1001Z71000000000DTP4','@@@@',0,null,null,null,'N',1,4,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'relatetel',null,'N',1,'N','N',0,null,0,'relatetel','hrta.hrtaleavereg.relatetel',null,'N',0,null,'1001Z710000000000CCM','1002Z710000000001GH7',null,0,null,null,null,'N',1,16,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'workprocess',null,'N',1,'N','N',0,null,0,'workprocess','hrta.hrtaleavereg.workprocess',null,'N',0,null,'1001Z710000000000CCM','1002Z710000000001GH8',null,0,null,null,null,'N',1,18,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'leaveremark',null,'N',1,'N','N',0,null,0,'leaveremark','hrta.hrtaleavereg.leaveremark',null,'N',0,null,'1001Z710000000000CCM','1002Z710000000001GH9',null,0,null,null,null,'N',1,19,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_agentpsn',null,'N',1,'N','N',0,null,0,'pk_agentpsn','hrta.hrtaleavereg.pk_agentpsn',null,'N',0,null,'1001Z710000000000CCM','1002Z710000000001GHA',null,0,'人员工作记录(左树不含下级HR)',null,null,'N',1,17,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'lactationhour',null,'N',1,'N','Y',0,null,0,'lactationhour','hrta.hrtaleavereg.lactationhour',null,'N',0,null,'1001Z710000000000CCM','1002Z710000000001GHE',null,0,'2,0.00,72.00',null,null,'N',1,8,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_psndoc.name',0,'N',1,'N','Y',0,null,0,'pk_psndoc.name','hrhi.bd_psndoc.name',null,'N',0,null,'1001Z710000000000CCM','1002Z710000000001GHU','@@@@',0,null,null,null,'N',1,2,'hrtaleavereg','hrtaleavereg',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'billsource',0,'N',1,'N','Y',0,null,0,'billsource','hrta.hrtaleavereg.billsource',null,'N',0,null,'1001Z710000000000CCM','1002Z710000000004LW9','@@@@',0,null,null,null,'N',1,22,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_job',0,'N',1,'N','N',0,null,0,'pk_job','hrhi.hi_psnjob.pk_job',null,'N',0,null,'1001Z710000000000CCM','1002Z710000000008G14','@@@@',0,null,null,null,'N',1,6,'hrtaleavereg','hrtaleavereg',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_psnjob',-1,'pk_psnjob.pk_post',0,'N',1,'N','N',0,null,0,'pk_post','hrhi.hi_psnjob.pk_post',null,'N',0,null,'1001Z710000000000CCM','1002Z710000000008G15','@@@@',0,null,null,null,'N',1,5,'hrtaleavereg','hrtaleavereg',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N','pk_leavetypecopy',-1,'pk_leavetypecopy.timeitemunit',null,'N',1,'N','Y',0,null,0,'timeitemunit','hrta.leavetypecopy.timeitemunit',null,'N',0,null,'1001Z710000000000CCM','1002Z710000000009KWR',null,0,null,null,null,'N',0,14,'leaveinf','leaveinf',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_psnorg',null,'N',1,'N','N',0,null,0,'pk_psnorg','hrta.hrtaleavereg.pk_psnorg',null,'N',0,null,'1001Z710000000000CCM','1002Z71000000000MFVH',null,0,null,null,null,'N',0,13,'hrtaleavereg','hrtaleavereg',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'1',0,1,null,-1,'N',null,-1,'leaveindex',null,'N',1,'N','N',0,null,0,'leaveindex','hrta.hrtaleavereg.leaveindex',null,'N',0,null,'1001Z710000000000CCM','1002Z71000000000MFVI',null,0,null,null,null,'N',0,14,'hrtaleavereg','hrtaleavereg',0,'2017-09-13 11:24:42','N',null,null,null,1,1,'N',1,null,1)
go


insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrta.hrtaleavereg',null,null,'1001Z710000000000CCM','1001AA10000000002W64',null,0,0,'160170awayapply0010','hrtaleavereg',0,'人员信息','2017-09-13 11:25:02',null,null,null)
go
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrta.hrtaleavereg',null,2,'1001Z710000000000CCM','1001AA10000000002W65',null,2,2,'UC001-0000095','hrtaleavereg_t',0,'审计信息','2017-09-13 11:25:02',null,null,null)
go
insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( 'hrtaleavereg',0,'hrta.hrtaleavereg',null,null,'1001Z710000000000CCM','1001AA10000000002W66',null,0,0,'160170lvapl0008','leaveinf',1,'休假信息','2017-09-13 11:25:02',null,null,null)
go
