
delete pub_billtemplet_t where ( pk_billtemplet in ('1001Z71000000002MFPB') and (dr=0 or dr is null) )
go

delete pub_billtemplet_b where ( pk_billtemplet in ('1001Z71000000002MFPB') and (dr=0 or dr is null) )
go

delete pub_billtemplet where ( pk_billtemplet='1001Z71000000002MFPB' and (bill_templetname='SYSTEM') and (dr=0 or dr is null) )
go


insert into pub_billtemplet(bill_templetcaption,bill_templetname,devorg,dividerproportion,dr,funccode,layer,metadataclass,model_type,modulecode,nodecode,options,pk_billtemplet,pk_billtypecode,pk_corp,pk_org,resid,shareflag,ts,validateformula) values( '社保数据','SYSTEM',null,null,0,null,0,'hrbm.bmdata',null,'HRBM','60150bmfile',null,'1001Z71000000002MFPB','bmfilesa','@@@@',null,'160150bmfile0012',null,'2017-11-13 18:25:32',null)
go


insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'社保供应商代码(公司)',null,0,1,null,-1,'N',null,-1,'def2',0,'N',1,'N','Y',6,null,0,'def2','hrbm.bmdata.def2',null,'N',0,null,'1001Z71000000002MFPB','1001AA1000000000GKGE','@@@@',0,'1001AA1000000000GGLF:社保供應商代碼(自定义档案)','160150bmfile0032',null,'N',1,15,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'社保供应商代码(个人)',null,0,1,null,-1,'N',null,-1,'def3',0,'N',1,'N','Y',7,null,0,'def3','hrbm.bmdata.def3',null,'N',0,null,'1001Z71000000002MFPB','1001AA1000000000GKGD','@@@@',0,'1001AA1000000000GGLF:社保供應商代碼(自定义档案)','160150bmfile0033',null,'N',1,16,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'cyear',0,'N',1,'N','N',11,null,0,'cyear','hrbm.bmdata.cyear',null,'N',0,null,'1001Z71000000002MFPB','1001Z710000000031KG6','@@@@',0,null,null,null,'N',0,10,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'cperiod',0,'N',1,'N','N',12,null,0,'cperiod','hrbm.bmdata.cperiod',null,'N',0,null,'1001Z71000000002MFPB','1001Z710000000031KG5','@@@@',0,null,null,null,'N',0,11,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_psndoc',0,'N',1,'N','N',9,null,0,'pk_psndoc','hrbm.bmdata.pk_psndoc',null,'N',0,null,'1001Z71000000002MFPB','1001Z710000000031KG4','@@@@',0,null,null,null,'N',0,8,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',10,null,0,'pk_org','hrbm.bmdata.pk_org',null,'N',0,null,'1001Z71000000002MFPB','1001Z710000000031KG3','@@@@',0,null,null,null,'N',0,9,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'险种',null,0,0,null,-1,'N',null,-1,'pk_bm_class',0,'N',1,'N','Y',0,null,0,'pk_bm_class','hrbm.bmdata.pk_bm_class',null,'N',0,null,'1001Z71000000002MFPB','1001Z710000000031B6Z','@@@@',0,null,'160150bmfile0007',null,'N',1,1,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_bm_data',0,'N',1,'N','N',8,null,0,'pk_bm_data','hrbm.bmdata.pk_bm_data',null,'N',0,null,'1001Z71000000002MFPB','1001Z710000000031B6W','@@@@',0,null,null,null,'N',0,7,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'accounttype',0,'N',1,'N','Y',5,null,0,'accounttype','hrbm.bmdata.accounttype',null,'N',0,null,'1001Z71000000002MFPB','1001Z71000000002MFPI','@@@@',0,null,null,null,'N',1,6,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'bmaccountno',0,'N',1,'N','Y',1,null,0,'bmaccountno','hrbm.bmdata.bmaccountno',null,'N',0,null,'1001Z71000000002MFPB','1001Z71000000002MFPF','@@@@',0,null,null,null,'N',1,2,'bmaccountno','社保账号',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'dbegindate',0,'N',1,'N','Y',3,null,0,'dbegindate','hrbm.bmdata.dbegindate',null,'N',0,null,'1001Z71000000002MFPB','1001Z71000000002MFPE','@@@@',0,null,null,null,'N',1,4,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,0,null,-1,'N',null,-1,'accountstate',0,'N',1,'N','Y',4,null,0,'accountstate','hrbm.bmdata.accountstate',null,'N',0,null,'1001Z71000000002MFPB','1001Z71000000002MFPD','@@@@',0,null,null,null,'N',1,5,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'paylocation',0,'N',1,'N','Y',2,null,0,'paylocation','hrbm.bmdata.paylocation',null,'N',0,null,'1001Z71000000002MFPB','1001Z71000000002MFPC','@@@@',0,null,null,null,'N',1,3,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,'false',0,0,null,-1,'N',null,-1,'checkflag',0,'N',1,'N','N',14,null,0,'checkflag','hrbm.bmdata.checkflag',null,'N',0,null,'1001Z71000000002MFPB','1001Z71000000000ICI8','@@@@',0,null,null,null,'N',0,13,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,'封存注销原因',null,0,0,null,-1,'N',null,-1,'vcancelreason',0,'N',1,'N','N',13,null,0,'vcancelreason','hrbm.bmdata.vcancelreason',null,'N',0,null,'1001Z71000000002MFPB','1001Z71000000000DSX7','@@@@',0,null,'160150bmfile0001',null,'N',0,12,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go
insert into pub_billtemplet_b(cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_billtemplet_b,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values( 1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',15,null,0,'ts','hrbm.bmdata.ts',null,'N',0,null,'1001Z71000000002MFPB','1001Z710000000005OZS','@@@@',0,null,null,null,'N',0,14,'bmaccountno','bmaccountno',0,'2017-11-13 18:25:32','N',null,null,null,1,1,'N',1,null,1)
go


insert into pub_billtemplet_t(basetab,dr,metadataclass,metadatapath,mixindex,pk_billtemplet,pk_billtemplet_t,pk_layout,pos,position,resid,tabcode,tabindex,tabname,ts,vdef1,vdef2,vdef3) values( null,0,'hrbm.bmdata',null,null,'1001Z71000000002MFPB','1001AA1000000000GKGJ',null,0,0,'160150bmfile0014','bmaccountno',0,'社保账号','2017-11-13 18:25:33',null,null,null)
go
